/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:39:28 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Podcasts.app/PlugIns/com.apple.podcasts.SpotlightIndexExtension.appex/com.apple.podcasts.SpotlightIndexExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class IMCloudSyncController, NSString;

@interface IMCloudSyncKeyValueStore : NSObject {

	IMCloudSyncController* _controller;
	NSString* _domain;

}

@property (nonatomic,retain,readonly) IMCloudSyncController * controller;              //@synthesize controller=_controller - In the implementation block
@property (nonatomic,retain) NSString * domain;                                        //@synthesize domain=_domain - In the implementation block
-(void)setDataAndKeysFromDictionary:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)dataForKeys:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_scheduleTransactionWithType:(int)arg1 completion:(/*^block*/id)arg2 keys:(id)arg3 values:(id)arg4 ;
-(void)setData:(id)arg1 forKey:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)dataForKey:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)init;
-(void)dealloc;
-(NSString *)domain;
-(IMCloudSyncController *)controller;
-(id)initWithController:(id)arg1 ;
-(void)setDomain:(NSString *)arg1 ;
@end

