/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:39:26 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Podcasts.app/PlugIns/com.apple.podcasts.SpotlightIndexExtension.appex/com.apple.podcasts.SpotlightIndexExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class UIImage, UIView, NSArray, NSIndexPath, UIImageView;

@interface IMCollectionChangeParameters : NSObject {

	UIImage* _image;
	UIView* _primaryView;
	NSArray* _secondaryViews;
	NSIndexPath* _indexPath;
	UIImageView* _imageView;

}

@property (nonatomic,retain) UIImage * image;                               //@synthesize image=_image - In the implementation block
@property (nonatomic,retain) UIView * primaryView;                          //@synthesize primaryView=_primaryView - In the implementation block
@property (nonatomic,retain) NSArray * secondaryViews;                      //@synthesize secondaryViews=_secondaryViews - In the implementation block
@property (nonatomic,retain) NSIndexPath * indexPath;                       //@synthesize indexPath=_indexPath - In the implementation block
@property (nonatomic,retain,readonly) UIImageView * imageView; 
-(void)setSecondaryViews:(NSArray *)arg1 ;
-(NSArray *)secondaryViews;
-(void)setImage:(UIImage *)arg1 ;
-(void)dealloc;
-(id)description;
-(NSIndexPath *)indexPath;
-(UIImage *)image;
-(void)setIndexPath:(NSIndexPath *)arg1 ;
-(UIImageView *)imageView;
-(void)setPrimaryView:(UIView *)arg1 ;
-(UIView *)primaryView;
@end

