/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:39:27 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Podcasts.app/PlugIns/com.apple.podcasts.SpotlightIndexExtension.appex/com.apple.podcasts.SpotlightIndexExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IMLibraryBooksViewControllerDelegate <NSObject>
@required
-(void)libraryBooksViewController:(id)arg1 didSelectObject:(id)arg2;
-(void)libraryBooksViewController:(id)arg1 didMoveItemAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
-(char)libraryBooksViewController:(id)arg1 isObjectSelected:(id)arg2;
-(void)libraryBooksViewController:(id)arg1 wasSwiped:(unsigned)arg2;
-(void)libraryBooksViewController:(id)arg1 searchTextDidChange:(id)arg2;

@end

