/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:39:27 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Podcasts.app/PlugIns/com.apple.podcasts.SpotlightIndexExtension.appex/com.apple.podcasts.SpotlightIndexExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <com.apple.podcasts.SpotlightIndexExtension/com.apple.podcasts.SpotlightIndexExtension-Structs.h>
#import <com.apple.podcasts.SpotlightIndexExtension/IMSplitViewController.h>
#import <UIKit/UIPopoverControllerDelegate.h>

@class UIBarButtonItem, UIPopoverController, NSString;

@interface IMSplitPopViewController : IMSplitViewController <UIPopoverControllerDelegate> {

	id _delegate;
	UIBarButtonItem* _barButtonPopSource;
	UIPopoverController* _popover;
	CGSize _popoverContentSize;
	char _popoverMode;
	int _style;
	Class _popoverBackgroundViewClass;
	char _forceSplit;

}

@property (assign,nonatomic) id<IMSplitPopViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) CGSize popoverContentSize;                                  //@synthesize popoverContentSize=_popoverContentSize - In the implementation block
@property (assign,nonatomic) char popoverMode;                                           //@synthesize popoverMode=_popoverMode - In the implementation block
@property (nonatomic,readonly) UIPopoverController * popover;                            //@synthesize popover=_popover - In the implementation block
@property (nonatomic,readonly) UIBarButtonItem * barButtonPopSource;                     //@synthesize barButtonPopSource=_barButtonPopSource - In the implementation block
@property (assign,nonatomic) int style;                                                  //@synthesize style=_style - In the implementation block
@property (nonatomic,retain) Class popoverBackgroundViewClass;                           //@synthesize popoverBackgroundViewClass=_popoverBackgroundViewClass - In the implementation block
@property (assign,nonatomic) char forceSplit;                                            //@synthesize forceSplit=_forceSplit - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)releaseViews;
-(void)setupModeForOrientation:(int)arg1 ;
-(char)forceSplit;
-(void)setupSplitMode;
-(void)setupPopoverMode;
-(void)onPopoverButtonClick:(id)arg1 ;
-(char)popoverMode;
-(void)setPopoverMode:(char)arg1 ;
-(UIBarButtonItem *)barButtonPopSource;
-(void)setForceSplit:(char)arg1 ;
-(void)setDelegate:(id<IMSplitPopViewControllerDelegate>)arg1 ;
-(void)dealloc;
-(id<IMSplitPopViewControllerDelegate>)delegate;
-(int)style;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidLayoutSubviews;
-(void)setStyle:(int)arg1 ;
-(void)setEditing:(char)arg1 animated:(char)arg2 ;
-(void)dismissPopoverAnimated:(char)arg1 ;
-(void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2 ;
-(void)popoverControllerDidDismissPopover:(id)arg1 ;
-(void)setPopoverBackgroundViewClass:(Class)arg1 ;
-(Class)popoverBackgroundViewClass;
-(CGSize)popoverContentSize;
-(void)setPopoverContentSize:(CGSize)arg1 ;
-(UIPopoverController *)popover;
@end

