/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:39:27 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Podcasts.app/PlugIns/com.apple.podcasts.SpotlightIndexExtension.appex/com.apple.podcasts.SpotlightIndexExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <com.apple.podcasts.SpotlightIndexExtension/com.apple.podcasts.SpotlightIndexExtension-Structs.h>
#import <UIKit/UIToolbar.h>
#import <com.apple.podcasts.SpotlightIndexExtension/IMTopBar.h>

@class NSArray, UIView, UIBarButtonItem, UIImage, UIImageView, NSString;

@interface IMToolbar : UIToolbar <IMTopBar> {

	char _bottom;
	NSArray* _leftItems;
	UIView* _titleView;
	NSArray* _rightItems;
	UIBarButtonItem* _titleViewBarButtonItem;
	UIImage* _backgroundImage;
	UIImage* _miniBackgroundImage;
	UIImage* _backgroundImageBottom;
	UIImage* _miniBackgroundImageBottom;
	UIImage* _shadowImage;
	UIImageView* _shadow;

}

@property (nonatomic,retain) UIImage * backgroundImage;                        //@synthesize backgroundImage=_backgroundImage - In the implementation block
@property (nonatomic,retain) UIImage * miniBackgroundImage;                    //@synthesize miniBackgroundImage=_miniBackgroundImage - In the implementation block
@property (nonatomic,retain) UIImage * backgroundImageBottom;                  //@synthesize backgroundImageBottom=_backgroundImageBottom - In the implementation block
@property (nonatomic,retain) UIImage * miniBackgroundImageBottom;              //@synthesize miniBackgroundImageBottom=_miniBackgroundImageBottom - In the implementation block
@property (nonatomic,readonly) char mini; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) char bottom;                                      //@synthesize bottom=_bottom - In the implementation block
@property (nonatomic,retain) NSArray * leftItems;                              //@synthesize leftItems=_leftItems - In the implementation block
@property (nonatomic,retain) UIView * titleView;                               //@synthesize titleView=_titleView - In the implementation block
@property (nonatomic,retain) NSArray * rightItems;                             //@synthesize rightItems=_rightItems - In the implementation block
@property (nonatomic,retain) UIImage * shadowImage;                            //@synthesize shadowImage=_shadowImage - In the implementation block
-(void)setLeftItems:(id)arg1 rightItems:(id)arg2 ;
-(void)_updateControlMiniState;
-(void)layoutShadow;
-(char)mini;
-(id)_toolbarItemSubviews;
-(void)setBackgroundImageBottom:(UIImage *)arg1 ;
-(void)setMiniBackgroundImageBottom:(UIImage *)arg1 ;
-(UIImage *)backgroundImageBottom;
-(UIImage *)miniBackgroundImageBottom;
-(void)layoutSubviews;
-(void)drawRect:(CGRect)arg1 ;
-(void)dealloc;
-(UIImage *)backgroundImage;
-(UIImage *)miniBackgroundImage;
-(UIImage *)shadowImage;
-(void)setShadowImage:(UIImage *)arg1 ;
-(UIView *)titleView;
-(void)setTitleView:(UIView *)arg1 ;
-(id)backgroundImageForToolbarPosition:(int)arg1 barMetrics:(int)arg2 ;
-(void)setBackgroundImage:(UIImage *)arg1 ;
-(void)setMiniBackgroundImage:(UIImage *)arg1 ;
-(void)setBackgroundImage:(id)arg1 forToolbarPosition:(int)arg2 barMetrics:(int)arg3 ;
-(void)_updateItems;
-(CGRect)_centerFrame;
-(NSArray *)leftItems;
-(NSArray *)rightItems;
-(void)setLeftItems:(NSArray *)arg1 ;
-(void)setRightItems:(NSArray *)arg1 ;
-(char)bottom;
-(void)setBottom:(char)arg1 ;
@end

