/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:39:41 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/StoreKitUIService.app/StoreKitUIService
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <StoreKitUIService/StoreKitUIService-Structs.h>
#import <UIKit/UIViewController.h>
#import <StoreKitUIService/ServiceAlertDelegate.h>
#import <libobjc.A.dylib/SKUIComposeReviewDelegate.h>
#import <libobjc.A.dylib/SUClientInterfaceDelegate.h>

@class ServiceAlertController, SKUIComposeReviewViewController, NSString;

@interface ServiceComposeReviewViewController : UIViewController <ServiceAlertDelegate, SKUIComposeReviewDelegate, SUClientInterfaceDelegate> {

	ServiceAlertController* _alertController;
	char _dismissAfterDialog;
	SKUIComposeReviewViewController* _underlyingViewController;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)_exportedInterface;
+(id)_remoteViewControllerInterface;
-(id)_clientViewControllerProxy;
-(void)alertController:(id)arg1 alertDidFinishWithButton:(id)arg2 ;
-(void)_dismissWithError:(id)arg1 ;
-(void)dealloc;
-(void)loadView;
-(void)_willAppearInRemoteViewController;
-(void)finishStarRatingPromptWithRating:(id)arg1 ;
-(void)loadReviewWithURL:(id)arg1 ;
-(void)clientKeyboardFrameChanged:(CGRect)arg1 ;
-(char)composeReviewViewController:(id)arg1 shouldSubmitReview:(id)arg2 ;
-(void)composeReviewViewController:(id)arg1 didFailWithDialog:(id)arg2 ;
-(void)composeReviewViewControllerDidSubmit:(id)arg1 ;
-(void)composeReviewViewControllerDidCancel:(id)arg1 ;
-(void)_presentAlertForDialog:(id)arg1 ;
-(void)composeReviewViewController:(id)arg1 presentDialog:(id)arg2 ;
@end

