/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:25:37 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/StoreKitUIService.app/StoreKitUIService
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSString;


@protocol SKUIHostApplicationProtocol <NSObject>
@property (nonatomic,copy,readonly) NSString * hostApplicationIdentifier; 
@required
-(NSString *)hostApplicationIdentifier;

@end

