/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:39:03 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileNotes.app/MobileNotes
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol ICDrawingControllerDelegate, OS_dispatch_queue, OS_dispatch_semaphore;
#import <MobileNotes/MobileNotes-Structs.h>
@class NSObject, NSMutableOrderedSet, ICDrawingRendererController, ICDrawing, ICDrawingInputController;

@interface ICDrawingController : NSObject {

	char _liveInteraction;
	NSObject*<ICDrawingControllerDelegate> _delegate;
	NSObject*<OS_dispatch_queue> _previewQueue;
	char _cachedImageValid;
	CGImageRef _cachedImage;
	char _imageNeedsSave;
	char _isSuspended;
	char _liveDrawing;
	NSMutableOrderedSet* _renderedCommands;
	ICDrawingRendererController* _rendererController;
	ICDrawing* _drawing;
	NSObject*<OS_dispatch_semaphore> _drawingSemaphore;
	NSObject*<OS_dispatch_semaphore> _interactSemaphore;
	NSObject*<OS_dispatch_queue> _interactQueue;
	NSObject*<OS_dispatch_queue> _suspendQueue;
	CGSize _pixelSize;
	CGSize _actualSize;

}

@property (nonatomic,retain) ICDrawingRendererController * rendererController;                //@synthesize rendererController=_rendererController - In the implementation block
@property (nonatomic,retain) ICDrawing * drawing;                                             //@synthesize drawing=_drawing - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_semaphore> drawingSemaphore;               //@synthesize drawingSemaphore=_drawingSemaphore - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_semaphore> interactSemaphore;              //@synthesize interactSemaphore=_interactSemaphore - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> interactQueue;                      //@synthesize interactQueue=_interactQueue - In the implementation block
@property (nonatomic,retain) NSMutableOrderedSet * renderedCommands;                          //@synthesize renderedCommands=_renderedCommands - In the implementation block
@property (assign,nonatomic) char isSuspended;                                                //@synthesize isSuspended=_isSuspended - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> suspendQueue;                       //@synthesize suspendQueue=_suspendQueue - In the implementation block
@property (assign) char liveDrawing;                                                          //@synthesize liveDrawing=_liveDrawing - In the implementation block
@property (nonatomic,readonly) ICDrawingInputController * inputController; 
@property (assign,nonatomic) char imageNeedsSave;                                             //@synthesize imageNeedsSave=_imageNeedsSave - In the implementation block
@property (nonatomic,readonly) CGSize pixelSize;                                              //@synthesize pixelSize=_pixelSize - In the implementation block
@property (nonatomic,readonly) CGSize actualSize;                                             //@synthesize actualSize=_actualSize - In the implementation block
-(void)setIsSuspended:(char)arg1 ;
-(id)initWithPixelSize:(CGSize)arg1 actualSize:(CGSize)arg2 ;
-(void)saveImageImmediatelyIfNeededWithCompletion:(/*^block*/id)arg1 ;
-(void)suspendDrawing;
-(void)resumeDrawing;
-(void)suspendDrawingImmediately:(char)arg1 ;
-(void)_clearCachedImage;
-(char)liveDrawing;
-(void)setLiveDrawing:(char)arg1 ;
-(void)_setDrawing:(id)arg1 initialDrawing:(id)arg2 withImage:(CGImageRef)arg3 andMask:(CGImageRef)arg4 setupComplete:(/*^block*/id)arg5 completion:(/*^block*/id)arg6 ;
-(void)setImageNeedsSave:(char)arg1 ;
-(void)_renderImage:(CGImageRef)arg1 andMask:(CGImageRef)arg2 ;
-(char)_loadInitialDrawing:(id)arg1 withImage:(CGImageRef)arg2 andMask:(CGImageRef)arg3 ;
-(char)_updateFrom:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_renderAllInCommandSpaceRect:(CGRect)arg1 completion:(/*^block*/id)arg2 ;
-(void)_setCachedImage:(CGImageRef)arg1 andMask:(CGImageRef)arg2 ;
-(void)_drawingChanged;
-(void)_renderCommands:(id)arg1 renderIntermediateSteps:(char)arg2 completion:(/*^block*/id)arg3 ;
-(void)_restoreValidStateCompletion:(/*^block*/id)arg1 ;
-(void)performAsyncInteractBlock:(/*^block*/id)arg1 ;
-(char)_saveAndUpdateFrom:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_saveImage;
-(void)_saveImageWithState:(int)arg1 ;
-(void)_didRenderCommands:(id)arg1 ;
-(void)removeCommandsInRect:(CGRect)arg1 from:(id)arg2 ;
-(ICDrawingRendererController *)rendererController;
-(void)_getImages;
-(NSObject*<OS_dispatch_queue>)interactQueue;
-(void)_saveImageIfNeeded;
-(void)claimLiveDrawingForDelegate:(id)arg1 ;
-(void)releaseLiveDrawingClaimForDelegate:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)didStartLiveInteractionWith:(id)arg1 ;
-(void)didEndLiveInteraction;
-(void)renderPreviewDrawing:(id)arg1 initialDrawing:(id)arg2 withImage:(CGImageRef)arg3 andMask:(CGImageRef)arg4 completion:(/*^block*/id)arg5 ;
-(void)setDrawingProvider:(id)arg1 finishedSetup:(/*^block*/id)arg2 completion:(/*^block*/id)arg3 ;
-(void)setDrawing:(id)arg1 initialDrawing:(id)arg2 withImage:(CGImageRef)arg3 andMask:(CGImageRef)arg4 setupComplete:(/*^block*/id)arg5 completion:(/*^block*/id)arg6 ;
-(void)updateOrientation:(int)arg1 ;
-(void)drawingChanged;
-(void)_renderCommands:(id)arg1 clippedToCommandSpaceRect:(CGRect)arg2 completion:(/*^block*/id)arg3 ;
-(id)addNewRenderedCommand:(id)arg1 ;
-(void)setRenderedCommands:(NSMutableOrderedSet *)arg1 ;
-(void)setRendererController:(ICDrawingRendererController *)arg1 ;
-(char)imageNeedsSave;
-(CGSize)actualSize;
-(NSObject*<OS_dispatch_semaphore>)drawingSemaphore;
-(void)setDrawingSemaphore:(NSObject*<OS_dispatch_semaphore>)arg1 ;
-(NSObject*<OS_dispatch_semaphore>)interactSemaphore;
-(void)setInteractSemaphore:(NSObject*<OS_dispatch_semaphore>)arg1 ;
-(void)setInteractQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)setSuspendQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(id)init;
-(char)isSuspended;
-(CGImageRef)_image;
-(void)dealloc;
-(CGImageRef)image;
-(ICDrawingInputController *)inputController;
-(NSObject*<OS_dispatch_queue>)suspendQueue;
-(NSMutableOrderedSet *)renderedCommands;
-(void)updateDrawing;
-(void)renderImage:(CGImageRef)arg1 andMask:(CGImageRef)arg2 forRenderedCommands:(id)arg3 thenRenderCommands:(id)arg4 completion:(/*^block*/id)arg5 ;
-(void)renderImage:(CGImageRef)arg1 andMask:(CGImageRef)arg2 forRenderedCommands:(id)arg3 thenRenderCommands:(id)arg4 inCommandSpaceClipRect:(CGRect)arg5 completion:(/*^block*/id)arg6 ;
-(void)renderCommands:(id)arg1 completion:(/*^block*/id)arg2 ;
-(ICDrawing *)drawing;
-(void)setDrawing:(ICDrawing *)arg1 ;
-(void)setTransientOrientation:(int)arg1 ;
-(CGSize)pixelSize;
@end

