/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:25:01 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileNotes.app/MobileNotes
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileNotes/MobileNotes-Structs.h>
#import <CoreImage/CIFeature.h>

@interface ICEdgeFeature : CIFeature {

	CGRect _clusterBounds;

}

@property (assign,nonatomic) CGRect clusterBounds;              //@synthesize clusterBounds=_clusterBounds - In the implementation block
-(void)setClusterBounds:(CGRect)arg1 ;
-(CGRect)clusterBounds;
-(CGRect)bounds;
-(id)description;
-(id)initWithBounds:(CGRect)arg1 ;
@end

