/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:59 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileNotes.app/MobileNotes
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class ICAttachment, MURemoteViewController, MarkupViewController, UIViewController;

@interface ICMarkupPresenter : NSObject {

	ICAttachment* _attachment;
	MURemoteViewController* _markupRemoteViewController;
	MarkupViewController* _markupViewController;
	UIViewController* _presentingViewController;
	/*^block*/id _frameBlock;
	/*^block*/id _completionBlock;

}

@property (retain) ICAttachment * attachment;                                                  //@synthesize attachment=_attachment - In the implementation block
@property (nonatomic,retain) MURemoteViewController * markupRemoteViewController;              //@synthesize markupRemoteViewController=_markupRemoteViewController - In the implementation block
@property (nonatomic,retain) MarkupViewController * markupViewController;                      //@synthesize markupViewController=_markupViewController - In the implementation block
@property (__weak) UIViewController * presentingViewController;                                //@synthesize presentingViewController=_presentingViewController - In the implementation block
@property (nonatomic,copy) id frameBlock;                                                      //@synthesize frameBlock=_frameBlock - In the implementation block
@property (nonatomic,copy) id completionBlock;                                                 //@synthesize completionBlock=_completionBlock - In the implementation block
+(void)markupAttachment:(id)arg1 fromView:(id)arg2 presentingViewController:(id)arg3 frameBlock:(/*^block*/id)arg4 completionBlock:(/*^block*/id)arg5 ;
+(void)cleanupMarkup;
-(void)setFrameBlock:(id)arg1 ;
-(id)frameBlock;
-(void)presentMarkupFromView:(id)arg1 ;
-(void)presentMarkupUsingExtensionFromView:(id)arg1 ;
-(void)presentMarkupViewControllerFromView:(id)arg1 ;
-(void)markupDoneAction:(id)arg1 ;
-(void)markupCancelAction:(id)arg1 ;
-(void)setMarkupRemoteViewController:(MURemoteViewController *)arg1 ;
-(MURemoteViewController *)markupRemoteViewController;
-(void)handleReturnedURL:(id)arg1 ;
-(id)completionBlock;
-(void)setCompletionBlock:(id)arg1 ;
-(UIViewController *)presentingViewController;
-(void)setPresentingViewController:(UIViewController *)arg1 ;
-(void)setAttachment:(ICAttachment *)arg1 ;
-(ICAttachment *)attachment;
-(void)dismissMarkupViewController;
-(void)setMarkupViewController:(MarkupViewController *)arg1 ;
-(MarkupViewController *)markupViewController;
@end

