/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:39:03 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileNotes.app/MobileNotes
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class ICAttachment;

@interface ICMarkupActivityItem : NSObject {

	ICAttachment* _attachment;

}

@property (nonatomic,retain) ICAttachment * attachment;              //@synthesize attachment=_attachment - In the implementation block
-(id)initWithAttachment:(id)arg1 ;
-(void)setAttachment:(ICAttachment *)arg1 ;
-(ICAttachment *)attachment;
@end

