/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:25:00 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileNotes.app/MobileNotes
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface ICMutableBool : NSObject {

	char _value;

}

@property (assign,nonatomic) char value;              //@synthesize value=_value - In the implementation block
-(char)value;
-(void)setValue:(char)arg1 ;
@end

