/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:39:05 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileNotes.app/MobileNotes
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileNotes/MobileNotes-Structs.h>
#import <Foundation/NSOperation.h>

@class ICNotesListTableViewCellWithImageView, NSString, NSCache, NSManagedObjectContext;

@interface ICNotesListBackgroundFetchOperation : NSOperation {

	char _thumbnailFetched;
	ICNotesListTableViewCellWithImageView* _tableViewCell;
	NSString* _noteIdentifier;
	float _thumbnailScale;
	NSCache* _thumbnailCache;
	NSCache* _cellDataCache;
	NSManagedObjectContext* _workerContext;
	CGSize _thumbnailSize;

}

@property (nonatomic,copy) NSString * noteIdentifier;                                                   //@synthesize noteIdentifier=_noteIdentifier - In the implementation block
@property (assign,nonatomic) char thumbnailFetched;                                                     //@synthesize thumbnailFetched=_thumbnailFetched - In the implementation block
@property (assign,nonatomic) CGSize thumbnailSize;                                                      //@synthesize thumbnailSize=_thumbnailSize - In the implementation block
@property (assign,nonatomic) float thumbnailScale;                                                      //@synthesize thumbnailScale=_thumbnailScale - In the implementation block
@property (nonatomic,retain) NSCache * thumbnailCache;                                                  //@synthesize thumbnailCache=_thumbnailCache - In the implementation block
@property (nonatomic,retain) NSCache * cellDataCache;                                                   //@synthesize cellDataCache=_cellDataCache - In the implementation block
@property (nonatomic,retain) NSManagedObjectContext * workerContext;                                    //@synthesize workerContext=_workerContext - In the implementation block
@property (assign,nonatomic,__weak) ICNotesListTableViewCellWithImageView * tableViewCell;              //@synthesize tableViewCell=_tableViewCell - In the implementation block
-(void)setNoteIdentifier:(NSString *)arg1 ;
-(NSString *)noteIdentifier;
-(char)thumbnailFetched;
-(id)initWithNoteIdentifier:(id)arg1 thumbnailSize:(CGSize)arg2 thumbnailScale:(float)arg3 thumbnailCache:(id)arg4 cellDataCache:(id)arg5 ;
-(void)setCellDataCache:(NSCache *)arg1 ;
-(NSCache *)cellDataCache;
-(void)setWorkerContext:(NSManagedObjectContext *)arg1 ;
-(NSManagedObjectContext *)workerContext;
-(void)setThumbnailFetched:(char)arg1 ;
-(void)setTableViewCell:(ICNotesListTableViewCellWithImageView *)arg1 ;
-(ICNotesListTableViewCellWithImageView *)tableViewCell;
-(void)main;
-(NSCache *)thumbnailCache;
-(void)setThumbnailCache:(NSCache *)arg1 ;
-(CGSize)thumbnailSize;
-(void)setThumbnailSize:(CGSize)arg1 ;
-(float)thumbnailScale;
-(void)setThumbnailScale:(float)arg1 ;
@end

