/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:25:01 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileNotes.app/MobileNotes
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileNotes/MobileNotes-Structs.h>
#import <UIKit/UIView.h>

@class UIActivityIndicatorView, UILabel, UIImageView, UIView, NSLayoutConstraint, UIButton;

@interface ICNotesListSummaryView : UIView {

	char _lockItemVisible;
	char _enabled;
	int _numberOfNotes;
	UIActivityIndicatorView* _activityIndicatorView;
	UILabel* _notesCountLabel;
	UIImageView* _lockIcon;
	UILabel* _lockLabel;
	UIView* _lockContainerView;
	NSLayoutConstraint* _lockContainerViewZeroHeightConstraint;
	NSLayoutConstraint* _lockContainerViewZeroWidthConstraint;
	UIButton* _button;
	/*^block*/id _buttonHandler;

}

@property (assign,nonatomic,__weak) UILabel * notesCountLabel;                                               //@synthesize notesCountLabel=_notesCountLabel - In the implementation block
@property (assign,nonatomic,__weak) UIImageView * lockIcon;                                                  //@synthesize lockIcon=_lockIcon - In the implementation block
@property (assign,nonatomic,__weak) UILabel * lockLabel;                                                     //@synthesize lockLabel=_lockLabel - In the implementation block
@property (assign,nonatomic,__weak) UIView * lockContainerView;                                              //@synthesize lockContainerView=_lockContainerView - In the implementation block
@property (assign,nonatomic,__weak) NSLayoutConstraint * lockContainerViewZeroHeightConstraint;              //@synthesize lockContainerViewZeroHeightConstraint=_lockContainerViewZeroHeightConstraint - In the implementation block
@property (assign,nonatomic,__weak) NSLayoutConstraint * lockContainerViewZeroWidthConstraint;               //@synthesize lockContainerViewZeroWidthConstraint=_lockContainerViewZeroWidthConstraint - In the implementation block
@property (assign,nonatomic,__weak) UIButton * button;                                                       //@synthesize button=_button - In the implementation block
@property (nonatomic,copy) id buttonHandler;                                                                 //@synthesize buttonHandler=_buttonHandler - In the implementation block
@property (assign,nonatomic) int numberOfNotes;                                                              //@synthesize numberOfNotes=_numberOfNotes - In the implementation block
@property (assign,nonatomic) char lockItemVisible;                                                           //@synthesize lockItemVisible=_lockItemVisible - In the implementation block
@property (assign,nonatomic) char enabled;                                                                   //@synthesize enabled=_enabled - In the implementation block
@property (assign,nonatomic,__weak) UIActivityIndicatorView * activityIndicatorView;                         //@synthesize activityIndicatorView=_activityIndicatorView - In the implementation block
+(id)summaryViewWithButtonPressedHandler:(/*^block*/id)arg1 ;
-(void)setLockItemVisible:(char)arg1 ;
-(void)setNumberOfNotes:(int)arg1 ;
-(void)updateforAccessibilityDarkerSystemColors;
-(UIImageView *)lockIcon;
-(void)setNotesNumberLabelToNumberOfNotes:(int)arg1 ;
-(UIView *)lockContainerView;
-(char)lockItemVisible;
-(UILabel *)notesCountLabel;
-(void)setLockItemVisible:(char)arg1 animated:(char)arg2 ;
-(void)setLockContainerVisible:(char)arg1 ;
-(NSLayoutConstraint *)lockContainerViewZeroHeightConstraint;
-(NSLayoutConstraint *)lockContainerViewZeroWidthConstraint;
-(void)buttonActionThatCausesAlphaChange:(id)arg1 ;
-(void)buttonActionThatEndsAlphaChange:(id)arg1 ;
-(void)buttonTouchUpInside:(id)arg1 ;
-(int)numberOfNotes;
-(void)setNotesCountLabel:(UILabel *)arg1 ;
-(void)setLockIcon:(UIImageView *)arg1 ;
-(void)setLockLabel:(UILabel *)arg1 ;
-(void)setLockContainerView:(UIView *)arg1 ;
-(void)setLockContainerViewZeroHeightConstraint:(NSLayoutConstraint *)arg1 ;
-(void)setLockContainerViewZeroWidthConstraint:(NSLayoutConstraint *)arg1 ;
-(char)enabled;
-(UIButton *)button;
-(void)dealloc;
-(void)setEnabled:(char)arg1 ;
-(void)awakeFromNib;
-(void)sizeToFit;
-(CGRect)accessibilityFrame;
-(char)shouldGroupAccessibilityChildren;
-(id)accessibilityElements;
-(void)setButton:(UIButton *)arg1 ;
-(UIActivityIndicatorView *)activityIndicatorView;
-(void)setActivityIndicatorView:(UIActivityIndicatorView *)arg1 ;
-(UILabel *)lockLabel;
-(id)_accessibilityContainingParentForOrdering;
-(char)_accessibilityOnlyComparesByXAxis;
-(id)buttonHandler;
-(void)setButtonHandler:(id)arg1 ;
@end

