/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:59 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileNotes.app/MobileNotes
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileNotes/ICNoteBaseActivityItemSource.h>
#import <UIKit/UIActivityItemSource.h>

@class NSAttributedString, NSString;

@interface ICNoteStringActivityItemSource : ICNoteBaseActivityItemSource <UIActivityItemSource> {

	/*^block*/id _attributedStringCreator;
	NSAttributedString* _attributedString;

}

@property (nonatomic,copy) id attributedStringCreator;                         //@synthesize attributedStringCreator=_attributedStringCreator - In the implementation block
@property (nonatomic,copy) NSAttributedString * attributedString;              //@synthesize attributedString=_attributedString - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setAttributedStringCreator:(id)arg1 ;
-(id)attributedStringCreator;
-(char)allowsAttributedStringForActivityType:(id)arg1 ;
-(id)initWithTitle:(id)arg1 attributedStringCreator:(/*^block*/id)arg2 ;
-(id)init;
-(void)setAttributedString:(NSAttributedString *)arg1 ;
-(NSAttributedString *)attributedString;
-(id)activityViewControllerPlaceholderItem:(id)arg1 ;
-(id)activityViewController:(id)arg1 itemForActivityType:(id)arg2 ;
@end

