/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:39:05 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileNotes.app/MobileNotes
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class UIWindow;

@interface ICOverlayWindowPresenter : NSObject {

	unsigned _presentAnimationType;
	UIWindow* _window;
	UIWindow* _presentingWindow;

}

@property (nonatomic,retain) UIWindow * window;                          //@synthesize window=_window - In the implementation block
@property (nonatomic,retain) UIWindow * presentingWindow;                //@synthesize presentingWindow=_presentingWindow - In the implementation block
@property (assign,nonatomic) unsigned presentAnimationType;              //@synthesize presentAnimationType=_presentAnimationType - In the implementation block
-(void)dismissWithCompletionBlock:(/*^block*/id)arg1 ;
-(id)initWithRootViewController:(id)arg1 presentingWindow:(id)arg2 ;
-(void)setPresentAnimationType:(unsigned)arg1 ;
-(void)presentWithCompletionBlock:(/*^block*/id)arg1 ;
-(void)setPresentingWindow:(UIWindow *)arg1 ;
-(UIWindow *)presentingWindow;
-(unsigned)presentAnimationType;
-(void)animateWindowFrameReverse:(char)arg1 duration:(double)arg2 completionBlock:(/*^block*/id)arg3 ;
-(UIWindow *)window;
-(void)setWindow:(UIWindow *)arg1 ;
@end

