/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:25:02 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileNotes.app/MobileNotes
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NotesCIDDataProvider <NSObject>
@required
-(char)getData:(id*)arg1 mimeType:(id*)arg2 error:(id*)arg3;

@end

