/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:39:07 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileNotes.app/MobileNotes
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NoteTextViewActionDelegate
@required
-(char)canInsertImagesInTextView:(id)arg1;
-(void)insertImageInTextView:(id)arg1;
-(char)noteTextView:(id)arg1 acceptContentsFromPasteboard:(id)arg2;
-(char)allowsAttachmentsInTextView:(id)arg1;
-(void)noteTextView:(id)arg1 handleLongPressOnElement:(id)arg2 atPoint:(CGPoint)arg3;
-(char)noteTextView:(id)arg1 canHandleLongPressOnElement:(id)arg2;

@end

