/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:25:43 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/VoiceMemos.app/VoiceMemos
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIApplication.h>

@class RCUndoTrackedUIAlertView;

@interface RecorderApp : UIApplication {

	char _willShowUndoAlertView;
	/*^block*/id _alertDidCancelBlock;
	RCUndoTrackedUIAlertView* _undoAlertView;

}

@property (nonatomic,copy) id alertDidCancelBlock;                                  //@synthesize alertDidCancelBlock=_alertDidCancelBlock - In the implementation block
@property (assign,nonatomic) char willShowUndoAlertView;                            //@synthesize willShowUndoAlertView=_willShowUndoAlertView - In the implementation block
@property (nonatomic,retain) RCUndoTrackedUIAlertView * undoAlertView;              //@synthesize undoAlertView=_undoAlertView - In the implementation block
-(void)_didDismissAlertView:(id)arg1 withButtonIndex:(unsigned)arg2 ;
-(id)alertDidCancelBlock;
-(void)setAlertDidCancelBlock:(id)arg1 ;
-(char)willShowUndoAlertView;
-(void)setWillShowUndoAlertView:(char)arg1 ;
-(RCUndoTrackedUIAlertView *)undoAlertView;
-(void)setUndoAlertView:(RCUndoTrackedUIAlertView *)arg1 ;
-(void)applicationWillSuspend;
-(char)applicationSuspendWithSettings:(id)arg1 ;
-(void)_showEditAlertViewWithUndoManager:(id)arg1 window:(id)arg2 ;
-(void)applicationDidResume;
-(void)alertViewCancel:(id)arg1 ;
-(void)willPresentAlertView:(id)arg1 ;
-(void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2 ;
-(void)_writeApplicationDefaultPNGSnapshot;
@end

