/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:28 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/InCallService.app/InCallService
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <InCallService/PHCallParticipantsViewDelegate.h>

@class PHContactsClient, PHCallParticipantsView, NSMutableArray, NSString;

@interface PHCallParticipantsViewController : UIViewController <PHCallParticipantsViewDelegate> {

	char _handlesCallWaitingCalls;
	char _allowsFieldModeSendButton;
	char _shouldCompressLabelsVertically;
	char _shouldIgnoreUpdates;
	char _shouldInsertSpaceBeforeNextOverrideStringCharacter;
	PHContactsClient* _contactsClient;
	PHCallParticipantsView* _participantsView;
	NSMutableArray* _callGroups;
	NSString* _nameOverrideString;

}

@property (nonatomic,retain) PHContactsClient * contactsClient;                          //@synthesize contactsClient=_contactsClient - In the implementation block
@property (retain) PHCallParticipantsView * participantsView;                            //@synthesize participantsView=_participantsView - In the implementation block
@property (nonatomic,retain) NSMutableArray * callGroups;                                //@synthesize callGroups=_callGroups - In the implementation block
@property (retain) NSString * nameOverrideString;                                        //@synthesize nameOverrideString=_nameOverrideString - In the implementation block
@property (assign) char shouldInsertSpaceBeforeNextOverrideStringCharacter;              //@synthesize shouldInsertSpaceBeforeNextOverrideStringCharacter=_shouldInsertSpaceBeforeNextOverrideStringCharacter - In the implementation block
@property (assign) char handlesCallWaitingCalls;                                         //@synthesize handlesCallWaitingCalls=_handlesCallWaitingCalls - In the implementation block
@property (assign,nonatomic) char allowsFieldModeSendButton;                             //@synthesize allowsFieldModeSendButton=_allowsFieldModeSendButton - In the implementation block
@property (assign,nonatomic) char shouldCompressLabelsVertically;                        //@synthesize shouldCompressLabelsVertically=_shouldCompressLabelsVertically - In the implementation block
@property (assign,nonatomic) char shouldIgnoreUpdates;                                   //@synthesize shouldIgnoreUpdates=_shouldIgnoreUpdates - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(char)isDeviceCapableOfTelephonyCalls;
-(PHContactsClient *)contactsClient;
-(void)setShouldIgnoreUpdates:(char)arg1 ;
-(char)shouldIgnoreUpdates;
-(char)shouldCompressLabelsVertically;
-(void)setShouldCompressLabelsVertically:(char)arg1 ;
-(void)setContactsClient:(PHContactsClient *)arg1 ;
-(void)callStatusChangedNotification:(id)arg1 ;
-(unsigned)numberOfParticipantsForParticipantsView:(id)arg1 ;
-(id)overrideStringForParticipantsView:(id)arg1 ;
-(id)colorForStatusLabelForParticipantAtIndex:(unsigned)arg1 inParticipantsView:(id)arg2 ;
-(id)fontForParticipantLabelForParticipantAtIndex:(unsigned)arg1 inParticipantsView:(id)arg2 ;
-(char)shouldShowSingleDurationLabelInParticipantsView:(id)arg1 ;
-(id)nameForParticipantAtIndex:(unsigned)arg1 inParticipantsView:(id)arg2 ;
-(id)labelForParticipantAtIndex:(unsigned)arg1 inParticipantsView:(id)arg2 ;
-(id)supplementalParticipantLabelFormatStringAtIndex:(unsigned)arg1 inParticipantsView:(id)arg2 ;
-(id)contactForParticipantAtIndex:(unsigned)arg1 inParticipantsView:(id)arg2 ;
-(unsigned short)activityStateForParticipantAtIndex:(unsigned)arg1 inParticipantsView:(id)arg2 ;
-(char)shouldShowInfoButtonForParticipantAtIndex:(unsigned)arg1 inParticipantsView:(id)arg2 ;
-(void)participantTappedAtIndex:(unsigned)arg1 inParticipantsView:(id)arg2 ;
-(void)participantViewInfoButtonTappedAtIndex:(unsigned)arg1 inParticipantsView:(id)arg2 ;
-(id)compactLabelTextForParticipantAtIndex:(unsigned)arg1 inParticipantsView:(id)arg2 ;
-(void)fieldModeSendButtonTappedInParticipantsView:(id)arg1 ;
-(char)shouldIgnoreUpdatesInParticipantsView:(id)arg1 ;
-(void)setAllowsFieldModeSendButton:(char)arg1 ;
-(char)shouldShowSingleDurationLabel;
-(char)allowsFieldModeSendButton;
-(void)conferenceParticipantsChangedNotification:(id)arg1 ;
-(void)isThirdPartyVideoChangedNotification:(id)arg1 ;
-(void)callModelChangedNotification:(id)arg1 ;
-(void)displayContextChangedNotification:(id)arg1 ;
-(void)keypadDataSourceChangedNotification:(id)arg1 ;
-(void)callContinuityChangedNotification:(id)arg1 ;
-(void)secondTickNotification:(id)arg1 ;
-(void)_updateCallGroups;
-(PHCallParticipantsView *)participantsView;
-(NSMutableArray *)callGroups;
-(void)setParticipantsView:(PHCallParticipantsView *)arg1 ;
-(char)handlesCallWaitingCalls;
-(void)setCallGroups:(NSMutableArray *)arg1 ;
-(char)anyLabelDescriptorIsDynamic;
-(NSString *)nameOverrideString;
-(void)setNameOverrideString:(NSString *)arg1 ;
-(char)shouldInsertSpaceBeforeNextOverrideStringCharacter;
-(void)setShouldInsertSpaceBeforeNextOverrideStringCharacter:(char)arg1 ;
-(void)setShouldInsertSpaceBeforeNextOverrideStringCharacter;
-(char)shouldShowParticipantImageAtIndex:(unsigned)arg1 inParticipantsView:(id)arg2 ;
-(unsigned)numberOfParticipantLabels;
-(id)callForParticipantAtIndex:(unsigned)arg1 inParticipantsView:(id)arg2 ;
-(void)resetNameOverrideString;
-(void)setHandlesCallWaitingCalls:(char)arg1 ;
-(void)dealloc;
-(void)didReceiveMemoryWarning;
-(void)loadView;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidDisappear:(char)arg1 ;
@end

