/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:25:39 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Tips.app/Tips
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Tips/Tips-Structs.h>
#import <UIKit/UICollectionViewFlowLayout.h>

@class NSIndexPath;

@interface TPSCollectionViewFlowLayout : UICollectionViewFlowLayout {

	float _width;
	NSIndexPath* _preRotationIndexPath;

}
-(id)invalidationContextForBoundsChange:(CGRect)arg1 ;
-(char)shouldInvalidateLayoutForBoundsChange:(CGRect)arg1 ;
-(CGPoint)targetContentOffsetForProposedContentOffset:(CGPoint)arg1 ;
@end

