/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:39:43 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Tips.app/Tips
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Tips/Tips-Structs.h>
#import <Tips/TPSAppearance.h>

@interface TPSIntroAppearance : TPSAppearance {

	char _sideBySideUI;
	float _bodyTextLabelFirstBaseline;
	float _startLearningButtonFirstBaseline;
	float _startLearningButtonLastBaseline;
	float _assetAreaOffset;
	float _imageAreaLeftMargin;
	float _assetAreaWidth;
	float _contentSidePadding;
	CGSize _imageSize;

}

@property (assign,nonatomic) float bodyTextLabelFirstBaseline;                     //@synthesize bodyTextLabelFirstBaseline=_bodyTextLabelFirstBaseline - In the implementation block
@property (assign,nonatomic) float startLearningButtonFirstBaseline;               //@synthesize startLearningButtonFirstBaseline=_startLearningButtonFirstBaseline - In the implementation block
@property (assign,nonatomic) float startLearningButtonLastBaseline;                //@synthesize startLearningButtonLastBaseline=_startLearningButtonLastBaseline - In the implementation block
@property (assign,nonatomic) float assetAreaOffset;                                //@synthesize assetAreaOffset=_assetAreaOffset - In the implementation block
@property (assign,nonatomic) float imageAreaLeftMargin;                            //@synthesize imageAreaLeftMargin=_imageAreaLeftMargin - In the implementation block
@property (assign,nonatomic) float assetAreaWidth;                                 //@synthesize assetAreaWidth=_assetAreaWidth - In the implementation block
@property (assign,getter=isSideBySideUI,nonatomic) char sideBySideUI;              //@synthesize sideBySideUI=_sideBySideUI - In the implementation block
@property (assign,nonatomic) float contentSidePadding;                             //@synthesize contentSidePadding=_contentSidePadding - In the implementation block
@property (assign,nonatomic) CGSize imageSize;                                     //@synthesize imageSize=_imageSize - In the implementation block
-(void)setStartLearningButtonLastBaseline:(float)arg1 ;
-(void)setSideBySideUI:(char)arg1 ;
-(void)setAssetAreaWidth:(float)arg1 ;
-(void)setContentSidePadding:(float)arg1 ;
-(void)setStartLearningButtonFirstBaseline:(float)arg1 ;
-(void)setBodyTextLabelFirstBaseline:(float)arg1 ;
-(void)setAssetAreaOffset:(float)arg1 ;
-(void)setImageAreaLeftMargin:(float)arg1 ;
-(float)assetAreaWidth;
-(float)startLearningButtonLastBaseline;
-(char)isSideBySideUI;
-(float)bodyTextLabelFirstBaseline;
-(float)startLearningButtonFirstBaseline;
-(float)contentSidePadding;
-(float)imageAreaLeftMargin;
-(float)assetAreaOffset;
-(void)updateMediaSizeType;
-(void)updateAppearanceWithSize:(CGSize)arg1 ;
-(char)isEqual:(id)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(CGSize)imageSize;
-(void)setImageSize:(CGSize)arg1 ;
@end

