/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:25:31 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Setup.app/Setup
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDate, NSMutableDictionary, NSString;

@interface BFFAnalyticsManager : NSObject {

	NSDate* _timingStartDate;
	int _timingStartIdentifier;
	NSMutableDictionary* _skippedPanes;
	id _callstack;
	NSString* _activationADKey;
	NSString* _appleIDADKey;

}

@property (nonatomic,retain) NSString * activationADKey;              //@synthesize activationADKey=_activationADKey - In the implementation block
@property (nonatomic,retain) NSString * appleIDADKey;                 //@synthesize appleIDADKey=_appleIDADKey - In the implementation block
+(id)sharedManager;
-(void)logNumberOfBuddySections:(unsigned)arg1 forRunType:(int)arg2 ;
-(void)commitAnalyticsForRunType:(int)arg1 ;
-(void)startUserPerceivedTimingWithStartIdentifier:(int)arg1 ;
-(void)finishTimingIfNeededWithEndIdentifier:(id)arg1 ;
-(void)setActivationADKey:(NSString *)arg1 ;
-(void)logSkipChoice:(char)arg1 forPane:(int)arg2 ;
-(void)setAppleIDADKey:(NSString *)arg1 ;
-(void)cancelTiming;
-(void)_finishTimingWithEndIdentifier:(id)arg1 hardFailure:(char)arg2 ;
-(id)_stringForKeyboardList:(id)arg1 ;
-(void)finishTimingWithEndIdentifier:(id)arg1 ;
-(void)logKeyboardChoices:(id)arg1 againstGuessedKeyboards:(id)arg2 forLocaleidentifier:(id)arg3 ;
-(void)clearSkipChoice:(char)arg1 forPane:(int)arg2 ;
-(NSString *)activationADKey;
-(NSString *)appleIDADKey;
-(id)init;
@end

