/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:25:30 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Setup.app/Setup
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol BuddyLanguageChangeObserverDelegate <NSObject>
@required
-(void)observer:(id)arg1 didObserveLanguageChange:(char)arg2 localeChange:(char)arg3;

@end

