/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:39:36 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Setup.app/Setup
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Setup/BuddyTableViewController.h>
#import <Setup/BuddyController.h>

@protocol BuddyControllerDelegate;
@class NSArray, NSMutableIndexSet, NSIndexSet, NSString;

@interface BuddyKeyboardPickerController : BuddyTableViewController <BuddyController> {

	NSArray* _previousSelectedInputModes;
	id<BuddyControllerDelegate> _delegate;
	NSArray* _inputModes;
	NSMutableIndexSet* _selectedRowIndexes;
	NSIndexSet* _suggestedRowIndexes;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(char)controllerNeedsToRun;
-(void)controllerWasPopped;
-(void)startOver;
-(void)_restoreSavedInputModes;
-(id)init;
-(void)setDelegate:(id)arg1 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(id)tableView:(id)arg1 titleForFooterInSection:(int)arg2 ;
-(void)done;
-(id)titleText;
@end

