/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:29 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Magnifier.app/Magnifier
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Magnifier/Magnifier-Structs.h>
#import <UIKit/UIView.h>

@protocol MAGLiveMagnifierViewDelegate;
@class AVCaptureVideoPreviewLayer, UIView, MAGManualFocusIndicatorView, AXDispatchTimer, UIImageView, CABackdropLayer, MAGCurrentFilterSetChangeSubscription, MAGFilterSetChangeSubscription;

@interface MAGLiveMagnifierView : UIView {

	char _sizeTransitionInProgress;
	AVCaptureVideoPreviewLayer* _previewLayer;
	id<MAGLiveMagnifierViewDelegate> _delegate;
	float _lastMagnificationFactor;
	UIView* _previewContainer;
	MAGManualFocusIndicatorView* _manualFocusIndicator;
	AXDispatchTimer* _focusIndicatorFadeTimer;
	UIView* _blackoutView;
	UIImageView* _frozenView;
	CABackdropLayer* _filterLayer;
	MAGCurrentFilterSetChangeSubscription* _filterChangeSubscription;
	MAGFilterSetChangeSubscription* _filterSetChangeSubscription;

}

@property (assign,nonatomic) float lastMagnificationFactor;                                                 //@synthesize lastMagnificationFactor=_lastMagnificationFactor - In the implementation block
@property (nonatomic,retain) UIView * previewContainer;                                                     //@synthesize previewContainer=_previewContainer - In the implementation block
@property (nonatomic,retain) AVCaptureVideoPreviewLayer * previewLayer;                                     //@synthesize previewLayer=_previewLayer - In the implementation block
@property (nonatomic,retain) MAGManualFocusIndicatorView * manualFocusIndicator;                            //@synthesize manualFocusIndicator=_manualFocusIndicator - In the implementation block
@property (nonatomic,retain) AXDispatchTimer * focusIndicatorFadeTimer;                                     //@synthesize focusIndicatorFadeTimer=_focusIndicatorFadeTimer - In the implementation block
@property (nonatomic,retain) UIView * blackoutView;                                                         //@synthesize blackoutView=_blackoutView - In the implementation block
@property (nonatomic,retain) UIImageView * frozenView;                                                      //@synthesize frozenView=_frozenView - In the implementation block
@property (nonatomic,retain) CABackdropLayer * filterLayer;                                                 //@synthesize filterLayer=_filterLayer - In the implementation block
@property (nonatomic,retain) MAGCurrentFilterSetChangeSubscription * filterChangeSubscription;              //@synthesize filterChangeSubscription=_filterChangeSubscription - In the implementation block
@property (nonatomic,retain) MAGFilterSetChangeSubscription * filterSetChangeSubscription;                  //@synthesize filterSetChangeSubscription=_filterSetChangeSubscription - In the implementation block
@property (assign,nonatomic) char sizeTransitionInProgress;                                                 //@synthesize sizeTransitionInProgress=_sizeTransitionInProgress - In the implementation block
@property (assign,nonatomic,__weak) id<MAGLiveMagnifierViewDelegate> delegate;                              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) char blackedOut; 
-(void)setBlackoutView:(UIView *)arg1 ;
-(UIView *)blackoutView;
-(void)setFilterChangeSubscription:(MAGCurrentFilterSetChangeSubscription *)arg1 ;
-(void)setFilterSetChangeSubscription:(MAGFilterSetChangeSubscription *)arg1 ;
-(void)setBlackedOut:(char)arg1 ;
-(char)blackedOut;
-(MAGCurrentFilterSetChangeSubscription *)filterChangeSubscription;
-(MAGFilterSetChangeSubscription *)filterSetChangeSubscription;
-(void)sizeTransitionWillBeginToSize:(CGSize)arg1 ;
-(void)sizeTransitionDidEnd;
-(void)setFilterLayer:(CABackdropLayer *)arg1 ;
-(CABackdropLayer *)filterLayer;
-(void)setPreviewContainer:(UIView *)arg1 ;
-(UIView *)previewContainer;
-(void)setManualFocusIndicator:(MAGManualFocusIndicatorView *)arg1 ;
-(MAGManualFocusIndicatorView *)manualFocusIndicator;
-(void)setFocusIndicatorFadeTimer:(AXDispatchTimer *)arg1 ;
-(AXDispatchTimer *)focusIndicatorFadeTimer;
-(void)setFrozenView:(UIImageView *)arg1 ;
-(UIImageView *)frozenView;
-(void)compensateForInterfaceOrientationInLiveMagnifier:(int)arg1 referenceSize:(CGSize)arg2 ;
-(void)setLastMagnificationFactor:(float)arg1 ;
-(float)lastMagnificationFactor;
-(id)initWithPreviewLayer:(id)arg1 ;
-(void)magnificationFactorChangedTo:(float)arg1 ;
-(CGPoint)convertPointToCaptureDeviceLocation:(CGPoint)arg1 ;
-(void)showFocusIndicatorOfType:(unsigned)arg1 atPoint:(CGPoint)arg2 ;
-(void)setFrozenImage:(id)arg1 ;
-(void)layoutSubviews;
-(void)setDelegate:(id<MAGLiveMagnifierViewDelegate>)arg1 ;
-(id<MAGLiveMagnifierViewDelegate>)delegate;
-(id)accessibilityLabel;
-(id)accessibilityValue;
-(id)accessibilityHint;
-(CGPoint)accessibilityActivationPoint;
-(unsigned long long)accessibilityTraits;
-(char)isAccessibilityElement;
-(void)accessibilityIncrement;
-(void)accessibilityDecrement;
-(void)setPreviewLayer:(AVCaptureVideoPreviewLayer *)arg1 ;
-(char)sizeTransitionInProgress;
-(void)setSizeTransitionInProgress:(char)arg1 ;
-(AVCaptureVideoPreviewLayer *)previewLayer;
@end

