#import <Magnifier/MAGFilterSelectionReducedMotionShowAnimator.h>
#import <Magnifier/MAGSecureWindow.h>
#import <Magnifier/MAGAppDelegate.h>
#import <Magnifier/MAGSnapshotView.h>
#import <Magnifier/MAGSettingsCache.h>
#import <Magnifier/MAGSnapshotButton.h>
#import <Magnifier/MAGManualFocusIndicatorView.h>
#import <Magnifier/MAGFilterSelectionPreviewView.h>
#import <Magnifier/MAGFilterSelectionStandardShowAnimator.h>
#import <Magnifier/MAGSpecSlider.h>
#import <Magnifier/MAGFilterBackdropLayer.h>
#import <Magnifier/MAGStandardFilterSelectionPreviewView.h>
#import <Magnifier/MAGFilterSelectionControlPanel.h>
#import <Magnifier/MAGFilterSelectionReducedMotionHideAnimator.h>
#import <Magnifier/MAGFocusIndicatorView.h>
#import <Magnifier/MAGFilterSelectionZoomTransitioningDelegate.h>
#import <Magnifier/MAGCurrentFilterSetChangeSubscription.h>
#import <Magnifier/MAGFilterSetChangeSubscription.h>
#import <Magnifier/MAGFilterManager.h>
#import <Magnifier/MAGSnapshotCanvasAccessibilityElement.h>
#import <Magnifier/MAGControlPanel.h>
#import <Magnifier/MAGFilterSelectionViewController.h>
#import <Magnifier/MAGReducedMotionFilterSelectionPreviewView.h>
#import <Magnifier/MAGManualFocusIndicatorReticleView.h>
#import <Magnifier/MAGFilterSelectionStandardHideAnimator.h>
#import <Magnifier/MAGNamedFilterSet.h>
#import <Magnifier/MAGAutoBrightnessManager.h>
#import <Magnifier/MAGMagnificationFactorLabel.h>
#import <Magnifier/MAGFilterLabelDial.h>
#import <Magnifier/MAGLiveMagnifierView.h>
#import <Magnifier/MAGSimplePhotoCaptureDelegate.h>
#import <Magnifier/MAGRootViewController.h>
