/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:25:36 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Stocks.app/Stocks
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@class NSArray, UIViewController;

@interface StocksPreviewingWrapperViewController : UIViewController {

	NSArray* _stocksPreviewActionItems;
	UIViewController* _wrappedViewController;

}

@property (nonatomic,retain) NSArray * stocksPreviewActionItems;                    //@synthesize stocksPreviewActionItems=_stocksPreviewActionItems - In the implementation block
@property (nonatomic,retain) UIViewController * wrappedViewController;              //@synthesize wrappedViewController=_wrappedViewController - In the implementation block
-(UIViewController *)wrappedViewController;
-(void)setWrappedViewController:(UIViewController *)arg1 ;
-(NSArray *)stocksPreviewActionItems;
-(id)initWithWrappedViewController:(id)arg1 ;
-(void)setStocksPreviewActionItems:(NSArray *)arg1 ;
-(void)viewDidLoad;
-(id)previewActionItems;
@end

