/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:39:41 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Stocks.app/Stocks
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol StocksStatusViewDelegate <NSObject>
@required
-(int)statusViewCurrentPageForPageIndicator:(id)arg1;
-(void)statusView:(id)arg1 updatePageControlForDirection:(int)arg2;

@end

