/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:08 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/DemoApp.app/DemoApp
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class AVPlayer;

@interface DemoPlayerView : UIView

@property (nonatomic,retain) AVPlayer * player; 
+(Class)layerClass;
-(AVPlayer *)player;
-(void)setPlayer:(AVPlayer *)arg1 ;
@end

