/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:11 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/DiagnosticsService.app/PlugIns/Diagnostic-4446.appex/Diagnostic-4446
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Diagnostic-4446/Diagnostic-4446-Structs.h>
#import <UIKit/UIView.h>

@class UILabel, UIActivityIndicatorView;

@interface WiFiHeaderView : UIView {

	UILabel* _headerText;
	UIActivityIndicatorView* _spinner;

}

@property (nonatomic,retain) UILabel * headerText;                           //@synthesize headerText=_headerText - In the implementation block
@property (nonatomic,retain) UIActivityIndicatorView * spinner;              //@synthesize spinner=_spinner - In the implementation block
-(id)initWithFrame:(CGRect)arg1 text:(id)arg2 showSpinner:(char)arg3 ;
-(void)layoutSubviews;
-(UILabel *)headerText;
-(void)setHeaderText:(UILabel *)arg1 ;
-(UIActivityIndicatorView *)spinner;
-(void)setSpinner:(UIActivityIndicatorView *)arg1 ;
@end

