/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:22 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/FindMyiPhone.app/FindMyiPhone
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreCDPUI/CDPUIBaseController.h>
#import <FindMyiPhone/FMIPCommandProcessingProtocol.h>

@class FMIPCommandContext, NSString;

@interface FMIPCDPUIController : CDPUIBaseController <FMIPCommandProcessingProtocol> {

	FMIPCommandContext* commandContext;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,retain) FMIPCommandContext * commandContext; 
-(FMIPCommandContext *)commandContext;
-(void)setCommandContext:(FMIPCommandContext *)arg1 ;
-(void)cdpContext:(id)arg1 promptForRemoteSecretWithDevices:(id)arg2 offeringRemoteApproval:(char)arg3 validator:(id)arg4 ;
@end

