/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:00 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Feedback Assistant iOS.app/Feedback Assistant iOS
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class UILabel;

@interface FBAOSLogTableViewCell : UITableViewCell {

	UILabel* _logLabel;

}

@property (assign,nonatomic,__weak) UILabel * logLabel;              //@synthesize logLabel=_logLabel - In the implementation block
-(UILabel *)logLabel;
-(void)setLogLabel:(UILabel *)arg1 ;
-(void)awakeFromNib;
-(void)setSelected:(char)arg1 animated:(char)arg2 ;
@end

