/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:00 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Feedback Assistant iOS.app/Feedback Assistant iOS
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <libobjc.A.dylib/WKNavigationDelegate.h>

@class FBABugForm, UIView, UIButton, UIScrollView, FBAAdaptiveWebView, NSLayoutConstraint, NSString;

@interface iFBASurveyDetailViewController : UIViewController <WKNavigationDelegate> {

	char _isLoading;
	char _isObserving;
	FBABugForm* _surveyBugForm;
	UIView* _actionView;
	UIButton* _actionButton;
	UIScrollView* _scrollView;
	FBAAdaptiveWebView* _webView;
	NSLayoutConstraint* _webViewHeightConstraint;

}

@property (nonatomic,retain) UIView * actionView;                                       //@synthesize actionView=_actionView - In the implementation block
@property (assign,nonatomic,__weak) UIButton * actionButton;                            //@synthesize actionButton=_actionButton - In the implementation block
@property (assign,nonatomic,__weak) UIScrollView * scrollView;                          //@synthesize scrollView=_scrollView - In the implementation block
@property (nonatomic,retain) FBAAdaptiveWebView * webView;                              //@synthesize webView=_webView - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * webViewHeightConstraint;              //@synthesize webViewHeightConstraint=_webViewHeightConstraint - In the implementation block
@property (assign,nonatomic) char isLoading;                                            //@synthesize isLoading=_isLoading - In the implementation block
@property (assign,nonatomic) char isObserving;                                          //@synthesize isObserving=_isObserving - In the implementation block
@property (nonatomic,retain) FBABugForm * surveyBugForm;                                //@synthesize surveyBugForm=_surveyBugForm - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)updateScrollView;
-(void)updateActionView;
-(void)updateWebViewFittingSize;
-(void)updateWebView;
-(void)updateNavigation;
-(FBABugForm *)surveyBugForm;
-(void)updateWebViewHeight:(float)arg1 ;
-(NSLayoutConstraint *)webViewHeightConstraint;
-(void)setWebViewHeightConstraint:(NSLayoutConstraint *)arg1 ;
-(void)setSurveyBugForm:(FBABugForm *)arg1 ;
-(void)didPressTakeSurveyButton:(id)arg1 ;
-(void)setActionView:(UIView *)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)dealloc;
-(UIScrollView *)scrollView;
-(void)setScrollView:(UIScrollView *)arg1 ;
-(void)viewDidLoad;
-(FBAAdaptiveWebView *)webView;
-(void)setWebView:(FBAAdaptiveWebView *)arg1 ;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(char)isLoading;
-(void)setIsLoading:(char)arg1 ;
-(char)isObserving;
-(void)setActionButton:(UIButton *)arg1 ;
-(UIButton *)actionButton;
-(void)setIsObserving:(char)arg1 ;
-(void)webView:(id)arg1 didFinishNavigation:(id)arg2 ;
-(UIView *)actionView;
@end

