/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:39:37 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/SharingViewService.app/SharingViewService
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>
#import <UIKit/UIKeyInput.h>
#import <UIKit/UITextInputTraits.h>

@class NSString, NSMutableString, NSArray;

@interface PINEntryView : UIView <UIKeyInput, UITextInputTraits> {

	NSMutableString* _text;
	NSArray* _digits;
	/*^block*/id _textChangedHandler;

}

@property (nonatomic,retain) NSArray * digits;                                           //@synthesize digits=_digits - In the implementation block
@property (nonatomic,copy) NSString * text; 
@property (nonatomic,copy) id textChangedHandler;                                        //@synthesize textChangedHandler=_textChangedHandler - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) int autocapitalizationType; 
@property (assign,nonatomic) int autocorrectionType; 
@property (assign,nonatomic) int spellCheckingType; 
@property (assign,nonatomic) int keyboardType; 
@property (assign,nonatomic) int keyboardAppearance; 
@property (assign,nonatomic) int returnKeyType; 
@property (assign,nonatomic) char enablesReturnKeyAutomatically; 
@property (assign,getter=isSecureTextEntry,nonatomic) char secureTextEntry; 
@property (nonatomic,copy) NSString * textContentType; 
@property (nonatomic,readonly) char hasText; 
-(id)textChangedHandler;
-(void)setTextChangedHandler:(id)arg1 ;
-(NSString *)text;
-(void)setText:(NSString *)arg1 ;
-(char)canBecomeFirstResponder;
-(void)insertText:(id)arg1 ;
-(void)deleteBackward;
-(char)hasText;
-(int)keyboardType;
-(void)setDigits:(NSArray *)arg1 ;
-(void)_updateLabels;
-(NSArray *)digits;
@end

