/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:25:32 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/SharingViewService.app/SharingViewService
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <UIKit/UIViewControllerTransitioningDelegate.h>

@class UIView, UIButton, UIImageView, UILabel, PINPairViewControllerProxy, NSDictionary, NSString;

@interface PINPairDoneViewController : UIViewController <UIViewControllerTransitioningDelegate> {

	UIView* _containerView;
	UIButton* _doneButton;
	UIImageView* _imageView;
	UILabel* _infoLabel;
	UILabel* _titleLabel;
	PINPairViewControllerProxy* _proxyViewController;
	long _status;
	NSDictionary* _userInfo;

}

@property (nonatomic,retain) PINPairViewControllerProxy * proxyViewController;              //@synthesize proxyViewController=_proxyViewController - In the implementation block
@property (assign,nonatomic) long status;                                                   //@synthesize status=_status - In the implementation block
@property (nonatomic,copy) NSDictionary * userInfo;                                         //@synthesize userInfo=_userInfo - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setProxyViewController:(PINPairViewControllerProxy *)arg1 ;
-(PINPairViewControllerProxy *)proxyViewController;
-(void)handleDismissButton:(id)arg1 ;
-(NSDictionary *)userInfo;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidDisappear:(char)arg1 ;
-(void)setUserInfo:(NSDictionary *)arg1 ;
-(long)status;
-(void)setStatus:(long)arg1 ;
@end

