/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:39:37 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/SharingViewService.app/SharingViewService
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <UIKit/UIViewControllerTransitioningDelegate.h>

@class UIView, UILabel, PINEntryView, PINPairViewControllerProxy, NSDictionary, NSString;

@interface PINPairEntryViewController : UIViewController <UIViewControllerTransitioningDelegate> {

	UIView* _containerView;
	UILabel* _infoLabel;
	PINEntryView* _pinEntryView;
	UILabel* _pinLabel1;
	UILabel* _pinLabel2;
	UILabel* _pinLabel3;
	UILabel* _pinLabel4;
	PINPairViewControllerProxy* _proxyViewController;
	NSDictionary* _userInfo;

}

@property (nonatomic,retain) PINPairViewControllerProxy * proxyViewController;              //@synthesize proxyViewController=_proxyViewController - In the implementation block
@property (nonatomic,copy) NSDictionary * userInfo;                                         //@synthesize userInfo=_userInfo - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setProxyViewController:(PINPairViewControllerProxy *)arg1 ;
-(PINPairViewControllerProxy *)proxyViewController;
-(void)handleDismissButton:(id)arg1 ;
-(void)showPINEntryUIWithFlags:(unsigned)arg1 throttleSeconds:(int)arg2 ;
-(NSDictionary *)userInfo;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidDisappear:(char)arg1 ;
-(void)setUserInfo:(NSDictionary *)arg1 ;
@end

