/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:55 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MFMailboxPrediction.h>

@class MFFuture, NSString;

@interface _MFAsyncMailboxPrediction : NSObject <MFMailboxPrediction> {

	char _didWait;
	MFFuture* _future;
	unsigned _context;
	double _startedAt;
	double _finishedAt;

}

@property (nonatomic,retain) MFFuture * future;                     //@synthesize future=_future - In the implementation block
@property (assign,nonatomic) unsigned context;                      //@synthesize context=_context - In the implementation block
@property (assign,nonatomic) char didWait;                          //@synthesize didWait=_didWait - In the implementation block
@property (assign,nonatomic) double startedAt;                      //@synthesize startedAt=_startedAt - In the implementation block
@property (assign,nonatomic) double finishedAt;                     //@synthesize finishedAt=_finishedAt - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)mailboxPredictionFromFuture:(id)arg1 context:(unsigned)arg2 startedAt:(double)arg3 ;
-(void)setFinishedAt:(double)arg1 ;
-(double)finishedAt;
-(id)copyForContext:(unsigned)arg1 ;
-(void)setStartedAt:(double)arg1 ;
-(id)_waitOnceForFutureResult;
-(double)startedAt;
-(void)setDidWait:(char)arg1 ;
-(void)_reportTimingForSuccess:(char)arg1 processing:(double)arg2 waiting:(double)arg3 ;
-(char)didWait;
-(void)dealloc;
-(unsigned)context;
-(void)setContext:(unsigned)arg1 ;
-(MFFuture *)future;
-(id)mailboxes;
-(id)diagnostics;
-(void)setFuture:(MFFuture *)arg1 ;
@end

