/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:54 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MFAtomTextView.h>

@class _MFSearchAtomFieldEditor, MFAtomSearchBar;

@interface _MFSearchAtomTextView : MFAtomTextView

@property (getter=_fieldEditor,nonatomic,retain,readonly) _MFSearchAtomFieldEditor * fieldEditor; 
@property (getter=_searchBar,nonatomic,retain,readonly) MFAtomSearchBar * searchBar; 
+(Class)_fieldEditorClass;
-(id)_searchBar;
-(char)shouldCenterPlaceholder;
-(void)setText:(id)arg1 ;
-(id)_fieldEditor;
-(id)textInputTraits;
-(id)searchText;
-(void)_setEnabled:(char)arg1 animated:(char)arg2 ;
-(id)placeholderColor;
@end

