/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:57 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <MobileMail/MFSwipeActionButton.h>

@interface MFCircularSwipeActionButton : MFSwipeActionButton
+(float)maximumButtonHeight;
+(float)buttonWidth;
+(id)titleFont;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)setTitle:(id)arg1 forState:(unsigned)arg2 ;
-(void)setBackgroundColor:(id)arg1 ;
@end

