/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:54 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/UIView.h>

@class UIButton, NSString;

@interface MFConversationItemFooterView : UIView {

	UIButton* _seeMoreButton;
	UIButton* _revealActionsButton;
	NSString* _senderName;

}

@property (nonatomic,retain) UIButton * seeMoreButton;                    //@synthesize seeMoreButton=_seeMoreButton - In the implementation block
@property (nonatomic,retain) UIButton * revealActionsButton;              //@synthesize revealActionsButton=_revealActionsButton - In the implementation block
@property (nonatomic,copy) NSString * senderName;                         //@synthesize senderName=_senderName - In the implementation block
+(id)prefixFont;
+(id)nameFont;
-(void)_fontMetricCacheDidInvalidate:(id)arg1 ;
-(void)hideAttribution;
-(void)showAttributionWithSenderName:(id)arg1 ;
-(void)setRevealActionsButton:(UIButton *)arg1 ;
-(UIButton *)revealActionsButton;
-(void)_updateAttributedTitle;
-(void)layoutActionButton;
-(void)layoutSeeMoreButton;
-(id)_attributedButtonTitleWithSenderName:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(UIButton *)seeMoreButton;
-(void)setSeeMoreButton:(UIButton *)arg1 ;
-(NSString *)senderName;
-(void)setSenderName:(NSString *)arg1 ;
-(void)render:(id)arg1 ;
-(void)_updateIcon;
@end

