/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:57 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIWindow.h>

@interface MFWindow : UIWindow {

	/*^block*/id _touchEventListener;

}

@property (nonatomic,copy) id touchEventListener;              //@synthesize touchEventListener=_touchEventListener - In the implementation block
-(void)setTouchEventListener:(id)arg1 ;
-(id)touchEventListener;
-(void)dealloc;
-(void)sendEvent:(id)arg1 ;
@end

