/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:39:01 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSXPCListenerDelegate.h>

@class NSLock, NSMutableArray, MFWeakReferenceHolder, NSXPCListener, NSArray, NSString;

@interface MFXPCEndpointListener : NSObject <NSXPCListenerDelegate> {

	NSLock* _lock;
	NSMutableArray* _clientInfos;
	MFWeakReferenceHolder* _endpointHolder;
	NSXPCListener* _listener;

}

@property (nonatomic,retain) NSXPCListener * listener;                //@synthesize listener=_listener - In the implementation block
@property (nonatomic,retain,readonly) NSArray * clients; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithEndpointInfo:(id)arg1 ;
-(void)removeClientInfo:(id)arg1 ;
-(void)addClientInfo:(id)arg1 ;
-(void)dealloc;
-(NSString *)description;
-(char)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2 ;
-(NSXPCListener *)listener;
-(void)setListener:(NSXPCListener *)arg1 ;
-(id)endpointInfo;
-(NSArray *)clients;
@end

