/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:25:34 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/SiriViewService.app/SiriViewService
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SiriUIPresentation <NSObject>
@property (assign,nonatomic,__weak) id<SiriUIPresentationDataSource> dataSource; 
@property (assign,nonatomic,__weak) id<SiriUIPresentationDelegate> delegate; 
@optional
-(id)initWithDelegate:(id)arg1 dataSource:(id)arg2;
-(void)siriDidTransitionFromState:(int)arg1 event:(int)arg2;
-(void)statusBarFrameDidChange;
-(void)updateSuggestedUtterances:(id)arg1 forLanguage:(id)arg2;
-(void)siriRequestWillStart;
-(void)changeUtterance:(id)arg1;
-(void)showSpeechAlternatives:(id)arg1;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 delegate:(id)arg3 dataSource:(id)arg4;
-(void)siriDidFinishTest:(id)arg1;
-(void)removeItemsWithIdentifiers:(id)arg1 atIndexPaths:(id)arg2 parentItemIdentifiers:(id)arg3;
-(void)presentationStateDidChangeForItemsAtIndexPaths:(id)arg1;
-(char)siriDidReceiveAdditionalContent:(id)arg1;
-(void)conversation:(id)arg1 didChangePresentationStateForItemsAtIndexPaths:(id)arg2;
-(void)siriDidFinishActionsForConversationItemWithIdentifier:(id)arg1 inConversation:(id)arg2;
-(void)startNewConversation;
-(char)canSaveConversations;
-(void)siriWillHidePasscodeUnlock;
-(void)siriDidStartSpeaking;
-(void)siriDidStopSpeaking:(char)arg1;
-(void)siriAudioRecordingDidChangePowerLevel:(float)arg1;
-(id)configureOptionsForImminentRequest:(id)arg1;
-(double)idleTimerInterval;
-(char)shouldDismissForIdling;
-(void)setScreenSupportsTouchInteraction:(char)arg1;
-(void)siriNetworkAvailabilityDidChange;
-(void)speechRecordingDidEndForRequest:(id)arg1 onAVRecordRoute:(id)arg2;
-(void)speechRecordingDidCancelForRequest:(id)arg1 onAVRecordRoute:(id)arg2;
-(void)speechRecordingDidFailForRequest:(id)arg1 onAVRecordRoute:(id)arg2 withError:(id)arg3;
-(void)speechRecordingDidDetectSpeechStartpoint;
-(char)shouldBlockURLOpenOnTTS:(id)arg1;
-(void)configureForRequestOptions:(id)arg1;
-(char)trustsURL:(id)arg1;
-(void)siriDidDetectMusic;
-(char)supportsSpeechSynthesis;
-(void)displayUtteranceWithTitle:(id)arg1 subtitle:(id)arg2;
-(void)didReceiveDismissalAction:(/*^block*/id)arg1;
-(void)dismissRecordingOverlayAndHideSnippets:(char)arg1;
-(char)supportsTextInput;
-(void)siriWillStartTest:(id)arg1;
-(void)removeItemsWithIdentifiers:(id)arg1 atIndexPaths:(id)arg2;
-(void)setDataSource:(id)arg1;
-(void)setDelegate:(id)arg1;
-(void)reloadData;
-(id<SiriUIPresentationDataSource>)dataSource;
-(id<SiriUIPresentationDelegate>)delegate;
-(id)viewController;
-(int)options;
-(void)insertItemsAtIndexPaths:(id)arg1;
-(void)reloadItemsAtIndexPaths:(id)arg1;
-(void)acousticIDRequestDidFinishWithSuccess:(char)arg1;
-(void)conversation:(id)arg1 didRemoveItemsWithIdentifiers:(id)arg2 atIndexPaths:(id)arg3 parentItemIdentifiers:(id)arg4;
-(void)conversation:(id)arg1 didUpdateItemsAtIndexPaths:(id)arg2;
-(void)conversation:(id)arg1 didInsertItemsAtIndexPaths:(id)arg2;
-(void)hostApplicationDidBecomeActive;
-(void)hostApplicationWillEnterForeground;
-(void)siriWillActivateFromSource:(int)arg1;
-(void)siriDidDeactivate;
-(void)siriDidActivateFromSource:(int)arg1;
-(void)siriWillShowPasscodeUnlockAndCancelRequest:(char)arg1;
-(void)siriDidHidePasscodeUnlock;
-(void)userInteractionDidOccur;
-(void)didReceiveHelpAction;
-(void)didReceiveReportBugAction;
-(void)didReceiveBugButtonLongPress;
-(void)hostApplicationWillResignActive;
-(void)siriWillShowPasscodeUnlock;
-(void)shortTapAction;
-(id)requestContext;

@end

