/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:29 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Home.app/Home
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <HomeUI/HUServiceGridViewController.h>
#import <libobjc.A.dylib/HUPresentationDelegate.h>
#import <libobjc.A.dylib/HUServiceGridItemManagerDelegate.h>
#import <libobjc.A.dylib/HUQuickControlDetailsPresentationDelegateHost.h>

@protocol HUPresentationDelegate, HOServiceContainerItemNSCopying, HOContainedServiceGridViewControllerDelegate;
@class HFItem, NSString;

@interface HOContainedServicesGridViewController : HUServiceGridViewController <HUPresentationDelegate, HUServiceGridItemManagerDelegate, HUQuickControlDetailsPresentationDelegateHost> {

	char requiresQuickControlDismissal;
	char _presentedModally;
	id<HUPresentationDelegate> _presentationDelegate;
	HFItem*<HOServiceContainerItem>*<NSCopying> _serviceContainerItem;
	id<HOContainedServiceGridViewControllerDelegate> _serviceGridDelegate;

}

@property (assign,getter=isPresentedModally,nonatomic) char presentedModally;                                          //@synthesize presentedModally=_presentedModally - In the implementation block
@property (nonatomic,copy,readonly) HFItem*<HOServiceContainerItem>*<NSCopying> serviceContainerItem;                  //@synthesize serviceContainerItem=_serviceContainerItem - In the implementation block
@property (assign,nonatomic,__weak) id<HOContainedServiceGridViewControllerDelegate> serviceGridDelegate;              //@synthesize serviceGridDelegate=_serviceGridDelegate - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic,__weak) id<HUPresentationDelegate> presentationDelegate;                                   //@synthesize presentationDelegate=_presentationDelegate - In the implementation block
@property (assign,nonatomic) char requiresQuickControlDismissal; 
-(id)initWithServiceContainerItem:(id)arg1 isPresentedModally:(char)arg2 valueSource:(id)arg3 ;
-(void)setServiceGridDelegate:(id<HOContainedServiceGridViewControllerDelegate>)arg1 ;
-(HFItem*<HOServiceContainerItem>*<NSCopying>)serviceContainerItem;
-(void)_updateRightBarButtons;
-(id<HOContainedServiceGridViewControllerDelegate>)serviceGridDelegate;
-(id)initWithServiceContainerItem:(id)arg1 ;
-(void)viewDidLoad;
-(void)setPresentedModally:(char)arg1 ;
-(char)isPresentedModally;
-(id<HUPresentationDelegate>)presentationDelegate;
-(void)setPresentationDelegate:(id<HUPresentationDelegate>)arg1 ;
-(void)_edit:(id)arg1 ;
-(char)hasDetailsActionForPresentationCoordinator:(id)arg1 item:(id)arg2 ;
-(id)detailsViewControllerForPresentationCoordinator:(id)arg1 item:(id)arg2 ;
-(void)finishPresentation:(id)arg1 animated:(char)arg2 ;
-(char)itemManager:(id)arg1 performBatchUpdateBlock:(/*^block*/id)arg2 ;
-(id)initWithItemManager:(id)arg1 ;
-(id)layoutOptionsForSection:(int)arg1 ;
-(char)requiresQuickControlDismissal;
-(void)setRequiresQuickControlDismissal:(char)arg1 ;
-(void)_done:(id)arg1 ;
@end

