/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:30 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Home.app/Home
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol HORoomViewControllerDelegate <NSObject>
@required
-(void)presentRoomListPickerForRoomViewController:(id)arg1 fromView:(id)arg2;
-(void)presentRoomEditorForRoomViewController:(id)arg1;

@end

