/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:25 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Home.app/Home
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol HOTriggerEditorDelegate <NSObject>
@optional
-(char)triggerEditor:(id)arg1 shouldCommitTriggerBuilder:(id)arg2;

@required
-(void)triggerEditor:(id)arg1 didFinishWithTriggerBuilder:(id)arg2;

@end

