/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:39:52 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/iBooks.app/Frameworks/BookCore.framework/BookCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <BookCore/AEBookMetadataProvider.h>

@class NSString, NSURL;

@interface AESingleBookMetadataProvider : NSObject <AEBookMetadataProvider> {

	char managedBook;
	NSString* assetID;
	NSURL* assetURL;
	NSString* bookVersionString;
	NSString* pathToAssetContextDirectory;

}

@property (nonatomic,retain) NSString * assetID; 
@property (nonatomic,retain) NSURL * assetURL; 
@property (nonatomic,retain) NSString * bookVersionString; 
@property (nonatomic,retain) NSString * pathToAssetContextDirectory; 
@property (assign,getter=isManagedBook,nonatomic) char managedBook; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)singleBookMetadataProviderWithAssetID:(id)arg1 assetURL:(id)arg2 bookVersionString:(id)arg3 pathToAssetContextDirectory:(id)arg4 isManagedBook:(char)arg5 ;
-(NSString *)assetID;
-(char)isManagedBook;
-(char)isManagedWithAssetID:(id)arg1 ;
-(id)assetURLForAssetID:(id)arg1 ;
-(id)pathToContextDirectoryForAssetID:(id)arg1 ;
-(id)bookVersionStringForAssetID:(id)arg1 ;
-(id)initWithAssetID:(id)arg1 assetURL:(id)arg2 bookVersionString:(id)arg3 pathToAssetContextDirectory:(id)arg4 isManagedBook:(char)arg5 ;
-(void)setAssetID:(NSString *)arg1 ;
-(void)setBookVersionString:(NSString *)arg1 ;
-(void)setPathToAssetContextDirectory:(NSString *)arg1 ;
-(NSString *)bookVersionString;
-(NSString *)pathToAssetContextDirectory;
-(void)setAssetURL:(NSURL *)arg1 ;
-(NSString *)description;
-(NSURL *)assetURL;
-(void)setManagedBook:(char)arg1 ;
@end

