/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:39:51 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/iBooks.app/Frameworks/BookCore.framework/BookCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <BookCore/BookCore-Structs.h>
#import <BookCore/IMViewControllerTransitionContext.h>

@class UIViewController;

@interface IMViewControllerOneToOneTransitionContext : IMViewControllerTransitionContext {

	UIViewController* _fromViewController;
	UIViewController* _toViewController;
	CGRect _fromStartFrame;
	CGRect _fromEndFrame;
	CGRect _toEndFrame;
	CGRect _toStartFrame;

}

@property (setter=_setFromViewController:,nonatomic,retain) UIViewController * fromViewController;              //@synthesize fromViewController=_fromViewController - In the implementation block
@property (setter=_setToViewController:,nonatomic,retain) UIViewController * toViewController;                  //@synthesize toViewController=_toViewController - In the implementation block
@property (assign,setter=_setFromStartFrame:,nonatomic) CGRect fromStartFrame;                                  //@synthesize fromStartFrame=_fromStartFrame - In the implementation block
@property (assign,setter=_setFromEndFrame:,nonatomic) CGRect fromEndFrame;                                      //@synthesize fromEndFrame=_fromEndFrame - In the implementation block
@property (assign,setter=_setToEndFrame:,nonatomic) CGRect toEndFrame;                                          //@synthesize toEndFrame=_toEndFrame - In the implementation block
@property (assign,setter=_setToStartFrame:,nonatomic) CGRect toStartFrame;                                      //@synthesize toStartFrame=_toStartFrame - In the implementation block
-(void)dealloc;
-(id)viewControllerForKey:(id)arg1 ;
-(id)viewForKey:(id)arg1 ;
-(CGRect)initialFrameForViewController:(id)arg1 ;
-(CGRect)finalFrameForViewController:(id)arg1 ;
-(void)_setFromViewController:(id)arg1 ;
-(void)_setToViewController:(id)arg1 ;
-(void)_setFromStartFrame:(CGRect)arg1 ;
-(void)_setToEndFrame:(CGRect)arg1 ;
-(void)_setToStartFrame:(CGRect)arg1 ;
-(void)_setFromEndFrame:(CGRect)arg1 ;
-(UIViewController *)fromViewController;
-(UIViewController *)toViewController;
-(CGRect)toStartFrame;
-(CGRect)fromStartFrame;
-(CGRect)toEndFrame;
-(CGRect)fromEndFrame;
@end

