/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:25:26 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Reminders.app/Reminders
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Reminders/Reminders-Structs.h>
#import <UIKit/UIViewController.h>
#import <Reminders/RemindersCardStackViewDataSource.h>
#import <Reminders/RemindersCardStackViewDelegate.h>
#import <Reminders/RemindersArchiving.h>
#import <Reminders/RemindersNewListControllerDelegate.h>
#import <Reminders/RemindersListControllerDelegate.h>
#import <Reminders/RemindersSearchControllerDelegate.h>
#import <Reminders/RemindersInvitationControllerDelegate.h>
#import <UIKit/UIScrollViewDelegate.h>

@class RemindersCardStackView, RemindersCategoryListController, UIView, RemindersCardController, EKCalendar, RemindersDetailEditorController, RemindersSearchController, NSString;

@interface RemindersCardStackViewController : UIViewController <RemindersCardStackViewDataSource, RemindersCardStackViewDelegate, RemindersArchiving, RemindersNewListControllerDelegate, RemindersListControllerDelegate, RemindersSearchControllerDelegate, RemindersInvitationControllerDelegate, UIScrollViewDelegate> {

	RemindersCardStackView* _stackView;
	RemindersCategoryListController* _highlightedList;
	UIView* _containerView;
	RemindersCardController* _newListCard;
	CGPoint _scrollOffsetAtDragStart;
	float _originalCardHeight;
	char _isDeleting;
	EKCalendar* _reorderingCalendar;
	EKCalendar* _cachedInvitation;
	RemindersDetailEditorController* _detailController;
	char _needsReload;
	char _hasPerformedInitialLoad;
	char _showingNewListCard;
	RemindersSearchController* _searchController;

}

@property (assign) char needsReload;                                            //@synthesize needsReload=_needsReload - In the implementation block
@property (assign) char hasPerformedInitialLoad;                                //@synthesize hasPerformedInitialLoad=_hasPerformedInitialLoad - In the implementation block
@property (assign) char showingNewListCard;                                     //@synthesize showingNewListCard=_showingNewListCard - In the implementation block
@property (readonly) RemindersSearchController * searchController;              //@synthesize searchController=_searchController - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(char)_shouldForwardViewWillTransitionToSize;
-(char)hasPerformedInitialLoad;
-(void)setHasPerformedInitialLoad:(char)arg1 ;
-(void)displaySearch;
-(void)invitationControllerDeclined:(id)arg1 ;
-(void)invitationControllerAccepted:(id)arg1 ;
-(id)displayedCard;
-(void)applyArchive:(id)arg1 ;
-(void)endSearching;
-(id)sortedCalendars;
-(void)eventStoreChangedWithChangedObjectIDs:(id)arg1 ;
-(void)alarmsFired;
-(void)highlightReminder:(id)arg1 withSearchTerm:(id)arg2 ;
-(void)displayCalendar:(id)arg1 ;
-(void)displayScheduledCard;
-(char)listControllerIsOnTop:(id)arg1 ;
-(void)listControllerBeganEditing:(id)arg1 ;
-(void)listControllerEndedEditing:(id)arg1 ;
-(void)listControllerFinishedLoadingData:(id)arg1 ;
-(void)listControllerDeletedList:(id)arg1 atIndex:(int)arg2 ;
-(void)resizeToSize:(CGSize)arg1 ;
-(void)swapDisplayedCard:(id)arg1 ;
-(void)searchController:(id)arg1 willBecomeActive:(char)arg2 ;
-(void)searchController:(id)arg1 didSelectReminder:(id)arg2 forSearchTerm:(id)arg3 ;
-(void)searchControllerDidTapActionButton:(id)arg1 ;
-(void)newListControllerCreatedList:(id)arg1 ;
-(void)newListControllerCanceledList:(id)arg1 ;
-(id)cardAtIndex:(int)arg1 ;
-(void)performTestSearch;
-(char)cardStackView:(id)arg1 cardShouldSlideBackIntoStackWhenDismissed:(id)arg2 ;
-(float)cardSpacing;
-(void)cardStackViewDidPresentCard:(id)arg1 ;
-(void)cardStackView:(id)arg1 willAddGestureRecognizer:(id)arg2 toCardAtIndex:(int)arg3 ;
-(void)cardStackView:(id)arg1 didDismissCard:(id)arg2 ;
-(int)indexOfCard:(id)arg1 ;
-(int)cardStackView:(id)arg1 targetIndexForMoveFromIndex:(int)arg2 toProposedIndex:(int)arg3 ;
-(void)cardStackView:(id)arg1 cardDidMoveFromIndex:(int)arg2 toIndex:(int)arg3 ;
-(void)cardStackViewDidEndReordering:(id)arg1 ;
-(char)cardStackView:(id)arg1 canReorderCardAtIndex:(int)arg2 ;
-(void)deleteCard:(id)arg1 atIndex:(int)arg2 ;
-(void)_loadInitialList;
-(void)_reloadStack;
-(char)showingNewListCard;
-(void)setShowingNewListCard:(char)arg1 ;
-(void)_loadSecondaryListsIfNeeded;
-(void)createReminder;
-(void)cancelAddReminder;
-(void)showNewListCard;
-(void)unhighlightReminder;
-(int)numberOfInvitations;
-(void)scrollViewDidScroll:(id)arg1 ;
-(void)scrollViewWillBeginDragging:(id)arg1 ;
-(void)scrollViewWillEndDragging:(id)arg1 withVelocity:(CGPoint)arg2 targetContentOffset:(inout CGPoint*)arg3 ;
-(void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(char)arg2 ;
-(void)scrollViewDidEndDecelerating:(id)arg1 ;
-(int)state;
-(void)didMoveToParentViewController:(id)arg1 ;
-(void)loadView;
-(void)viewDidAppear:(char)arg1 ;
-(void)setContentOffset:(CGPoint)arg1 ;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)endEditing;
-(id)searchResultsTableView;
-(RemindersSearchController *)searchController;
-(void)setNeedsReload:(char)arg1 ;
-(int)numberOfCards;
-(void)beginSearch:(id)arg1 ;
-(id)_stackView;
-(id)searchViewController;
-(char)needsReload;
-(id)archive;
@end

