/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:25:26 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Reminders.app/Reminders
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Reminders/Reminders-Structs.h>
#import <UIKit/UIViewController.h>
#import <UIKit/UISplitViewControllerDelegate.h>

@class RemindersCardStackViewController, RemindersSplitViewController, UIView, RemindersDebugMenuViewController, UITraitCollection;

@interface RemindersRootViewController : UIViewController <UISplitViewControllerDelegate> {

	RemindersCardStackViewController* _stackViewController;
	RemindersSplitViewController* _splitViewController;
	int _currentHorizontalSizeClass;
	int _currentVerticalSizeClass;
	UIView* _debugView;
	RemindersDebugMenuViewController* _debugController;
	UITraitCollection* _overrideTraitCollection;
	char _isInSizeTransition;
	int _transitionToHorizontalSizeClass;
	int _transitionToVerticalSizeClass;
	CGSize _transitionToSize;

}

@property (readonly) RemindersCardStackViewController * stackViewController;              //@synthesize stackViewController=_stackViewController - In the implementation block
@property (readonly) RemindersSplitViewController * splitViewController;                  //@synthesize splitViewController=_splitViewController - In the implementation block
@property (readonly) char isInSizeTransition;                                             //@synthesize isInSizeTransition=_isInSizeTransition - In the implementation block
@property (readonly) int transitionToHorizontalSizeClass;                                 //@synthesize transitionToHorizontalSizeClass=_transitionToHorizontalSizeClass - In the implementation block
@property (readonly) int transitionToVerticalSizeClass;                                   //@synthesize transitionToVerticalSizeClass=_transitionToVerticalSizeClass - In the implementation block
@property (readonly) CGSize transitionToSize;                                             //@synthesize transitionToSize=_transitionToSize - In the implementation block
+(char)_shouldForwardViewWillTransitionToSize;
-(RemindersCardStackViewController *)stackViewController;
-(char)isInSizeTransition;
-(CGSize)transitionToSize;
-(void)addStackViewController;
-(void)addSplitViewController;
-(void)_debugViewPanned:(id)arg1 ;
-(int)transitionToHorizontalSizeClass;
-(int)transitionToVerticalSizeClass;
-(id)init;
-(id)traitCollection;
-(int)preferredStatusBarStyle;
-(char)shouldAutorotate;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidAppear:(char)arg1 ;
-(RemindersSplitViewController *)splitViewController;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)viewDidLoad;
-(char)splitViewController:(id)arg1 collapseSecondaryViewController:(id)arg2 ontoPrimaryViewController:(id)arg3 ;
-(void)beginSearch:(id)arg1 ;
@end

