/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:18 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/FindMyFriends.app/FindMyFriends
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <FindMyFriends/FMFBaseCmd.h>

@class NSArray, NSString;

@interface FMFInviteCommand : FMFBaseCmd {

	char _ignoreResponse;
	NSArray* _emails;
	NSString* _message;
	NSArray* _friendIds;

}

@property (nonatomic,copy) NSArray * emails;                   //@synthesize emails=_emails - In the implementation block
@property (nonatomic,copy) NSString * message;                 //@synthesize message=_message - In the implementation block
@property (nonatomic,copy) NSArray * friendIds;                //@synthesize friendIds=_friendIds - In the implementation block
@property (assign,nonatomic) char ignoreResponse;              //@synthesize ignoreResponse=_ignoreResponse - In the implementation block
-(id)willSucceedNotification;
-(id)willFailNotification;
-(char)isFireAndForget;
-(id)customCommandNotification;
-(id)didSucceedNotification;
-(id)didFailNotification;
-(id)pathSuffix;
-(void)setFriendIds:(NSArray *)arg1 ;
-(id)initWithHandles:(id)arg1 forIds:(id)arg2 message:(id)arg3 ;
-(id)initWithHandles:(id)arg1 forIds:(id)arg2 message:(id)arg3 ignoreResponse:(char)arg4 ;
-(NSArray *)friendIds;
-(id)initWithEmails:(id)arg1 message:(id)arg2 ;
-(void)setMessage:(NSString *)arg1 ;
-(NSString *)message;
-(char)ignoreResponse;
-(void)setIgnoreResponse:(char)arg1 ;
-(NSArray *)emails;
-(id)jsonBodyDictionary;
-(void)setEmails:(NSArray *)arg1 ;
@end

