/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:18 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/FindMyFriends.app/FindMyFriends
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <FindMyFriends/FMFBaseCmd.h>

@class NSString;

@interface FMFRemoveFriendCommand : FMFBaseCmd {

	NSString* _friendId;

}

@property (nonatomic,copy) NSString * friendId;              //@synthesize friendId=_friendId - In the implementation block
-(id)willSucceedNotification;
-(id)willFailNotification;
-(id)didSucceedNotification;
-(id)didFailNotification;
-(id)pathSuffix;
-(void)setFriendId:(NSString *)arg1 ;
-(NSString *)friendId;
-(id)initWithFriendId:(id)arg1 ;
-(id)jsonBodyDictionary;
@end

