/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:25:08 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobilePhone.app/MobilePhone
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobilePhone/MobilePhone-Structs.h>
#import <UIKit/UITextField.h>

@protocol PHLCDViewTextFieldDelegate;
@class NSCharacterSet, NSString;

@interface PHLCDViewTextField : UITextField {

	id<PHLCDViewTextFieldDelegate> _lcdViewTextFieldDelegate;
	NSCharacterSet* _specialDialerCharacters;
	NSString* _previousTextSuggestion;

}

@property (nonatomic,retain) NSCharacterSet * specialDialerCharacters;                                    //@synthesize specialDialerCharacters=_specialDialerCharacters - In the implementation block
@property (nonatomic,retain) NSString * previousTextSuggestion;                                           //@synthesize previousTextSuggestion=_previousTextSuggestion - In the implementation block
@property (assign,nonatomic,__weak) id<PHLCDViewTextFieldDelegate> lcdViewTextFieldDelegate;              //@synthesize lcdViewTextFieldDelegate=_lcdViewTextFieldDelegate - In the implementation block
-(void)setLcdViewTextFieldDelegate:(id<PHLCDViewTextFieldDelegate>)arg1 ;
-(void)_textFieldDidUpdate:(id)arg1 ;
-(NSString *)previousTextSuggestion;
-(void)setPreviousTextSuggestion:(NSString *)arg1 ;
-(void)reformatText;
-(NSCharacterSet *)specialDialerCharacters;
-(id<PHLCDViewTextFieldDelegate>)lcdViewTextFieldDelegate;
-(void)setSpecialDialerCharacters:(NSCharacterSet *)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
-(char)canPerformAction:(SEL)arg1 withSender:(id)arg2 ;
-(void)setText:(id)arg1 ;
-(void)replaceRange:(id)arg1 withText:(id)arg2 ;
-(void)deleteBackward;
-(void)paste:(id)arg1 ;
-(void)_updateTextLabel;
@end

