/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:25:08 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobilePhone.app/MobilePhone
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobilePhone/PHAudioRecorderDelegate.h>

@protocol PHVoicemailGreetingModelDelegate;
@class VMVoicemailGreeting, PHAudioRecorder;

@interface PHVoicemailGreetingModel : NSObject <PHAudioRecorderDelegate> {

	id<PHVoicemailGreetingModelDelegate> _delegate;
	int _greetingState;
	VMVoicemailGreeting* _currentGreeting;
	PHAudioRecorder* _greetingRecorder;
	double _maximumGreetingDuration;
	double _greetingDuration;

}

@property (nonatomic,retain) VMVoicemailGreeting * currentGreeting;                             //@synthesize currentGreeting=_currentGreeting - In the implementation block
@property (assign,nonatomic) double maximumGreetingDuration;                                    //@synthesize maximumGreetingDuration=_maximumGreetingDuration - In the implementation block
@property (nonatomic,retain) PHAudioRecorder * greetingRecorder;                                //@synthesize greetingRecorder=_greetingRecorder - In the implementation block
@property (assign,nonatomic) double greetingDuration;                                           //@synthesize greetingDuration=_greetingDuration - In the implementation block
@property (assign,nonatomic,__weak) id<PHVoicemailGreetingModelDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) int greetingState;                                                 //@synthesize greetingState=_greetingState - In the implementation block
-(void)_handlePlayerControllerRateOrStatusChange:(id)arg1 ;
-(void)_handlePlayerDidFinishPlaying:(id)arg1 ;
-(void)_mediaserverReset:(id)arg1 ;
-(void)fetchGreeting;
-(int)greetingState;
-(void)pauseGreeting;
-(void)saveGreeting:(unsigned)arg1 ;
-(void)playGreeting;
-(char)greetingExists;
-(void)audioRecorderStartedWithFile:(id)arg1 ;
-(void)audioRecorderContinuedWithFile:(id)arg1 duration:(double)arg2 ;
-(void)audioRecorderEndedWithFile:(id)arg1 duration:(double)arg2 error:(id)arg3 ;
-(id)greetingTempFileLocation;
-(PHAudioRecorder *)greetingRecorder;
-(void)setGreetingState:(int)arg1 ;
-(VMVoicemailGreeting *)currentGreeting;
-(void)_loadGreeting:(id)arg1 ;
-(void)setCurrentGreeting:(VMVoicemailGreeting *)arg1 ;
-(void)setMaximumGreetingDuration:(double)arg1 ;
-(void)setGreetingRecorder:(PHAudioRecorder *)arg1 ;
-(double)greetingDuration;
-(void)setGreetingDuration:(double)arg1 ;
-(id)init;
-(void)setDelegate:(id<PHVoicemailGreetingModelDelegate>)arg1 ;
-(void)dealloc;
-(id<PHVoicemailGreetingModelDelegate>)delegate;
-(double)maximumGreetingDuration;
-(int)mailboxGreetingState;
-(void)stopRecording;
-(void)startRecording;
@end

