/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:39:12 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobilePhone.app/MobilePhone
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobilePhone/MobilePhone-Structs.h>
#import <MediaPlayer/MPDetailSlider.h>

@interface VMPlayerTimelineSlider : MPDetailSlider
-(id)init;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)timeLabelFontForStyle:(int)arg1 ;
-(id)timeLabelTextColorForStyle:(int)arg1 ;
@end

