/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:23:52 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Contacts.app/Contacts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Contacts/ContactsTest.h>

@class NSMutableDictionary, NSArray, CNTestNavigationControllerDelegate;

@interface ShowPseudoContactsTest : ContactsTest {

	char _animate;
	int _nextContactIndex;
	int _maxContactIndex;
	NSMutableDictionary* _extraResults;
	unsigned _currentDirectoryIndex;
	NSArray* _allSearchQueries;
	unsigned _currentQueryIndex;
	CNTestNavigationControllerDelegate* _navControllerDelegate;
	double _lastSearchBeginTime;

}

@property (assign,nonatomic) int nextContactIndex;                                                    //@synthesize nextContactIndex=_nextContactIndex - In the implementation block
@property (assign,nonatomic) int maxContactIndex;                                                     //@synthesize maxContactIndex=_maxContactIndex - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * extraResults;                                      //@synthesize extraResults=_extraResults - In the implementation block
@property (assign,nonatomic) unsigned currentDirectoryIndex;                                          //@synthesize currentDirectoryIndex=_currentDirectoryIndex - In the implementation block
@property (assign,nonatomic) char animate;                                                            //@synthesize animate=_animate - In the implementation block
@property (nonatomic,retain) NSArray * allSearchQueries;                                              //@synthesize allSearchQueries=_allSearchQueries - In the implementation block
@property (assign,nonatomic) unsigned currentQueryIndex;                                              //@synthesize currentQueryIndex=_currentQueryIndex - In the implementation block
@property (assign,nonatomic) double lastSearchBeginTime;                                              //@synthesize lastSearchBeginTime=_lastSearchBeginTime - In the implementation block
@property (nonatomic,retain) CNTestNavigationControllerDelegate * navControllerDelegate;              //@synthesize navControllerDelegate=_navControllerDelegate - In the implementation block
-(char)prepareForTestWithOptions:(id)arg1 ;
-(void)setExtraResults:(NSMutableDictionary *)arg1 ;
-(void)setAllSearchQueries:(NSArray *)arg1 ;
-(void)setCurrentQueryIndex:(unsigned)arg1 ;
-(void)startSearchQuery;
-(NSArray *)allSearchQueries;
-(unsigned)currentQueryIndex;
-(void)setLastSearchBeginTime:(double)arg1 ;
-(double)lastSearchBeginTime;
-(NSMutableDictionary *)extraResults;
-(unsigned)currentDirectoryIndex;
-(void)setCurrentDirectoryIndex:(unsigned)arg1 ;
-(void)didShow:(id)arg1 ;
-(void)setNavControllerDelegate:(CNTestNavigationControllerDelegate *)arg1 ;
-(CNTestNavigationControllerDelegate *)navControllerDelegate;
-(void)prepareForNextTest;
-(void)setNextContactIndex:(int)arg1 ;
-(void)setMaxContactIndex:(int)arg1 ;
-(void)showNextContact;
-(void)iterateContact;
-(int)nextContactIndex;
-(int)maxContactIndex;
-(void)ShowPseudoContactsList;
-(char)animate;
-(void)setAnimate:(char)arg1 ;
@end

