/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:25:19 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/News.app/PlugIns/NewsToday.appex/NewsToday
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <NewsToday/FRPersonalizationFeature.h>

@interface FRPublisherPremiumFeature : FRPersonalizationFeature {

	char _premium;

}

@property (assign,nonatomic) char premium;              //@synthesize premium=_premium - In the implementation block
-(id)initWithTagID:(id)arg1 premium:(char)arg2 ;
-(id)initWithPersonalizationIdentifier:(id)arg1 ;
-(id)fr_description;
-(void)setPremium:(char)arg1 ;
-(char)premium;
-(id)init;
@end

