/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:25:19 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/News.app/PlugIns/NewsToday.appex/NewsToday
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <NewsToday/NewsToday-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, NSSet;

@interface FTCatchUpOperationForYouRequest : NSObject <NSCopying> {

	NSString* _topStoriesChannelID;
	NSSet* _hiddenFeedIDs;
	NSSet* _mutedTagIDs;
	NSSet* _purchasedTagIDs;
	NSSet* _subscribedTagIDs;
	int _fetchingBin;
	long long _cutoffTime;
	unsigned long long _headlinesPerFeedFetchCount;

}

@property (nonatomic,copy,readonly) NSString * topStoriesChannelID;                        //@synthesize topStoriesChannelID=_topStoriesChannelID - In the implementation block
@property (nonatomic,copy,readonly) NSSet * hiddenFeedIDs;                                 //@synthesize hiddenFeedIDs=_hiddenFeedIDs - In the implementation block
@property (nonatomic,copy,readonly) NSSet * mutedTagIDs;                                   //@synthesize mutedTagIDs=_mutedTagIDs - In the implementation block
@property (nonatomic,copy,readonly) NSSet * purchasedTagIDs;                               //@synthesize purchasedTagIDs=_purchasedTagIDs - In the implementation block
@property (nonatomic,copy,readonly) NSSet * subscribedTagIDs;                              //@synthesize subscribedTagIDs=_subscribedTagIDs - In the implementation block
@property (nonatomic,readonly) long long cutoffTime;                                       //@synthesize cutoffTime=_cutoffTime - In the implementation block
@property (nonatomic,readonly) unsigned long long headlinesPerFeedFetchCount;              //@synthesize headlinesPerFeedFetchCount=_headlinesPerFeedFetchCount - In the implementation block
@property (nonatomic,readonly) int fetchingBin;                                            //@synthesize fetchingBin=_fetchingBin - In the implementation block
-(id)initWithForYouWidgetSectionSpecificConfig:(id)arg1 topStoriesChannelID:(id)arg2 hiddenFeedIDs:(id)arg3 mutedTagIDs:(id)arg4 purchasedTagIDs:(id)arg5 subscribedTagIDs:(id)arg6 ;
-(NSString *)topStoriesChannelID;
-(id)init;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSSet *)mutedTagIDs;
-(NSSet *)purchasedTagIDs;
-(NSSet *)subscribedTagIDs;
-(NSSet *)hiddenFeedIDs;
-(long long)cutoffTime;
-(int)fetchingBin;
-(unsigned long long)headlinesPerFeedFetchCount;
@end

