/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:19 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Fitness.app/Fitness
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Fitness/Fitness-Structs.h>
#import <UIKit/UIView.h>

@class UILabel, NSString, UIColor;

@interface _CHWorkoutSummaryTabbedLabelContainer : UIView {

	UILabel* _titleLabel;
	UILabel* _totalLabel;
	UILabel* _averageLabel;
	NSString* _titleText;
	NSString* _totalText;
	NSString* _averageText;
	UIColor* _textColor;

}

@property (nonatomic,retain) NSString * titleText;                //@synthesize titleText=_titleText - In the implementation block
@property (nonatomic,retain) NSString * totalText;                //@synthesize totalText=_totalText - In the implementation block
@property (nonatomic,retain) NSString * averageText;              //@synthesize averageText=_averageText - In the implementation block
@property (nonatomic,retain) UIColor * textColor;                 //@synthesize textColor=_textColor - In the implementation block
-(void)setTotalText:(NSString *)arg1 ;
-(void)setAverageText:(NSString *)arg1 ;
-(NSString *)totalText;
-(NSString *)averageText;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)setText:(id)arg1 ;
-(void)setTextColor:(UIColor *)arg1 ;
-(float)_firstBaselineOffsetFromTop;
-(void)sizeToFit;
-(CGSize)intrinsicContentSize;
-(UIColor *)textColor;
-(void)setTitleText:(NSString *)arg1 ;
-(NSString *)titleText;
@end

