/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:23 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Fitness.app/Fitness
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Fitness/Fitness-Structs.h>
#import <UIKit/UITableViewCell.h>

@class HKActivityRingView, UILabel;

@interface CHFriendListTableViewCell : UITableViewCell {

	int _displayMode;
	HKActivityRingView* _ringView;
	UILabel* _detailLineOneLabel;
	UILabel* _detailLineTwoLabel;

}

@property (nonatomic,retain) HKActivityRingView * ringView;              //@synthesize ringView=_ringView - In the implementation block
@property (nonatomic,retain) UILabel * detailLineOneLabel;               //@synthesize detailLineOneLabel=_detailLineOneLabel - In the implementation block
@property (nonatomic,retain) UILabel * detailLineTwoLabel;               //@synthesize detailLineTwoLabel=_detailLineTwoLabel - In the implementation block
@property (assign,nonatomic) int displayMode;                            //@synthesize displayMode=_displayMode - In the implementation block
+(float)measuredHeightWithDisplayMode:(int)arg1 ;
+(float)preferredHeight;
-(UILabel *)detailLineOneLabel;
-(HKActivityRingView *)ringView;
-(UILabel *)detailLineTwoLabel;
-(void)setFitnessFriend:(id)arg1 snapshot:(id)arg2 animated:(char)arg3 ;
-(float)_lastBaseline;
-(void)setRingView:(HKActivityRingView *)arg1 ;
-(void)setDetailLineOneLabel:(UILabel *)arg1 ;
-(void)setDetailLineTwoLabel:(UILabel *)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
-(void)_systemTextSizeChanged;
-(int)displayMode;
-(void)setDisplayMode:(int)arg1 ;
-(void)_setupCell;
@end

