/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:24 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Fitness.app/Fitness
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol _HKAnchoredObjectQueryObserver, OS_dispatch_queue;
@class HKHealthStore, _HKAnchoredObjectQueryManager, HKSortedSampleArray, NSMutableSet, NSArray, NSMutableDictionary, NSMutableArray, HKAnchoredObjectQuery, NSCalendar, NSObject, NSDictionary, CHWorkoutTypeKey;

@interface CHWorkoutsListDataProvider : NSObject {

	HKHealthStore* _healthStore;
	_HKAnchoredObjectQueryManager* _queryManager;
	id<_HKAnchoredObjectQueryObserver> _queryObserver;
	HKSortedSampleArray* _workouts;
	NSMutableSet* _activitySummaries;
	NSArray* _sortedSummaries;
	NSMutableDictionary* _workoutsByMonthAndYear;
	NSMutableDictionary* _workoutsByDay;
	NSMutableDictionary* _workoutStatisticsForMonthAndYear;
	NSMutableDictionary* _workoutStatisticsForYear;
	NSMutableArray* _sortedDateComponentKeys;
	NSMutableArray* _sortedYearDateComponents;
	NSMutableDictionary* _dateComponentsByYear;
	NSMutableDictionary* _workoutCountByTypeIdentifier;
	NSMutableArray* _updateHandlers;
	NSMutableArray* _animatedUpdateHandlers;
	NSMutableArray* _filterActionStartedHandlers;
	NSMutableArray* _filterActionEndedHandlers;
	HKAnchoredObjectQuery* _currentAnchoredObjectQuery;
	NSCalendar* _gregorianCalendar;
	NSCalendar* _currentCalendar;
	NSObject*<OS_dispatch_queue> _sortingQueue;
	char _dataAvailable;
	NSDictionary* _localizedWorkoutTypeNamesByTypeIdentifier;
	NSArray* _sortedTypeIdentifiers;
	CHWorkoutTypeKey* _currentFilteredTypeIdentifier;

}

@property (nonatomic,retain) NSDictionary * localizedWorkoutTypeNamesByTypeIdentifier;              //@synthesize localizedWorkoutTypeNamesByTypeIdentifier=_localizedWorkoutTypeNamesByTypeIdentifier - In the implementation block
@property (nonatomic,retain) NSArray * sortedTypeIdentifiers;                                       //@synthesize sortedTypeIdentifiers=_sortedTypeIdentifiers - In the implementation block
@property (nonatomic,readonly) NSDictionary * workoutsByMonthAndYear; 
@property (nonatomic,readonly) NSDictionary * workoutsByDay;                                        //@synthesize workoutsByDay=_workoutsByDay - In the implementation block
@property (nonatomic,readonly) NSDictionary * workoutStatisticsForMonthAndYear; 
@property (nonatomic,readonly) NSDictionary * workoutStatisticsForYear;                             //@synthesize workoutStatisticsForYear=_workoutStatisticsForYear - In the implementation block
@property (nonatomic,readonly) NSArray * sortedDateComponentKeys; 
@property (nonatomic,readonly) NSArray * sortedYearDateComponents;                                  //@synthesize sortedYearDateComponents=_sortedYearDateComponents - In the implementation block
@property (nonatomic,readonly) NSDictionary * dateComponentsByYear;                                 //@synthesize dateComponentsByYear=_dateComponentsByYear - In the implementation block
@property (nonatomic,readonly) char hasWorkouts; 
@property (nonatomic,retain) CHWorkoutTypeKey * currentFilteredTypeIdentifier;                      //@synthesize currentFilteredTypeIdentifier=_currentFilteredTypeIdentifier - In the implementation block
@property (getter=isCurrentFilterValid,nonatomic,readonly) char currentFilterValid; 
@property (assign,nonatomic) char dataAvailable;                                                    //@synthesize dataAvailable=_dataAvailable - In the implementation block
-(char)dataAvailable;
-(void)addFilterActionFinishedHandler:(/*^block*/id)arg1 ;
-(NSArray *)sortedYearDateComponents;
-(NSDictionary *)dateComponentsByYear;
-(CHWorkoutTypeKey *)currentFilteredTypeIdentifier;
-(NSDictionary *)workoutStatisticsForYear;
-(NSArray *)sortedDateComponentKeys;
-(NSDictionary *)workoutStatisticsForMonthAndYear;
-(void)addAnimatedUpdateHandler:(/*^block*/id)arg1 ;
-(NSArray *)sortedTypeIdentifiers;
-(NSDictionary *)localizedWorkoutTypeNamesByTypeIdentifier;
-(void)setCurrentFilteredTypeIdentifier:(CHWorkoutTypeKey *)arg1 ;
-(id)initWithHealthStore:(id)arg1 queryManager:(id)arg2 ;
-(void)startFetching;
-(NSDictionary *)workoutsByMonthAndYear;
-(id)activitySummariesForWorkout:(id)arg1 ;
-(void)deleteWorkout:(id)arg1 shouldDeleteAssociatedSamples:(char)arg2 completion:(/*^block*/id)arg3 ;
-(void)_fetchInitialWorkouts;
-(void)setCurrentFilteredTypeIdentifier:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_runFilterActionStartedHandlers;
-(void)_queue_sortAllWorkoutsByMonthAndYearWithCurrentFilter;
-(void)_runFilterActionFinishedHandlers;
-(id)_watchWorkoutsPredicate;
-(id)_queue_fetchInitialWorkoutsReturningQueryAnchor:(id*)arg1 ;
-(void)_handleFetchedResults:(id)arg1 ;
-(void)_queue_runAnchoredObjectQueryWithLastAnchor:(id)arg1 ;
-(id)_phoneWorkoutsPredicate;
-(void)_queryWorkoutWithWatchPredicate:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_fetchActivitySummariesForWorkouts:(id)arg1 ;
-(void)_recreateFilterObjects;
-(char)isCurrentFilterValid;
-(void)_runAnimatedUpdateHandlers;
-(void)_handleNewActivitySummaries:(id)arg1 ;
-(void)_countWorkouts;
-(void)setSortedTypeIdentifiers:(NSArray *)arg1 ;
-(void)setLocalizedWorkoutTypeNamesByTypeIdentifier:(NSDictionary *)arg1 ;
-(void)cancelAllFetches;
-(void)addFilterActionStartedHandler:(/*^block*/id)arg1 ;
-(id)_UUIDsForWorkoutsWithEndDate:(id)arg1 ;
-(char)isWatchWorkout:(id)arg1 ;
-(NSDictionary *)workoutsByDay;
-(id)init;
-(void)dealloc;
-(void)_calculateStatistics;
-(void)_commonInit;
-(void)setDataAvailable:(char)arg1 ;
-(void)_runUpdateHandlers;
-(void)_handleRemovedObjects:(id)arg1 ;
-(char)hasWorkouts;
-(void)addUpdateHandler:(/*^block*/id)arg1 ;
-(void)_timeZoneDidChange:(id)arg1 ;
@end

