/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:43 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol BrowseItemViewDelegate <NSObject>
@required
-(void)browseItemViewTouched:(id)arg1;
-(void)browseItemViewAnimationCompleted:(id)arg1 pushed:(char)arg2;

@end

