/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:44 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/CarMapsSuggestionsObserver.h>

@class NSString;

@interface CarMapsSuggestionsObserver_RouteGenius : NSObject <CarMapsSuggestionsObserver> {

	char _active;

}

@property (assign,nonatomic) char active;                           //@synthesize active=_active - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign) char allowLowFuelSuggestion; 
-(void)carMapsSuggestionControllerDidRefresh:(id)arg1 ;
-(char)active;
-(void)setActive:(char)arg1 ;
@end

