/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:35 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol CarMapSettingsDelegate <NSObject>
@optional
-(char)mapSettings:(id)arg1 shouldApplyAnimated:(char*)arg2;
-(void)mapSettings:(id)arg1 willApplyAnimated:(char)arg2;
-(void)mapSettings:(id)arg1 didApplyAnimated:(char)arg2;

@end

