/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:38 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <UIKit/UIView.h>

@class UIActivityIndicatorView, UILabel, UIView, MapsAutoLayoutContext;

@interface CarReroutingGuidanceSign : UIView {

	UIActivityIndicatorView* _activityIndicator;
	UILabel* _reroutingLabel;
	UILabel* _messageLabel;
	UIView* _container;
	MapsAutoLayoutContext* _layoutContext;
	char _showsDataConnectionMessage;

}

@property (assign,nonatomic) char showsDataConnectionMessage;              //@synthesize showsDataConnectionMessage=_showsDataConnectionMessage - In the implementation block
-(void)setShowsDataConnectionMessage:(char)arg1 ;
-(void)setShowsDataConnectionMessage:(char)arg1 animated:(char)arg2 ;
-(char)showsDataConnectionMessage;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)updateConstraints;
-(void)_updateStyling;
@end

