/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:36 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray, NSMapTable;

@interface ContainerStack : NSObject {

	NSMutableArray* _array;
	NSMapTable* _content;

}
-(unsigned)indexOfContainee:(id)arg1 ;
-(id)containeeStateAtIndex:(unsigned)arg1 ;
-(id)containeeStateForContainee:(id)arg1 ;
-(void)pushContaineeState:(id)arg1 ;
-(void)removeContaineeState:(id)arg1 ;
-(void)replaceLastOne:(id)arg1 ;
-(id)popFromIndex:(unsigned)arg1 ;
-(id)lastState;
-(id)init;
-(id)description;
-(id)allObjects;
@end

