/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:33 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Maps/Maps-Structs.h>
@interface CustomLocationManager : NSObject {

	CFDictionaryRef _reverseGeocodeRequestsForSearchResults;

}
+(id)sharedManager;
-(void)processSearchResult:(id)arg1 traits:(id)arg2 ;
-(void)processSearchResults:(id)arg1 traits:(id)arg2 ;
-(void)cancelProcessingSearchResult:(id)arg1 ;
-(id)init;
-(void)dealloc;
@end

