/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:38 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol CustomSearchManagerObserver <NSObject>
@required
-(void)customSearchManager:(id)arg1 didReplaceCustomSearchResult:(id)arg2 animated:(char)arg3 shouldSelectOnMap:(char)arg4 context:(id)arg5;
-(void)customSearchManager:(id)arg1 didModifyCustomSearchResult:(id)arg2 coordinateChanged:(char)arg3;

@end

