/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:43 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Maps/Maps-Structs.h>
@interface DataActivationPopupAssertion : NSObject {

	CTServerConnectionRef _telephonyServerConnection;
	void* _dataActivationPopupAssertion;
	char _active;

}
-(id)initAndTakeAssertion:(char)arg1 ;
-(void)_takeAssertion;
-(id)init;
-(void)invalidate;
-(void)dealloc;
-(void)_releaseAssertion;
@end

