/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:37 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol DataSourceDelegate <UIScrollViewDelegate>
@optional
-(void)dataSource:(id)arg1 searchResultNeedsEditing:(id)arg2 completion:(/*^block*/id)arg3;
-(int)listForDataSource:(id)arg1;

@required
-(void)dataSource:(id)arg1 itemTapped:(id)arg2;
-(void)dataSourceUpdated:(id)arg1;

@end

