/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:47 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MapKit/MKAnnotationView.h>

@class DebugLocationAnnotation, UIView, UIImageView;

@interface DebugLocationAnnotationView : MKAnnotationView {

	DebugLocationAnnotation* _debugLocationAnnotation;
	UIView* _circleView;
	UIView* _outerCircleView;
	UIImageView* _courseImageView;

}

@property (nonatomic,retain) DebugLocationAnnotation * debugLocationAnnotation;              //@synthesize debugLocationAnnotation=_debugLocationAnnotation - In the implementation block
-(void)_updateFillColor;
-(void)_updateCourse;
-(void)_updateAccuracy;
-(id)initWithAnnotation:(id)arg1 debugLocationAnnotation:(id)arg2 reuseIdentifier:(id)arg3 ;
-(void)setDebugLocationAnnotation:(DebugLocationAnnotation *)arg1 ;
-(DebugLocationAnnotation *)debugLocationAnnotation;
-(void)_setMapRotationRadians:(float)arg1 ;
-(void)_setMapPitchRadians:(float)arg1 ;
@end

