/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:48 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Maps/Maps-Structs.h>
@class NSString, SearchResult, AddressBookAddress, MKLocalSearchCompletion, MKMapItem;

@interface DirectionsWaypoint : NSObject {

	NSString* _requestSearchString;
	SearchResult* _requestSearch;
	AddressBookAddress* _requestAddress;
	NSString* _suggestionsPrefix;
	SearchResult* _responseSearch;
	MKLocalSearchCompletion* _completion;

}

@property (nonatomic,retain) NSString * requestSearchString;                    //@synthesize requestSearchString=_requestSearchString - In the implementation block
@property (nonatomic,retain) SearchResult * requestSearch;                      //@synthesize requestSearch=_requestSearch - In the implementation block
@property (nonatomic,retain) AddressBookAddress * requestAddress;               //@synthesize requestAddress=_requestAddress - In the implementation block
@property (nonatomic,retain) NSString * suggestionsPrefix;                      //@synthesize suggestionsPrefix=_suggestionsPrefix - In the implementation block
@property (nonatomic,retain) SearchResult * responseSearch;                     //@synthesize responseSearch=_responseSearch - In the implementation block
@property (nonatomic,retain) MKLocalSearchCompletion * completion;              //@synthesize completion=_completion - In the implementation block
@property (nonatomic,readonly) MKMapItem * mapItemIfLoaded; 
@property (nonatomic,readonly) CLLocationCoordinate2D coordinate; 
-(char)isDynamicCurrentLocation;
-(void)updateCoordinate:(CLLocationCoordinate2D)arg1 ;
-(void)updateFromGEOComposedWaypoint:(id)arg1 ;
-(void)setResponseSearch:(SearchResult *)arg1 ;
-(char)containsSearchResult:(id)arg1 ;
-(MKMapItem *)mapItemIfLoaded;
-(NSString *)requestSearchString;
-(void)setRequestSearchString:(NSString *)arg1 ;
-(void)setRequestSearch:(SearchResult *)arg1 ;
-(AddressBookAddress *)requestAddress;
-(void)setRequestAddress:(AddressBookAddress *)arg1 ;
-(SearchResult *)responseSearch;
-(SCD_Struct_RA12)bounds;
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(char)isValid;
-(MKLocalSearchCompletion *)completion;
-(void)setCompletion:(MKLocalSearchCompletion *)arg1 ;
-(id)location;
-(NSString *)suggestionsPrefix;
-(void)setSuggestionsPrefix:(NSString *)arg1 ;
-(SearchResult *)requestSearch;
-(id)pin;
-(id)singleLineAddress;
-(CLLocationCoordinate2D)coordinate;
@end

