/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:38 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Maps/Maps-Structs.h>
@class MKMapView, SearchPinsManager, VKPolylineGroupOverlay, VKPolylineGroupOverlayPainter, VKPolylineOverlay, NSArray, Route;

@interface DirectionsAnnotationsManager : NSObject {

	MKMapView* _mapView;
	SearchPinsManager* _searchPinsManager;
	VKPolylineGroupOverlay* _routesOverlay;
	VKPolylineGroupOverlayPainter* _routesOverlayPainter;
	VKPolylineOverlay* _navigationRouteOverlay;
	VKPolylineOverlay* _navigationAlternateRouteOverlay;
	NSArray* _routeOverlays;
	NSArray* _routes;
	unsigned _selectedRouteIndex;
	char _alternateRoutesEnabled;
	Route* _navigationRoute;
	Route* _navigationAlternateRoute;
	char _showingNavigationRoute;
	char _tapRouteToSelectEnabled;
	char _routesWereDistinguishable;
	char _isAnimating;
	char _showingDirections;
	char _showingAlternateRoutes;
	char _showingAlternateRouteAnnotations;
	char _alternateRouteAnnotationsEnabled;
	char _selectPolyline;

}

@property (nonatomic,retain) VKPolylineGroupOverlay * routesOverlay;                                       //@synthesize routesOverlay=_routesOverlay - In the implementation block
@property (nonatomic,retain) VKPolylineGroupOverlayPainter * routesOverlayPainter;                         //@synthesize routesOverlayPainter=_routesOverlayPainter - In the implementation block
@property (nonatomic,retain) MKMapView * mapView;                                                          //@synthesize mapView=_mapView - In the implementation block
@property (nonatomic,retain) SearchPinsManager * searchPinsManager;                                        //@synthesize searchPinsManager=_searchPinsManager - In the implementation block
@property (assign,nonatomic) char showingDirections;                                                       //@synthesize showingDirections=_showingDirections - In the implementation block
@property (nonatomic,retain) NSArray * routes;                                                             //@synthesize routes=_routes - In the implementation block
@property (assign,nonatomic) unsigned selectedRouteIndex;                                                  //@synthesize selectedRouteIndex=_selectedRouteIndex - In the implementation block
@property (assign,nonatomic) char alternateRoutesEnabled;                                                  //@synthesize alternateRoutesEnabled=_alternateRoutesEnabled - In the implementation block
@property (assign,nonatomic) char alternateRouteAnnotationsEnabled;                                        //@synthesize alternateRouteAnnotationsEnabled=_alternateRouteAnnotationsEnabled - In the implementation block
@property (assign,getter=selectsPolyline,nonatomic) char selectPolyline;                                   //@synthesize selectPolyline=_selectPolyline - In the implementation block
@property (nonatomic,retain) Route * navigationRoute;                                                      //@synthesize navigationRoute=_navigationRoute - In the implementation block
@property (assign,nonatomic) char showingNavigationRoute;                                                  //@synthesize showingNavigationRoute=_showingNavigationRoute - In the implementation block
@property (nonatomic,retain) Route * navigationAlternateRoute;                                             //@synthesize navigationAlternateRoute=_navigationAlternateRoute - In the implementation block
@property (getter=isTapRouteToSelectEnabled,nonatomic,readonly) char tapRouteToSelectEnabled;              //@synthesize tapRouteToSelectEnabled=_tapRouteToSelectEnabled - In the implementation block
+(id)displayableRoutesForRoutesArray:(id)arg1 selectedRoute:(id)arg2 ;
-(SearchPinsManager *)searchPinsManager;
-(void)setSearchPinsManager:(SearchPinsManager *)arg1 ;
-(id)_selectedRoute;
-(void)_eraseRoute:(id)arg1 ;
-(void)_drawRoute:(id)arg1 ;
-(void)_updateRouteTrafficIncidents;
-(void)updateRouteTrafficIncidents;
-(void)updateMatchedLocation:(id)arg1 ;
-(VKPolylineGroupOverlay *)routesOverlay;
-(VKPolylineGroupOverlayPainter *)routesOverlayPainter;
-(id)_selectedPolylineRoute;
-(id)_selectedRouteOverlay;
-(id)_selectedPolylineRouteOverlay;
-(id)selectedRoutePainter;
-(void)_updateAlternateRoutesAnimated:(char)arg1 ;
-(void)_updateAlternateRoutesAnimated:(char)arg1 forceUpdate:(char)arg2 ;
-(char)_shouldShowAlternateRoutes;
-(void)_updateRouteAnnotationsAnimated:(char)arg1 ;
-(void)_updateRouteAnnotationsAnimated:(char)arg1 forceUpdate:(char)arg2 ;
-(id)_drivingRouteEquivalentToWalkingRoute;
-(id)titleForAllRoutes;
-(void)setShowingDirections:(char)arg1 ;
-(void)setSelectPolyline:(char)arg1 ;
-(void)_updateSelectedRouteFromRouteIndexWithPreviousSelectedRoute:(id)arg1 ;
-(void)setAlternateRoutesEnabled:(char)arg1 ;
-(void)setAlternateRouteAnnotationsEnabled:(char)arg1 ;
-(void)setRoutes:(id)arg1 selectedRouteIndex:(unsigned)arg2 ;
-(void)updateRouteOverlayForRouteIndex:(unsigned)arg1 ;
-(void)setShowingDirections:(char)arg1 animated:(char)arg2 ;
-(void)setAlternateRoutesEnabled:(char)arg1 animated:(char)arg2 ;
-(void)setShowingNavigationRoute:(char)arg1 ;
-(void)updateNavigationRouteOverlay;
-(void)setNavigationRoute:(Route *)arg1 ;
-(void)setNavigationAlternateRoute:(Route *)arg1 ;
-(void)setNavigationAlternateRouteSelected:(char)arg1 ;
-(void)updateAlternateRouteAnnotationMarkers;
-(void)goToRouteRemainingAtLocation:(id)arg1 animated:(char)arg2 completion:(/*^block*/id)arg3 ;
-(SCD_Struct_RA12)_mapRectForRouteRemainingAtLocationWithMainScreenPadding:(id)arg1 ;
-(SCD_Struct_RA12)mapRectForRouteRemainingAtLocation:(id)arg1 ;
-(char)showingDirections;
-(char)alternateRoutesEnabled;
-(char)alternateRouteAnnotationsEnabled;
-(char)selectsPolyline;
-(Route *)navigationRoute;
-(char)showingNavigationRoute;
-(Route *)navigationAlternateRoute;
-(char)isTapRouteToSelectEnabled;
-(void)setRoutesOverlay:(VKPolylineGroupOverlay *)arg1 ;
-(void)setRoutesOverlayPainter:(VKPolylineGroupOverlayPainter *)arg1 ;
-(id)_routeadditions_annotationForRoute:(id)arg1 ;
-(void)_minimizeOverlapOfRouteAnnotationViewsWithContentBounds:(CGRect)arg1 ;
-(float)_areaOverlapOfRouteAnnotationRepresentation:(id)arg1 withAnnotationRepresentationToAvoid:(id)arg2 inOrientation:(int)arg3 ;
-(id)_acceptableOrientationsForRouteAnnotationRepresentation:(id)arg1 withAnnotationRepresentationToAvoid:(id)arg2 ;
-(NSArray*)_findOptimalPlacementForProblem:(id)arg1 ;
-(id)_routeadditions_routeForAnnotation:(id)arg1 ;
-(void)updateAlternateRouteAnnotationsWithContentBounds:(CGRect)arg1 ;
-(id)_acceptableOrientationsForRouteAnnotationRepresentation:(id)arg1 withAnnotationRepresentationsToAvoid:(id)arg2 ;
-(id)_acceptableOrientationsForRouteAnnotationRepresentation:(id)arg1 fromOrientations:(id)arg2 withStaticRouteAnnotationRepresentation:(id)arg3 inOrientation:(id)arg4 ;
-(id)init;
-(void)clearRoutes;
-(void)setSelectedRouteIndex:(unsigned)arg1 ;
-(NSArray *)routes;
-(void)setRoutes:(NSArray *)arg1 ;
-(unsigned)selectedRouteIndex;
-(id)mapView:(id)arg1 painterForVectorOverlay:(id)arg2 ;
-(void)setMapView:(MKMapView *)arg1 ;
-(id)mapView:(id)arg1 viewForAnnotation:(id)arg2 ;
-(MKMapView *)mapView;
@end

