/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:40 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/SearchResultMapItemBase.h>
#import <Maps/PersonalizedAutocompleteItem.h>

@class NSArray, DroppedPinMapItemKey;

@interface DroppedPinMapItem : SearchResultMapItemBase <PersonalizedAutocompleteItem> {

	NSArray* _autocompletionStrings;
	DroppedPinMapItemKey* _droppedPinKey;

}

@property (nonatomic,readonly) int autocompleteCategoryPriority; 
@property (nonatomic,readonly) int autocompleteOrder; 
@property (nonatomic,readonly) id autocompleteObject; 
@property (nonatomic,readonly) NSArray * autocompletionStrings; 
-(int)autocompleteCategoryPriority;
-(int)autocompleteOrder;
-(id)autocompleteObject;
-(NSArray *)autocompletionStrings;
-(id)title;
-(id)keys;
-(id)styleAttributes;
-(id)initWithSearchResult:(id)arg1 ;
@end

