/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:34 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/MapsDebugValuesViewController.h>
#import <libobjc.A.dylib/GEOExperimentConfigurationObserver.h>

@class NSString;

@interface ExperimentsDebugController : MapsDebugValuesViewController <GEOExperimentConfigurationObserver>

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)navigationDestinationTitle;
-(void)prepareContent;
-(void)dealloc;
-(void)experimentConfigurationDidChange:(id)arg1 ;
@end

