/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:32 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <UIKit/UIView.h>

@class UIStackView, ExtensionsActionView, NSString;

@interface ExtensionsActionsFooterView : UIView {

	UIStackView* _stackView;
	ExtensionsActionView* _openAppView;

}

@property (copy) NSString * openAppButtonTitle; 
@property (copy) id didTapOpenAppButton; 
-(NSString *)openAppButtonTitle;
-(void)setOpenAppButtonTitle:(NSString *)arg1 ;
-(id)didTapOpenAppButton;
-(void)setDidTapOpenAppButton:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)setActions:(id)arg1 ;
-(void)_commonInit;
@end

