/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:43 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Maps/Maps-Structs.h>
@class NSString;

@interface ExternalURLQuery : NSObject {

	NSString* _query;
	int _resultProviderId;
	NSString* _contentProvider;
	unsigned long long _muid;
	CLLocationCoordinate2D _coordinate;

}

@property (nonatomic,copy,readonly) NSString * query;                          //@synthesize query=_query - In the implementation block
@property (nonatomic,readonly) CLLocationCoordinate2D coordinate;              //@synthesize coordinate=_coordinate - In the implementation block
@property (nonatomic,readonly) unsigned long long muid;                        //@synthesize muid=_muid - In the implementation block
@property (nonatomic,readonly) int resultProviderId;                           //@synthesize resultProviderId=_resultProviderId - In the implementation block
@property (nonatomic,copy,readonly) NSString * contentProvider;                //@synthesize contentProvider=_contentProvider - In the implementation block
-(id)initWithQuery:(id)arg1 coordinate:(CLLocationCoordinate2D)arg2 muid:(unsigned long long)arg3 resultProviderId:(int)arg4 contentProvider:(id)arg5 ;
-(char)isEqualToExternalURLQuery:(id)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(NSString *)query;
-(unsigned long long)muid;
-(int)resultProviderId;
-(NSString *)contentProvider;
-(CLLocationCoordinate2D)coordinate;
@end

