/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:41 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewController.h>
#import <libobjc.A.dylib/MFMailComposeViewControllerDelegate.h>

@class NSDictionary, UISlider, GEORequestCounter, NSString;

@interface GeoRequestCounterTableViewController : UITableViewController <MFMailComposeViewControllerDelegate> {

	char _isLoggingEnabled;
	NSDictionary* _appRequestDict;
	UISlider* _timeSlider;
	GEORequestCounter* _reqCounter;

}

@property (assign,nonatomic) char isLoggingEnabled;                       //@synthesize isLoggingEnabled=_isLoggingEnabled - In the implementation block
@property (nonatomic,retain) GEORequestCounter * reqCounter;              //@synthesize reqCounter=_reqCounter - In the implementation block
@property (nonatomic,retain) NSDictionary * appRequestDict;               //@synthesize appRequestDict=_appRequestDict - In the implementation block
@property (nonatomic,retain) UISlider * timeSlider;                       //@synthesize timeSlider=_timeSlider - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)showActionSheet;
-(UISlider *)timeSlider;
-(GEORequestCounter *)reqCounter;
-(NSDictionary *)appRequestDict;
-(void)_toggleLogging;
-(void)_resetLogs;
-(void)sliderAction:(id)arg1 ;
-(id)stringForSliderValue:(int)arg1 ;
-(id)getSinceDate:(int)arg1 ;
-(int)getTotalRequestCountFor:(id)arg1 ;
-(int)getTotalRequestCountForAllApps;
-(id)logFileName;
-(void)saveToLogFileWithName:(id)arg1 ;
-(void)sendEmailWithLogAttachement;
-(void)setAppRequestDict:(NSDictionary *)arg1 ;
-(void)setTimeSlider:(UISlider *)arg1 ;
-(void)setReqCounter:(GEORequestCounter *)arg1 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2 ;
-(void)didReceiveMemoryWarning;
-(void)viewDidLoad;
-(void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3 ;
-(char)isLoggingEnabled;
-(void)setIsLoggingEnabled:(char)arg1 ;
@end

