/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:41 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewController.h>

@class GEORequestCounterInfo;

@interface GeoRequestDetailTableViewController : UITableViewController {

	GEORequestCounterInfo* _counterInfo;

}

@property (nonatomic,retain) GEORequestCounterInfo * counterInfo;              //@synthesize counterInfo=_counterInfo - In the implementation block
-(id)initWithGEORequestCounterInfo:(id)arg1 ;
-(void)setCounterInfo:(GEORequestCounterInfo *)arg1 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2 ;
-(void)didReceiveMemoryWarning;
-(void)viewDidLoad;
-(GEORequestCounterInfo *)counterInfo;
@end

