/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:36 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol GuidanceDisplay <NSObject>
@property (assign,getter=isGuidanceEnabled,nonatomic) char guidanceEnabled; 
@optional
-(void)showRecalculationFailed;
-(void)hideRecalculating;
-(void)willStartNavigation;
-(void)willEndNavigation;
-(void)setGuidanceEnabled:(char)arg1 animated:(char)arg2;
-(void)setGuidanceEnabled:(char)arg1;
-(void)setCurrentRoadDescriptionIsUnreliable:(char)arg1;
-(void)willResumeNavigation;
-(char)isGuidanceEnabled;
-(void)didStartNavigation;
-(void)didReroute;
-(void)willPauseNavigation;

@required
-(void)showNoGuidance;
-(void)showArrived;
-(void)showRecalculating;
-(void)showProceedingToRouteDistance:(double)arg1 displayString:(id)arg2 forStep:(id)arg3;
-(void)setDestinationDisplayName:(id)arg1;
-(void)setETA:(id)arg1;
-(void)showNewManeuver:(int)arg1 junction:(id)arg2 instructions:(id)arg3 shieldType:(int)arg4 shieldText:(id)arg5 drivingSide:(int)arg6 maneuverStepIndex:(unsigned)arg7;
-(void)showManeuverAlertForAnnouncementStage:(unsigned)arg1;
-(void)setTimeToManeuver:(double)arg1 distanceToManeuver:(double)arg2 forStep:(id)arg3 atStepIndex:(unsigned)arg4;
-(void)showSecondaryManeuver:(int)arg1 junction:(id)arg2 instructions:(id)arg3 shieldType:(int)arg4 shieldText:(id)arg5 drivingSide:(int)arg6;
-(void)hideSecondaryManeuver;

@end

