/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:36 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MapsActivityViewControllerDelegate <NSObject>
@optional
-(void)mapsActivityViewControllerPrint:(id)arg1;
-(void)mapsActivityViewControllerPresentRoutingApps:(id)arg1;
-(void)mapsActivityViewController:(id)arg1 activityCompleted:(char)arg2;

@required
-(id)mapsActivityMapView;

@end

