/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:43 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/MNTraceBookmarkSelectorDelegate.h>
#import <Maps/TraceControlViewDelegate.h>
#import <libobjc.A.dylib/MNTracePlayerObserver.h>
#import <libobjc.A.dylib/MNNavigationServiceObserver.h>
#import <Maps/TraceSliderViewDelegate.h>
#import <Maps/NavTestLoggerDelegate.h>
#import <Maps/NavigationCameraSnapshotPickerDelegate.h>
#import <UIKit/UIGestureRecognizerDelegate.h>
#import <UIKit/UISplitViewControllerDelegate.h>

@protocol NavigationDebugViewsControllerDelegate;
@class MNTracePlayer, NSTimer, TraceControlView, TraceSliderView, UIView, TraceBookmarkSelector, UITapGestureRecognizer, UILongPressGestureRecognizer, MKMapView, MNTrace, MNTraceBookmarkRecorder, NavigationCameraSnapshotPickerViewController, NavigationDebugSplitViewController, UIWindow, UINavigationController, UIViewController, MNLocation, NSString;

@interface NavigationDebugViewsController : NSObject <MNTraceBookmarkSelectorDelegate, TraceControlViewDelegate, MNTracePlayerObserver, MNNavigationServiceObserver, TraceSliderViewDelegate, NavTestLoggerDelegate, NavigationCameraSnapshotPickerDelegate, UIGestureRecognizerDelegate, UISplitViewControllerDelegate> {

	id<NavigationDebugViewsControllerDelegate> _delegate;
	MNTracePlayer* _tracePlayer;
	NSTimer* _hideTraceControlTimer;
	TraceControlView* _traceControlView;
	TraceSliderView* _traceSliderView;
	UIView* _debugControlsView;
	TraceBookmarkSelector* _traceBookmarkSelector;
	char _shouldResumeTracePlayer;
	UITapGestureRecognizer* _oldBookmarkGestureRecognizer;
	UILongPressGestureRecognizer* _bookmarkGestureRecognizer;
	MKMapView* _mapView;
	char _traceControlsAreShowing;
	char _debugViewsWereAdded;
	char _showTraceControlsForStaleLocations;
	MNTrace* _trace;
	MNTraceBookmarkRecorder* _bookmarkRecorder;
	NavigationCameraSnapshotPickerViewController* _cameraSnapshotPickerVC;
	NavigationDebugSplitViewController* _splitViewController;
	UIWindow* _window;
	UINavigationController* _nonsplitRootViewController;
	UIViewController* _mainViewController;
	UIViewController* _modalPresentingViewController;
	char _isPresentingModallyPickerVC;
	UINavigationController* _modalCameraSnapshotPickerVC;
	char _shouldUpdateLocationPuck;
	MNLocation* _puckLocation;
	char _automaticallyHideTraceControls;

}

@property (nonatomic,retain) UIView * debugControlsView;                           //@synthesize debugControlsView=_debugControlsView - In the implementation block
@property (nonatomic,retain) MKMapView * mapView;                                  //@synthesize mapView=_mapView - In the implementation block
@property (nonatomic,retain) NSTimer * hideTraceControlTimer;                      //@synthesize hideTraceControlTimer=_hideTraceControlTimer - In the implementation block
@property (assign,nonatomic) char automaticallyHideTraceControls;                  //@synthesize automaticallyHideTraceControls=_automaticallyHideTraceControls - In the implementation block
@property (assign,nonatomic) char showTraceControlsForStaleLocations;              //@synthesize showTraceControlsForStaleLocations=_showTraceControlsForStaleLocations - In the implementation block
@property (nonatomic,readonly) char isShowingTraceControls;                        //@synthesize traceControlsAreShowing=_traceControlsAreShowing - In the implementation block
@property (nonatomic,readonly) MNTracePlayer * tracePlayer; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)cameraSnapshotPicker:(id)arg1 didSelectCameraSnapshot:(id)arg2 ;
-(void)testLoggerDidFailToLog:(id)arg1 ;
-(void)traceSliderViewEditingDidBegin:(id)arg1 ;
-(void)traceSliderView:(id)arg1 editingEndedAtTime:(double)arg2 ;
-(void)traceSliderViewCancelledEditing:(id)arg1 ;
-(void)traceControlView:(id)arg1 setPlaying:(char)arg2 ;
-(void)traceControlViewJumpedBack:(id)arg1 ;
-(void)traceControlView:(id)arg1 setPlaySpeed:(double)arg2 ;
-(void)traceControlViewPressedBookmarksButton:(id)arg1 ;
-(void)traceControlViewPressedStartLoggingButton:(id)arg1 ;
-(void)traceControlViewPressedEndLoggingButton:(id)arg1 ;
-(void)traceControlViewPressedSaveCameraSnapshotButton:(id)arg1 ;
-(void)traceControlViewPressedViewCameraSnapshotsButton:(id)arg1 ;
-(void)traceBookmarkSelector:(id)arg1 choseGuideMeBookmark:(id)arg2 ;
-(void)prepareToRunNavigation;
-(void)showTraceControls;
-(void)resetTracePlayer;
-(void)setAutomaticallyHideTraceControls:(char)arg1 ;
-(void)resetHideTraceControlsTimer;
-(void)hideTraceControls;
-(void)hideTraceControlsAnimated:(char)arg1 ;
-(float)debugViewHeight;
-(UIView *)debugControlsView;
-(void)addDebugViewsToView:(id)arg1 mapView:(id)arg2 modalPresentingViewController:(id)arg3 ;
-(void)addDebugViewsToView:(id)arg1 mapView:(id)arg2 window:(id)arg3 ;
-(void)_addDebugViewsToView:(id)arg1 mapView:(id)arg2 window:(id)arg3 viewController:(id)arg4 ;
-(void)didManuallyAddDebugViews;
-(void)setViewController:(id)arg1 window:(id)arg2 ;
-(void)_setUpCameraSnapshotPickerVCFromViewController:(id)arg1 ;
-(void)_setUpCameraSnapshotPickerVCFromWindow:(id)arg1 ;
-(void)removeDebugViewsFromView:(id)arg1 ;
-(void)didManuallyRemoveDebugViews;
-(void)_longPressBookmarkGesture:(id)arg1 ;
-(void)_threeFingerTapBookmarkGesture:(id)arg1 ;
-(void)_addTraceBookmark;
-(void)_sliderDidEndEditing;
-(void)toggleCameraSnapshotPickerVisibility;
-(void)_presentCameraSnapshotPickerModallyIfNeededAnimated:(char)arg1 ;
-(void)_dismissModalCameraSnapshotPickerIfNeededAnimated:(char)arg1 ;
-(NSTimer *)hideTraceControlTimer;
-(void)setHideTraceControlTimer:(NSTimer *)arg1 ;
-(char)automaticallyHideTraceControls;
-(char)isShowingTraceControls;
-(char)showTraceControlsForStaleLocations;
-(void)setShowTraceControlsForStaleLocations:(char)arg1 ;
-(void)setDebugControlsView:(UIView *)arg1 ;
-(void)dealloc;
-(id)initWithDelegate:(id)arg1 ;
-(char)splitViewController:(id)arg1 collapseSecondaryViewController:(id)arg2 ontoPrimaryViewController:(id)arg3 ;
-(id)splitViewController:(id)arg1 separateSecondaryViewControllerFromPrimaryViewController:(id)arg2 ;
-(id)primaryViewControllerForCollapsingSplitViewController:(id)arg1 ;
-(id)primaryViewControllerForExpandingSplitViewController:(id)arg1 ;
-(unsigned)splitViewControllerSupportedInterfaceOrientations:(id)arg1 ;
-(void)setMapView:(MKMapView *)arg1 ;
-(MKMapView *)mapView;
-(void)_done;
-(void)tracePlayerDidStart:(id)arg1 ;
-(void)tracePlayerDidStop:(id)arg1 ;
-(void)tracePlayerDidPause:(id)arg1 ;
-(void)tracePlayerDidResume:(id)arg1 ;
-(void)tracePlayer:(id)arg1 didSeekToTransportType:(int)arg2 ;
-(void)tracePlayer:(id)arg1 didSeekToTime:(double)arg2 location:(id)arg3 ;
-(void)tracePlayer:(id)arg1 didPlayAtTime:(double)arg2 ;
-(void)tracePlayer:(id)arg1 didJumpToRouteResponse:(id)arg2 request:(id)arg3 destination:(id)arg4 ;
-(void)tracePlayerDidStayOnRoute:(id)arg1 ;
-(void)tracePlayer:(id)arg1 didUpdateLocation:(id)arg2 ;
-(void)tracePlayer:(id)arg1 didReceiveLocationError:(id)arg2 ;
-(void)tracePlayerDidPauseLocationUpdates:(id)arg1 ;
-(void)tracePlayerDidResumeLocationUpdates:(id)arg1 ;
-(void)tracePlayer:(id)arg1 didUpdateHeading:(id)arg2 ;
-(void)tracePlayer:(id)arg1 didUpdateMotion:(unsigned)arg2 exitType:(unsigned)arg3 confidence:(unsigned)arg4 ;
-(void)tracePlayer:(id)arg1 didUpdateVehicleHeading:(double)arg2 timestamp:(id)arg3 ;
-(void)tracePlayer:(id)arg1 didUpdateVehicleSpeed:(double)arg2 timestamp:(id)arg3 ;
-(MNTracePlayer *)tracePlayer;
-(id)tracePath;
-(void)navigationService:(id)arg1 didRecordTraceBookmarkWithID:(unsigned)arg2 ;
-(void)navigationServiceDidResumeTrace:(id)arg1 ;
-(void)navigationServiceDidPauseTrace:(id)arg1 ;
-(void)navigationService:(id)arg1 didSeekToTracePosition:(double)arg2 ;
-(void)navigationService:(id)arg1 didPlayTracePosition:(double)arg2 ;
-(void)navigationServiceDidFinishLoadingTrace:(id)arg1 ;
@end

