/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:41 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface PersistentAddressBookAddress : PBCodable <NSCopying> {

	double _position;
	int _addressID;
	int _recordID;
	NSString* _syncIdentifier;
	SCD_Struct_RA14 _has;

}

@property (assign,nonatomic) char hasRecordID; 
@property (assign,nonatomic) int recordID;                           //@synthesize recordID=_recordID - In the implementation block
@property (assign,nonatomic) char hasAddressID; 
@property (assign,nonatomic) int addressID;                          //@synthesize addressID=_addressID - In the implementation block
@property (nonatomic,readonly) char hasSyncIdentifier; 
@property (nonatomic,retain) NSString * syncIdentifier;              //@synthesize syncIdentifier=_syncIdentifier - In the implementation block
@property (assign,nonatomic) char hasPosition; 
@property (assign,nonatomic) double position;                        //@synthesize position=_position - In the implementation block
-(void)setSyncIdentifier:(NSString *)arg1 ;
-(char)hasSyncIdentifier;
-(void)setHasAddressID:(char)arg1 ;
-(void)setHasRecordID:(char)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setPosition:(double)arg1 ;
-(double)position;
-(id)dictionaryRepresentation;
-(int)recordID;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(char)hasAddressID;
-(int)addressID;
-(void)setAddressID:(int)arg1 ;
-(char)hasPosition;
-(char)hasRecordID;
-(void)setRecordID:(int)arg1 ;
-(NSString *)syncIdentifier;
-(void)setHasPosition:(char)arg1 ;
@end

