/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:33 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <Maps/RAPQuestion.h>
#import <Maps/RAPMenuItem.h>
#import <Maps/RAPAccessPointQuestion.h>
#import <Maps/RAPPlaceCorrectionsQuestionProtocol.h>

@class RAPPlaceCorrectableString, RAPCommentQuestion, NSString, UIImage;

@interface RAPArrivalEntryPointIncorrectQuestion : RAPQuestion <RAPMenuItem, RAPAccessPointQuestion, RAPPlaceCorrectionsQuestionProtocol> {

	char _showPin;
	RAPCommentQuestion* _commentQuestion;
	unsigned _mapType;
	unsigned _maptype;
	CLLocationCoordinate2D _originalCoordinate;
	CLLocationCoordinate2D _selectedCoordinate;

}

@property (nonatomic,readonly) RAPCommentQuestion * commentQuestion;                     //@synthesize commentQuestion=_commentQuestion - In the implementation block
@property (nonatomic,readonly) SCD_Struct_RA12 visibleMapRect; 
@property (nonatomic,readonly) CLLocationCoordinate2D originalCoordinate;                //@synthesize originalCoordinate=_originalCoordinate - In the implementation block
@property (nonatomic,readonly) unsigned maptype;                                         //@synthesize maptype=_maptype - In the implementation block
@property (nonatomic,readonly) char showPin;                                             //@synthesize showPin=_showPin - In the implementation block
@property (nonatomic,readonly) NSString * localizedCoordinatePickingPrompt; 
@property (nonatomic,readonly) unsigned coordinatePickingMapType; 
@property (assign,nonatomic) CLLocationCoordinate2D selectedCoordinate;                  //@synthesize selectedCoordinate=_selectedCoordinate - In the implementation block
@property (assign,nonatomic) CLLocationCoordinate2D coordinate; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) NSString * localizedTitle; 
@property (nonatomic,readonly) NSString * localizedDescription; 
@property (nonatomic,readonly) UIImage * image; 
@property (nonatomic,readonly) int questionCategory; 
@property (nonatomic,readonly) int userAction; 
@property (nonatomic,readonly) int analyticTarget; 
@property (nonatomic,readonly) int backAction; 
@property (nonatomic,readonly) unsigned mapType;                                         //@synthesize mapType=_mapType - In the implementation block
@property (nonatomic,retain) RAPPlaceCorrectableString * accessPointName; 
@property (getter=isComplete,nonatomic,readonly) char complete; 
-(int)analyticTarget;
-(int)questionCategory;
-(char)_isRecursivelyComplete;
-(void)_fillSubmittableProblem:(id)arg1 ;
-(RAPCommentQuestion *)commentQuestion;
-(NSString *)localizedCoordinatePickingPrompt;
-(CLLocationCoordinate2D)selectedCoordinate;
-(void)setSelectedCoordinate:(CLLocationCoordinate2D)arg1 ;
-(unsigned)coordinatePickingMapType;
-(char)showPin;
-(id)initWithReport:(id)arg1 parentQuestion:(id)arg2 arrivalPoint:(CLLocationCoordinate2D)arg3 ;
-(unsigned)maptype;
-(NSString *)localizedTitle;
-(unsigned)mapType;
-(SCD_Struct_RA12)visibleMapRect;
-(char)isComplete;
-(CLLocationCoordinate2D)originalCoordinate;
-(void)setCoordinate:(CLLocationCoordinate2D)arg1 ;
-(CLLocationCoordinate2D)coordinate;
-(int)userAction;
@end

