/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:43 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/RAPReportComposerTwoLineSnippetTableViewCell.h>

@interface RAPReportComposerPlaceSnippetTableViewCell : RAPReportComposerTwoLineSnippetTableViewCell
-(id)attributedStringFormat;
-(id)defaultReplacementAttributes;
-(void)setContentsFromMapItem:(id)arg1 ;
-(void)setContentsFromMapItem:(id)arg1 isCurrentLocation:(char)arg2 ;
-(void)_setImageForMapItem:(id)arg1 isCurrentLocation:(char)arg2 ;
-(void)_setImageForMapItem:(id)arg1 ;
-(void)_setTransitImageForMapItem:(id)arg1 ;
-(void)_setPlaceName:(id)arg1 singleLineAddress:(id)arg2 ;
-(void)prepareForReuse;
@end

