/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:45 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class UILabel;

@interface RestaurantReservationsChooseOfferCell : UITableViewCell {

	UILabel* _mainLabel;
	UILabel* _subLabel;

}

@property (nonatomic,readonly) UILabel * mainLabel;              //@synthesize mainLabel=_mainLabel - In the implementation block
@property (nonatomic,readonly) UILabel * subLabel;               //@synthesize subLabel=_subLabel - In the implementation block
-(void)initConstraints;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
-(void)awakeFromNib;
-(UILabel *)mainLabel;
-(UILabel *)subLabel;
@end

