/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:43 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/RidesharingCoordination.h>

@class AppCoordinator, RidesharingErrorAlertProvider, UIAlertController, RidesharingContainerViewController, NSString;

@interface RidesharingCoordinator : NSObject <RidesharingCoordination> {

	RidesharingErrorAlertProvider* _errorAlertProvider;
	UIAlertController* _errorAlert;
	AppCoordinator* _appCoordinator;
	RidesharingContainerViewController* _containerViewController;

}

@property (assign,nonatomic,__weak) AppCoordinator * appCoordinator;                                    //@synthesize appCoordinator=_appCoordinator - In the implementation block
@property (nonatomic,retain) RidesharingContainerViewController * containerViewController;              //@synthesize containerViewController=_containerViewController - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(AppCoordinator *)appCoordinator;
-(void)setAppCoordinator:(AppCoordinator *)arg1 ;
-(id)initWithContainerViewController:(id)arg1 ;
-(void)presentDetailsPickingWithProvider:(id)arg1 ;
-(void)presentExpirationAlertControllerWithProvider:(id)arg1 ;
-(void)presentCurrentRideWithProvider:(id)arg1 ;
-(void)viewController:(id)arg1 requestRideWithProvider:(id)arg2 ;
-(void)viewController:(id)arg1 cancelRequest:(id)arg2 ;
-(void)viewController:(id)arg1 contactDriver:(id)arg2 ;
-(void)viewController:(id)arg1 minimizeConfirmation:(id)arg2 ;
-(void)viewControllerRideCompletionAction:(id)arg1 ;
-(void)viewControllerNeedsRebooking:(id)arg1 ;
-(void)viewController:(id)arg1 presentErrorAlertIfNeeded:(id)arg2 ;
-(char)_ridesharingIsCurrentMode;
-(RidesharingContainerViewController *)containerViewController;
-(void)setContainerViewController:(RidesharingContainerViewController *)arg1 ;
@end

