/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:43 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class UIImage;

@interface RidesharingSpecialPricingBadge : NSObject {

	UIImage* _image;

}
-(id)initWithTemplateImage:(id)arg1 ;
-(id)badgeImageWithMaximumDimension:(float)arg1 ;
@end

