/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:38 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/MKMapViewDelegate.h>

@protocol RidesharingCurrentRideProvider;
@class IOSChromeViewController, MKPointAnnotation, NSArray, MKAnnotationView, _MKBalloonAnnotationView, RidesharingBalloonETAView, MKMapView, NSDate, NSString;

@interface RidesharingAnnotationsManager : NSObject <MKMapViewDelegate> {

	char _shouldReframeMapView;
	char _hasConfirmedRide;
	IOSChromeViewController* _chromeViewController;
	MKPointAnnotation* _vehicleAnnotation;
	MKPointAnnotation* _pickupAnnotation;
	MKPointAnnotation* _dropoffAnnotation;
	NSArray* _waypointAnnotations;
	MKAnnotationView* _vehicleAnnotationView;
	_MKBalloonAnnotationView* _pickupAnnotationView;
	_MKBalloonAnnotationView* _dropoffAnnotationView;
	RidesharingBalloonETAView* _ETAView;
	id<RidesharingCurrentRideProvider> _currentRideProvider;
	MKMapView* _mapView;
	NSDate* _lastVehicleLocationUpdateDate;

}

@property (nonatomic,retain) MKAnnotationView * vehicleAnnotationView;                            //@synthesize vehicleAnnotationView=_vehicleAnnotationView - In the implementation block
@property (nonatomic,retain) _MKBalloonAnnotationView * pickupAnnotationView;                     //@synthesize pickupAnnotationView=_pickupAnnotationView - In the implementation block
@property (nonatomic,retain) _MKBalloonAnnotationView * dropoffAnnotationView;                    //@synthesize dropoffAnnotationView=_dropoffAnnotationView - In the implementation block
@property (nonatomic,retain) RidesharingBalloonETAView * ETAView;                                 //@synthesize ETAView=_ETAView - In the implementation block
@property (assign,nonatomic) char hasConfirmedRide;                                               //@synthesize hasConfirmedRide=_hasConfirmedRide - In the implementation block
@property (nonatomic,retain) id<RidesharingCurrentRideProvider> currentRideProvider;              //@synthesize currentRideProvider=_currentRideProvider - In the implementation block
@property (nonatomic,retain) MKMapView * mapView;                                                 //@synthesize mapView=_mapView - In the implementation block
@property (nonatomic,retain) NSDate * lastVehicleLocationUpdateDate;                              //@synthesize lastVehicleLocationUpdateDate=_lastVehicleLocationUpdateDate - In the implementation block
@property (assign,nonatomic,__weak) IOSChromeViewController * chromeViewController;               //@synthesize chromeViewController=_chromeViewController - In the implementation block
@property (nonatomic,retain) MKPointAnnotation * vehicleAnnotation;                               //@synthesize vehicleAnnotation=_vehicleAnnotation - In the implementation block
@property (nonatomic,retain) MKPointAnnotation * pickupAnnotation;                                //@synthesize pickupAnnotation=_pickupAnnotation - In the implementation block
@property (nonatomic,retain) MKPointAnnotation * dropoffAnnotation;                               //@synthesize dropoffAnnotation=_dropoffAnnotation - In the implementation block
@property (nonatomic,retain) NSArray * waypointAnnotations;                                       //@synthesize waypointAnnotations=_waypointAnnotations - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(IOSChromeViewController *)chromeViewController;
-(void)setChromeViewController:(IOSChromeViewController *)arg1 ;
-(id<RidesharingCurrentRideProvider>)currentRideProvider;
-(void)setCurrentRideProvider:(id<RidesharingCurrentRideProvider>)arg1 ;
-(void)addCurrentRideWithProvider:(id)arg1 replaceExisting:(char)arg2 ;
-(void)removeCurrentRide;
-(void)_updateFromCurrentRideProvider:(id)arg1 ;
-(void)setPickupAnnotation:(MKPointAnnotation *)arg1 ;
-(void)setDropoffAnnotation:(MKPointAnnotation *)arg1 ;
-(void)setVehicleAnnotation:(MKPointAnnotation *)arg1 ;
-(void)setWaypointAnnotations:(NSArray *)arg1 ;
-(_MKBalloonAnnotationView *)pickupAnnotationView;
-(_MKBalloonAnnotationView *)dropoffAnnotationView;
-(MKAnnotationView *)vehicleAnnotationView;
-(RidesharingBalloonETAView *)ETAView;
-(MKPointAnnotation *)vehicleAnnotation;
-(MKPointAnnotation *)pickupAnnotation;
-(MKPointAnnotation *)dropoffAnnotation;
-(NSArray *)waypointAnnotations;
-(void)setVehicleAnnotationView:(MKAnnotationView *)arg1 ;
-(void)setPickupAnnotationView:(_MKBalloonAnnotationView *)arg1 ;
-(void)setDropoffAnnotationView:(_MKBalloonAnnotationView *)arg1 ;
-(void)setETAView:(RidesharingBalloonETAView *)arg1 ;
-(char)hasConfirmedRide;
-(void)setHasConfirmedRide:(char)arg1 ;
-(NSDate *)lastVehicleLocationUpdateDate;
-(void)setLastVehicleLocationUpdateDate:(NSDate *)arg1 ;
-(char)mapView:(id)arg1 shouldSelectLabelMarker:(id)arg2 ;
-(void)setMapView:(MKMapView *)arg1 ;
-(id)mapView:(id)arg1 viewForAnnotation:(id)arg2 ;
-(MKMapView *)mapView;
-(id)initWithMapView:(id)arg1 ;
@end

