/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:39 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIAlertController.h>

@protocol RidesharingDetailsPickingProvider;
@interface RidesharingPartySizeSelectionAlertController : UIAlertController {

	id<RidesharingDetailsPickingProvider> _provider;
	/*^block*/id _didFinishSelectingPartySize;

}

@property (nonatomic,copy) id didFinishSelectingPartySize;              //@synthesize didFinishSelectingPartySize=_didFinishSelectingPartySize - In the implementation block
+(id)ridesharingPartySizeSelectionAlertControllerWithProvider:(id)arg1 ;
-(void)setDidFinishSelectingPartySize:(id)arg1 ;
-(id)didFinishSelectingPartySize;
@end

