/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:33 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Maps/Maps-Structs.h>
@class GEOMapRegion, SearchFieldItem, NSArray, GEORelatedSearchSuggestion, NSString, GEOSearchCategory, SearchResult;

@interface SearchInfo : NSObject {

	char _shouldPreserveResults;
	char _searchAlongRoute;
	char _isRedoSearch;
	char _canRedoSearch;
	char _chainResults;
	unsigned _selectedIndex;
	GEOMapRegion* _requestedMapRegion;
	SearchFieldItem* _searchFieldItem;
	NSArray* _results;
	NSArray* _suggestions;
	GEOMapRegion* _mapRegion;
	int _searchResultType;
	GEORelatedSearchSuggestion* _defaultSuggestion;
	NSString* _resultDisplayHeader;
	GEOSearchCategory* _category;
	NSString* _searchText;

}

@property (assign,nonatomic) unsigned selectedIndex;                                        //@synthesize selectedIndex=_selectedIndex - In the implementation block
@property (assign,nonatomic) char shouldPreserveResults;                                    //@synthesize shouldPreserveResults=_shouldPreserveResults - In the implementation block
@property (assign,getter=isSearchAlongRoute,nonatomic) char searchAlongRoute;               //@synthesize searchAlongRoute=_searchAlongRoute - In the implementation block
@property (assign,nonatomic) char isRedoSearch;                                             //@synthesize isRedoSearch=_isRedoSearch - In the implementation block
@property (assign,nonatomic) char canRedoSearch;                                            //@synthesize canRedoSearch=_canRedoSearch - In the implementation block
@property (nonatomic,retain) GEOMapRegion * requestedMapRegion;                             //@synthesize requestedMapRegion=_requestedMapRegion - In the implementation block
@property (nonatomic,copy) SearchFieldItem * searchFieldItem;                               //@synthesize searchFieldItem=_searchFieldItem - In the implementation block
@property (nonatomic,readonly) NSArray * results;                                           //@synthesize results=_results - In the implementation block
@property (nonatomic,readonly) NSArray * suggestions;                                       //@synthesize suggestions=_suggestions - In the implementation block
@property (nonatomic,readonly) SearchResult * selectedResult; 
@property (nonatomic,readonly) GEOMapRegion * mapRegion;                                    //@synthesize mapRegion=_mapRegion - In the implementation block
@property (nonatomic,readonly) int searchResultType;                                        //@synthesize searchResultType=_searchResultType - In the implementation block
@property (nonatomic,readonly) GEORelatedSearchSuggestion * defaultSuggestion;              //@synthesize defaultSuggestion=_defaultSuggestion - In the implementation block
@property (nonatomic,readonly) NSString * resultDisplayHeader;                              //@synthesize resultDisplayHeader=_resultDisplayHeader - In the implementation block
@property (getter=isChainResults,nonatomic,readonly) char chainResults;                     //@synthesize chainResults=_chainResults - In the implementation block
@property (nonatomic,retain) GEOSearchCategory * category;                                  //@synthesize category=_category - In the implementation block
@property (nonatomic,copy) NSString * searchText;                                           //@synthesize searchText=_searchText - In the implementation block
@property (nonatomic,readonly) char singleResultMode; 
+(char)supportClientMapRegionCorrection;
+(id)searchInfoWithResults:(id)arg1 ;
+(id)searchInfoWithResults:(id)arg1 mapRegion:(SCD_Struct_RA12)arg2 ;
+(id)searchInfoWithResults:(id)arg1 boundingMapRegion:(id)arg2 ;
+(id)searchInfoWithMapItems:(id)arg1 traits:(id)arg2 placeInfo:(id)arg3 boundingRegion:(id)arg4 addressBookAddress:(id)arg5 searchType:(unsigned)arg6 ;
+(id)searchInfoWithTicket:(id)arg1 searchType:(unsigned)arg2 ;
+(id)searchInfoWithTicket:(id)arg1 addressBookAddress:(id)arg2 searchType:(unsigned)arg3 ;
+(id)searchInfoWithTicket:(id)arg1 addressBookAddress:(id)arg2 searchType:(unsigned)arg3 forRefinementSearchForBookmark:(id)arg4 ;
+(id)searchInfoWithSearchInfo:(id)arg1 refinedIndex:(unsigned)arg2 ;
-(SearchFieldItem *)searchFieldItem;
-(void)setSearchFieldItem:(SearchFieldItem *)arg1 ;
-(char)singleResultMode;
-(id)initWithSearchResults:(id)arg1 boundingMapRegion:(id)arg2 ;
-(SearchResult *)selectedResult;
-(void)addResultsFromSearchInfo:(id)arg1 ;
-(char)shouldPreserveResults;
-(void)setShouldPreserveResults:(char)arg1 ;
-(char)isSearchAlongRoute;
-(char)canRedoSearch;
-(void)setCanRedoSearch:(char)arg1 ;
-(GEOMapRegion *)requestedMapRegion;
-(void)setRequestedMapRegion:(GEOMapRegion *)arg1 ;
-(GEORelatedSearchSuggestion *)defaultSuggestion;
-(char)isChainResults;
-(void)setCategory:(GEOSearchCategory *)arg1 ;
-(GEOSearchCategory *)category;
-(unsigned)selectedIndex;
-(void)setSelectedIndex:(unsigned)arg1 ;
-(NSString *)searchText;
-(void)setSearchText:(NSString *)arg1 ;
-(NSArray *)results;
-(GEOMapRegion *)mapRegion;
-(int)searchResultType;
-(NSString *)resultDisplayHeader;
-(void)setIsRedoSearch:(char)arg1 ;
-(char)isRedoSearch;
-(NSArray *)suggestions;
-(void)setSearchAlongRoute:(char)arg1 ;
@end

