/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:42 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <Maps/OverlayContainerViewController.h>
#import <Maps/SteppingPageViewControllerDelegate.h>
#import <libobjc.A.dylib/MNNavigationServiceObserver.h>
#import <libobjc.A.dylib/GEOComposedRouteObserver.h>
#import <Maps/TransitSteppingSignGeneratorDelegate.h>
#import <Maps/MKMapViewDelegatePrivate.h>
#import <Maps/NavIdleTimerDelegate.h>
#import <Maps/PPTTestGuidanceStepProtocol.h>
#import <Maps/MapViewResponderHandling.h>

@protocol SteppingSignGenerator;
@class Route, StepActionCoordinator, SteppingPageViewController, BlurredStatusBar, UIScrollView, NSLayoutConstraint, ButtonsContainerViewController, _MKUserTrackingButton, MapCameraController, NavDebugLocationManager, NavigationDebugViewsController, NSDate, MNLocation, NSMutableSet, NSMutableDictionary, NSTimer, NavIdleTimer, MKMapView, NSString;

@interface StepContainerViewController : OverlayContainerViewController <SteppingPageViewControllerDelegate, MNNavigationServiceObserver, GEOComposedRouteObserver, TransitSteppingSignGeneratorDelegate, MKMapViewDelegatePrivate, NavIdleTimerDelegate, PPTTestGuidanceStepProtocol, MapViewResponderHandling> {

	char _isGoingToEnterGuidance;
	char _mustNotBreakUserTrackingMode;
	char _hasDesiredUserTrackingMode;
	char _userIsInteractingWithMap;
	char _didSubmitAlightFeedback;
	char _showingOverview;
	Route* _route;
	unsigned _matchedStepIndex;
	StepActionCoordinator* _stepActionCoordinator;
	SteppingPageViewController* _pagingVC;
	id<SteppingSignGenerator> _signGenerator;
	BlurredStatusBar* _blurredStatusBar;
	UIScrollView* _verticalSignScrollView;
	NSLayoutConstraint* _scrollViewHeightConstraint;
	ButtonsContainerViewController* _locationButtonViewController;
	_MKUserTrackingButton* _userLocationButton;
	MapCameraController* _mapCameraController;
	NavDebugLocationManager* _debugLocationManager;
	NavigationDebugViewsController* _debugViewsController;
	NSLayoutConstraint* _userLocationLeadingConstraint;
	NSLayoutConstraint* _userLocationTrailingConstraint;
	NSDate* _startDate;
	NSDate* _lastMapTouchDate;
	unsigned _matchedSignIndex;
	MNLocation* _previousMatchedLocation;
	int _desiredUserTrackingMode;
	int _hasArrived;
	NSMutableSet* _alightStepsNotified;
	NSMutableDictionary* _alightStepsFeedback;
	NSMutableDictionary* _isExpandedMapping;
	unsigned _initialStepIndex;
	NSTimer* _delayAutoAdvanceTimer;
	NSTimer* _locationExpirationTimer;
	NSTimer* _arrivalEndTimer;
	NSTimer* _backgroundArrivalTimer;
	NavIdleTimer* _idleTimer;

}

@property (nonatomic,retain) SteppingPageViewController * pagingVC;                                      //@synthesize pagingVC=_pagingVC - In the implementation block
@property (nonatomic,retain) id<SteppingSignGenerator> signGenerator;                                    //@synthesize signGenerator=_signGenerator - In the implementation block
@property (nonatomic,retain) BlurredStatusBar * blurredStatusBar;                                        //@synthesize blurredStatusBar=_blurredStatusBar - In the implementation block
@property (nonatomic,retain) UIScrollView * verticalSignScrollView;                                      //@synthesize verticalSignScrollView=_verticalSignScrollView - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * scrollViewHeightConstraint;                            //@synthesize scrollViewHeightConstraint=_scrollViewHeightConstraint - In the implementation block
@property (nonatomic,retain) ButtonsContainerViewController * locationButtonViewController;              //@synthesize locationButtonViewController=_locationButtonViewController - In the implementation block
@property (nonatomic,retain) _MKUserTrackingButton * userLocationButton;                                 //@synthesize userLocationButton=_userLocationButton - In the implementation block
@property (nonatomic,readonly) MKMapView * mapView; 
@property (nonatomic,retain) MapCameraController * mapCameraController;                                  //@synthesize mapCameraController=_mapCameraController - In the implementation block
@property (nonatomic,retain) NavDebugLocationManager * debugLocationManager;                             //@synthesize debugLocationManager=_debugLocationManager - In the implementation block
@property (nonatomic,retain) NavigationDebugViewsController * debugViewsController;                      //@synthesize debugViewsController=_debugViewsController - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * userLocationLeadingConstraint;                         //@synthesize userLocationLeadingConstraint=_userLocationLeadingConstraint - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * userLocationTrailingConstraint;                        //@synthesize userLocationTrailingConstraint=_userLocationTrailingConstraint - In the implementation block
@property (nonatomic,retain) NSDate * startDate;                                                         //@synthesize startDate=_startDate - In the implementation block
@property (nonatomic,retain) NSDate * lastMapTouchDate;                                                  //@synthesize lastMapTouchDate=_lastMapTouchDate - In the implementation block
@property (assign,nonatomic) unsigned matchedSignIndex;                                                  //@synthesize matchedSignIndex=_matchedSignIndex - In the implementation block
@property (assign,nonatomic) char isGoingToEnterGuidance;                                                //@synthesize isGoingToEnterGuidance=_isGoingToEnterGuidance - In the implementation block
@property (nonatomic,retain) MNLocation * previousMatchedLocation;                                       //@synthesize previousMatchedLocation=_previousMatchedLocation - In the implementation block
@property (assign,nonatomic) char mustNotBreakUserTrackingMode;                                          //@synthesize mustNotBreakUserTrackingMode=_mustNotBreakUserTrackingMode - In the implementation block
@property (assign,nonatomic) char hasDesiredUserTrackingMode;                                            //@synthesize hasDesiredUserTrackingMode=_hasDesiredUserTrackingMode - In the implementation block
@property (assign,nonatomic) int desiredUserTrackingMode;                                                //@synthesize desiredUserTrackingMode=_desiredUserTrackingMode - In the implementation block
@property (assign,nonatomic) char userIsInteractingWithMap;                                              //@synthesize userIsInteractingWithMap=_userIsInteractingWithMap - In the implementation block
@property (assign,nonatomic) int hasArrived;                                                             //@synthesize hasArrived=_hasArrived - In the implementation block
@property (assign,nonatomic) char didSubmitAlightFeedback;                                               //@synthesize didSubmitAlightFeedback=_didSubmitAlightFeedback - In the implementation block
@property (nonatomic,retain) NSMutableSet * alightStepsNotified;                                         //@synthesize alightStepsNotified=_alightStepsNotified - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * alightStepsFeedback;                                  //@synthesize alightStepsFeedback=_alightStepsFeedback - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * isExpandedMapping;                                    //@synthesize isExpandedMapping=_isExpandedMapping - In the implementation block
@property (assign,nonatomic) char showingOverview;                                                       //@synthesize showingOverview=_showingOverview - In the implementation block
@property (assign,nonatomic) unsigned initialStepIndex;                                                  //@synthesize initialStepIndex=_initialStepIndex - In the implementation block
@property (nonatomic,retain) NSTimer * delayAutoAdvanceTimer;                                            //@synthesize delayAutoAdvanceTimer=_delayAutoAdvanceTimer - In the implementation block
@property (nonatomic,retain) NSTimer * locationExpirationTimer;                                          //@synthesize locationExpirationTimer=_locationExpirationTimer - In the implementation block
@property (nonatomic,retain) NSTimer * arrivalEndTimer;                                                  //@synthesize arrivalEndTimer=_arrivalEndTimer - In the implementation block
@property (nonatomic,retain) NSTimer * backgroundArrivalTimer;                                           //@synthesize backgroundArrivalTimer=_backgroundArrivalTimer - In the implementation block
@property (nonatomic,retain) NavIdleTimer * idleTimer;                                                   //@synthesize idleTimer=_idleTimer - In the implementation block
@property (nonatomic,readonly) Route * route;                                                            //@synthesize route=_route - In the implementation block
@property (nonatomic,readonly) unsigned matchedStepIndex;                                                //@synthesize matchedStepIndex=_matchedStepIndex - In the implementation block
@property (nonatomic,retain) StepActionCoordinator * stepActionCoordinator;                              //@synthesize stepActionCoordinator=_stepActionCoordinator - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)updateLayoutAnimated:(char)arg1 ;
-(unsigned)originalLayoutForViewController:(id)arg1 ;
-(float)availableHeight;
-(id)passThroughView;
-(void)containerStyleManagerConfigureLayoutForStyle:(unsigned)arg1 ;
-(void)containerStyleManagerDidChangeStyle:(unsigned)arg1 ;
-(float)bottomEdgeInset;
-(void)didTapMapView:(id)arg1 atPoint:(CGPoint)arg2 ;
-(char)pptTestSupportStepping;
-(int)pptTestCurrentStepIndex;
-(char)pptTestHasNextStep;
-(void)pptTestMoveToNextStep;
-(StepActionCoordinator *)stepActionCoordinator;
-(id<SteppingSignGenerator>)signGenerator;
-(void)_transparencyStatusDidChange:(id)arg1 ;
-(BlurredStatusBar *)blurredStatusBar;
-(void)setBlurredStatusBar:(BlurredStatusBar *)arg1 ;
-(char)_isTrackingLocation;
-(MapCameraController *)mapCameraController;
-(id)_directionsManager;
-(void)setMapCameraController:(MapCameraController *)arg1 ;
-(void)steppingPageViewController:(id)arg1 didChangeCurrentSign:(int)arg2 previousSign:(int)arg3 fromUserGesture:(unsigned)arg4 ;
-(void)steppingPageViewControllerUserDidStartScrolling:(id)arg1 ;
-(void)steppingPageViewControllerDidChangeSignHeight:(id)arg1 ;
-(void)setSignGenerator:(id<SteppingSignGenerator>)arg1 ;
-(unsigned)matchedStepIndex;
-(NavigationDebugViewsController *)debugViewsController;
-(void)setDebugViewsController:(NavigationDebugViewsController *)arg1 ;
-(void)idleTimerDidTimeout:(id)arg1 ;
-(void)transitSteppingSignGenerator:(id)arg1 incidentButtonTappedForIncidents:(id)arg2 ;
-(void)transitSteppingSignGenerator:(id)arg1 didTapClusteredRoutesButtonInSteppingSignView:(id)arg2 ;
-(void)transitSteppingSignGenerator:(id)arg1 didTapExpandLabelInSteppingSignCell:(id)arg2 ;
-(char)transitSteppingSignGenerator:(id)arg1 signShouldBeExpandedAtIndex:(int)arg2 ;
-(id)initWithRoute:(id)arg1 initialStepIndex:(unsigned)arg2 ;
-(id)initWithRoute:(id)arg1 initialStepIndex:(unsigned)arg2 desiredTrackingMode:(int)arg3 ;
-(void)_addNavigationObservers;
-(void)_setupDebugUtilities;
-(void)updateWithDisplayedStep:(id)arg1 ;
-(void)showOverview:(char)arg1 andZoomToMapRegion:(char)arg2 ;
-(void)_setupStatusBarBackground;
-(void)_showInitialStepIfNecessary;
-(void)_userLocationButtonWasTapped:(id)arg1 ;
-(void)_updateMapRegionForSignAtIndex:(int)arg1 ;
-(void)_setUserTrackingMode:(int)arg1 animated:(char)arg2 ;
-(void)_updateUserLocationViewAppearanceWithMatchedLocation:(id)arg1 ;
-(char)_isStepOnTransitLine:(id)arg1 ;
-(char)_shouldShowHeadingIndicatorForStep:(id)arg1 ;
-(void)_updateForMatchedStepIndex:(unsigned)arg1 matchedLegIndex:(unsigned)arg2 ;
-(float)maximumSignHeight;
-(void)setupAsNavigationObserver;
-(void)teardownAsNavigationObserver;
-(void)_startArrivalEndTimerIfNecessary;
-(void)_stopArrivalEndTimer;
-(void)_arrivalEndTimerFired;
-(void)_locationExpirationTimerFired;
-(void)_backgroundArrivalTimerFired;
-(void)_setGizmoStepIndex:(unsigned)arg1 ;
-(void)submitAlightNotificationFeedbacks;
-(id)_geoRouteDetails;
-(void)_updateDebugConsoleForLocation:(id)arg1 ;
-(void)_toggleTraceControls;
-(void)setStepActionCoordinator:(StepActionCoordinator *)arg1 ;
-(SteppingPageViewController *)pagingVC;
-(void)setPagingVC:(SteppingPageViewController *)arg1 ;
-(UIScrollView *)verticalSignScrollView;
-(void)setVerticalSignScrollView:(UIScrollView *)arg1 ;
-(NSLayoutConstraint *)scrollViewHeightConstraint;
-(void)setScrollViewHeightConstraint:(NSLayoutConstraint *)arg1 ;
-(ButtonsContainerViewController *)locationButtonViewController;
-(void)setLocationButtonViewController:(ButtonsContainerViewController *)arg1 ;
-(NavDebugLocationManager *)debugLocationManager;
-(void)setDebugLocationManager:(NavDebugLocationManager *)arg1 ;
-(NSLayoutConstraint *)userLocationLeadingConstraint;
-(void)setUserLocationLeadingConstraint:(NSLayoutConstraint *)arg1 ;
-(NSLayoutConstraint *)userLocationTrailingConstraint;
-(void)setUserLocationTrailingConstraint:(NSLayoutConstraint *)arg1 ;
-(NSDate *)lastMapTouchDate;
-(void)setLastMapTouchDate:(NSDate *)arg1 ;
-(unsigned)matchedSignIndex;
-(void)setMatchedSignIndex:(unsigned)arg1 ;
-(char)isGoingToEnterGuidance;
-(void)setIsGoingToEnterGuidance:(char)arg1 ;
-(MNLocation *)previousMatchedLocation;
-(void)setPreviousMatchedLocation:(MNLocation *)arg1 ;
-(char)mustNotBreakUserTrackingMode;
-(void)setMustNotBreakUserTrackingMode:(char)arg1 ;
-(char)hasDesiredUserTrackingMode;
-(void)setHasDesiredUserTrackingMode:(char)arg1 ;
-(int)desiredUserTrackingMode;
-(void)setDesiredUserTrackingMode:(int)arg1 ;
-(char)userIsInteractingWithMap;
-(void)setUserIsInteractingWithMap:(char)arg1 ;
-(void)setHasArrived:(int)arg1 ;
-(char)didSubmitAlightFeedback;
-(void)setDidSubmitAlightFeedback:(char)arg1 ;
-(NSMutableSet *)alightStepsNotified;
-(void)setAlightStepsNotified:(NSMutableSet *)arg1 ;
-(NSMutableDictionary *)alightStepsFeedback;
-(void)setAlightStepsFeedback:(NSMutableDictionary *)arg1 ;
-(NSMutableDictionary *)isExpandedMapping;
-(void)setIsExpandedMapping:(NSMutableDictionary *)arg1 ;
-(char)showingOverview;
-(void)setShowingOverview:(char)arg1 ;
-(unsigned)initialStepIndex;
-(void)setInitialStepIndex:(unsigned)arg1 ;
-(NSTimer *)delayAutoAdvanceTimer;
-(void)setDelayAutoAdvanceTimer:(NSTimer *)arg1 ;
-(NSTimer *)locationExpirationTimer;
-(void)setLocationExpirationTimer:(NSTimer *)arg1 ;
-(NSTimer *)arrivalEndTimer;
-(void)setArrivalEndTimer:(NSTimer *)arg1 ;
-(NSTimer *)backgroundArrivalTimer;
-(void)setBackgroundArrivalTimer:(NSTimer *)arg1 ;
-(void)_invalidateTimers;
-(void)_delayTimerFired;
-(void)dealloc;
-(int)preferredStatusBarStyle;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidAppear:(char)arg1 ;
-(void)viewDidDisappear:(char)arg1 ;
-(void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)viewDidLoad;
-(void)_didEnterBackground:(id)arg1 ;
-(void)_willEnterForeground:(id)arg1 ;
-(Route *)route;
-(void)composedRoute:(id)arg1 changedSelectedRideInClusteredLeg:(id)arg2 fromIndex:(unsigned)arg3 toIndex:(unsigned)arg4 ;
-(void)composedRouteUpdatedSnappedPaths:(id)arg1 ;
-(void)composedRoute:(id)arg1 selectedSections:(id)arg2 deselectedSections:(id)arg3 ;
-(void)composedRouteUpdatedTraffic:(id)arg1 ;
-(int)hasArrived;
-(void)mapView:(id)arg1 didSelectLabelMarker:(id)arg2 ;
-(void)mapViewDidStopUserInteraction:(id)arg1 ;
-(void)mapViewDidStartUserInteraction:(id)arg1 ;
-(void)mapViewDidFinishInitialUserTrackingModeAnimation:(id)arg1 ;
-(char)mapView:(id)arg1 shouldSelectLabelMarker:(id)arg2 ;
-(void)setStartDate:(NSDate *)arg1 ;
-(NSDate *)startDate;
-(void)mapView:(id)arg1 regionDidChangeAnimated:(char)arg2 ;
-(void)mapViewDidFinishLoadingMap:(id)arg1 ;
-(id)mapView:(id)arg1 viewForAnnotation:(id)arg2 ;
-(id)mapView:(id)arg1 rendererForOverlay:(id)arg2 ;
-(MKMapView *)mapView;
-(_MKUserTrackingButton *)userLocationButton;
-(void)setUserLocationButton:(_MKUserTrackingButton *)arg1 ;
-(void)_updateIdleTimer;
-(void)navigationService:(id)arg1 didUpdateFeedback:(id)arg2 forAlightingStepAtIndex:(unsigned)arg3 ;
-(void)navigationService:(id)arg1 didSignalAlightForStepAtIndex:(unsigned)arg2 ;
-(void)navigationServiceDidArrive:(id)arg1 ;
-(void)navigationService:(id)arg1 didUpdateStepIndex:(unsigned)arg2 legIndex:(unsigned)arg3 ;
-(void)navigationService:(id)arg1 didUpdateMatchedLocation:(id)arg2 ;
-(void)navigationService:(id)arg1 willChangeFromState:(unsigned)arg2 toState:(unsigned)arg3 ;
-(NavIdleTimer *)idleTimer;
-(void)setIdleTimer:(NavIdleTimer *)arg1 ;
-(void)_setupViews;
-(void)_setupConstraints;
@end

