/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:36 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <UIKit/UITableViewCell.h>
#import <UIKit/UITextViewDelegate.h>

@class UITextView, NSString;

@interface TextViewTableViewCell : UITableViewCell <UITextViewDelegate> {

	UITextView* _textView;

}

@property (nonatomic,readonly) UITextView * textView;               //@synthesize textView=_textView - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)configureToolbar;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
-(char)textView:(id)arg1 shouldChangeTextInRange:(NSRange)arg2 replacementText:(id)arg3 ;
-(UITextView *)textView;
-(void)setupConstraints;
-(void)doneButtonTapped:(id)arg1 ;
@end

