/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:40 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/AuxiliaryDebugViewController.h>
#import <libobjc.A.dylib/GEOResourceManifestTileGroupObserver.h>

@protocol MapsDebugViewControllerDelegate;
@class GEOResourceManifestDownload, NSString;

@interface TileGroupInfoDebugController : AuxiliaryDebugViewController <GEOResourceManifestTileGroupObserver> {

	char _canChangeActiveTileGroup;
	id<MapsDebugViewControllerDelegate> _delegate;
	int tileGroupIdentifier;
	GEOResourceManifestDownload* _resourceManifest;

}

@property (assign,nonatomic) int tileGroupIdentifier; 
@property (assign,nonatomic) char canChangeActiveTileGroup;                               //@synthesize canChangeActiveTileGroup=_canChangeActiveTileGroup - In the implementation block
@property (nonatomic,retain) GEOResourceManifestDownload * resourceManifest;              //@synthesize resourceManifest=_resourceManifest - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)navigationDestinationTitle;
-(void)setResourceManifest:(GEOResourceManifestDownload *)arg1 ;
-(void)setCanChangeActiveTileGroup:(char)arg1 ;
-(id)_tileGroup;
-(id)_resourceNames;
-(char)canChangeActiveTileGroup;
-(void)setDelegate:(id)arg1 ;
-(void)dealloc;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(id)delegate;
-(id)initWithStyle:(int)arg1 ;
-(void)resourceManifestManagerWillChangeActiveTileGroup:(id)arg1 ;
-(void)resourceManifestManagerDidChangeActiveTileGroup:(id)arg1 ;
-(int)tileGroupIdentifier;
-(void)setTileGroupIdentifier:(int)arg1 ;
-(GEOResourceManifestDownload *)resourceManifest;
@end

