/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:42 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <Maps/MapsThemeView.h>

@class NSMutableArray, NSString, UILabel;

@interface TrayHeaderLabelView : MapsThemeView {

	NSMutableArray* _defaultLayoutConstraints;
	NSMutableArray* _minimizedLayoutConstraints;
	NSMutableArray* _overflowLayoutConstraints;
	NSString* _secondaryText;
	NSString* _minimizedSecondaryText;
	unsigned _layout;
	UILabel* _primaryLabel;
	UILabel* _secondaryLabel;

}

@property (nonatomic,retain) UILabel * primaryLabel;                //@synthesize primaryLabel=_primaryLabel - In the implementation block
@property (nonatomic,retain) UILabel * secondaryLabel;              //@synthesize secondaryLabel=_secondaryLabel - In the implementation block
@property (assign,nonatomic) unsigned layout;                       //@synthesize layout=_layout - In the implementation block
-(void)updateTheme;
-(void)setPrimaryText:(id)arg1 secondaryText:(id)arg2 ;
-(void)setPrimaryText:(id)arg1 secondaryText:(id)arg2 minimizedSecondaryText:(id)arg3 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(CGSize)intrinsicContentSize;
-(unsigned)layout;
-(void)setLayout:(unsigned)arg1 ;
-(UILabel *)secondaryLabel;
-(void)setSecondaryLabel:(UILabel *)arg1 ;
-(void)setupSubviews;
-(UILabel *)primaryLabel;
-(void)setPrimaryLabel:(UILabel *)arg1 ;
-(void)setupConstraints;
@end

