/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:44 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <Maps/MapsThemeTableViewCell.h>
#import <libobjc.A.dylib/NUIContainerStackViewDelegate.h>
#import <Maps/SearchResultQuickActionMenuCell.h>

@class UILabel, UIImageView, UIView, MKLocalSearchCompletion, NUIContainerStackView, MapsSuggestionsEntry, SearchResult, NSString;

@interface TwoLinesTableViewCell : MapsThemeTableViewCell <NUIContainerStackViewDelegate, SearchResultQuickActionMenuCell> {

	UILabel* _mainTitleLabel;
	UILabel* _secondTitleLabel;
	UIImageView* _leftImageView;
	UIView* _badgeView;
	MKLocalSearchCompletion* _completion;
	int _imageState;
	NUIContainerStackView* _rootStackView;
	id _object;
	MapsSuggestionsEntry* _observedEntry;
	SearchResult* _observedSearchResult;

}

@property (nonatomic,retain) MapsSuggestionsEntry * observedEntry;              //@synthesize observedEntry=_observedEntry - In the implementation block
@property (nonatomic,retain) SearchResult * observedSearchResult;               //@synthesize observedSearchResult=_observedSearchResult - In the implementation block
@property (nonatomic,retain) id object;                                         //@synthesize object=_object - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)identifier;
+(float)cellHeight;
-(void)updateTheme;
-(void)setRecent:(id)arg1 ;
-(id)personalizedItemForQuickActionMenu;
-(id)anchorContentViewForQuickActionMenuPresenter:(id)arg1 ;
-(void)prepareForActionMenuPresentationUsingTheme:(id)arg1 ;
-(id)titleRegularFont;
-(void)setMainTitle:(id)arg1 andSecondTitle:(id)arg2 andImage:(id)arg3 ;
-(id)stringForSubtitleOrigin:(id)arg1 ;
-(void)updateObservedEntry;
-(void)setObservedSearchResult:(SearchResult *)arg1 ;
-(void)setImageForStyleAttributes:(id)arg1 ;
-(void)setImageForStyleAttributes:(id)arg1 markerFallback:(char)arg2 ;
-(void)setImageForStyleAttributes:(id)arg1 markerFallback:(char)arg2 isInitialAttempt:(char)arg3 ;
-(void)setImageForCategory:(id)arg1 ;
-(void)setImageForMapItem:(id)arg1 ;
-(void)setImageForContact:(id)arg1 ;
-(void)setImageForTransitArtworkDataSource:(id)arg1 ;
-(void)setObservedEntry:(MapsSuggestionsEntry *)arg1 ;
-(void)updateLabelsForCompletion;
-(MapsSuggestionsEntry *)observedEntry;
-(SearchResult *)observedSearchResult;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(id)object;
-(void)prepareForReuse;
-(void)setObject:(id)arg1 ;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(id)titleFont;
-(CGSize)containerStackView:(id)arg1 systemLayoutSizeFittingSize:(CGSize)arg2 forArrangedSubview:(id)arg3 ;
-(void)setMainTitle:(id)arg1 ;
-(void)_updateFonts;
-(void)containerStackViewDidLayoutArrangedSubviews:(id)arg1 ;
@end

