/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:37:58 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/AppStore.app/AppStore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <AppStore/AppStore-Structs.h>
#import <StoreKitUI/SKUIViewController.h>
#import <AppStore/ASChildPurchasedViewControllerDelegate.h>
#import <libobjc.A.dylib/SKUIViewControllerTesting.h>
#import <UIKit/UIViewControllerRestoration.h>

@class UIImageView, SSFamilyMember, ASBaseIPadPurchasedViewController, ASBaseIPhonePurchasedViewController, ASPurchasedPage, NSString, NSDictionary;

@interface ASBasePurchasedViewController : SKUIViewController <ASChildPurchasedViewControllerDelegate, SKUIViewControllerTesting, UIViewControllerRestoration> {

	UIImageView* _animationImageView;
	int _deviceType;
	SSFamilyMember* _familyMember;
	char _hidesInstalledApps;
	ASBaseIPadPurchasedViewController* _iPadViewController;
	ASBaseIPhonePurchasedViewController* _iPhoneViewController;
	ASPurchasedPage* _page;
	NSString* _searchTerm;
	NSString* _performanceTestName;
	NSDictionary* _performanceTestOptions;

}

@property (nonatomic,copy) NSString * performanceTestName;                     //@synthesize performanceTestName=_performanceTestName - In the implementation block
@property (nonatomic,copy) NSDictionary * performanceTestOptions;              //@synthesize performanceTestOptions=_performanceTestOptions - In the implementation block
@property (nonatomic,retain) SSFamilyMember * familyMember;                    //@synthesize familyMember=_familyMember - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)viewControllerWithRestorationIdentifierPath:(id)arg1 coder:(id)arg2 ;
+(char)_shouldForwardViewWillTransitionToSize;
+(int)_sizeClassForSize:(CGSize)arg1 ;
-(SSFamilyMember *)familyMember;
-(void)childPurchasedViewController:(id)arg1 didChangeDeviceType:(int)arg2 ;
-(void)childPurchasedViewController:(id)arg1 didChangeFamilyMember:(id)arg2 ;
-(void)childPurchasedViewController:(id)arg1 didChangeSearchTerm:(id)arg2 ;
-(void)childPurchasedViewControllerWantsAuthenticate:(id)arg1 ;
-(void)childPurchasedViewController:(id)arg1 didChangeHidesInstalledApps:(char)arg2 ;
-(void)_databaseStateChangedNotification:(id)arg1 ;
-(void)_familyCircleDidChange:(id)arg1 ;
-(void)_reloadDataAndCheckForUpdates;
-(id)testingViewController;
-(void)setPerformanceTestName:(NSString *)arg1 ;
-(void)setPerformanceTestOptions:(NSDictionary *)arg1 ;
-(char)_isSignInRequired;
-(id)_additionalPredicatesForPurchaseDB;
-(void)setFamilyMember:(SSFamilyMember *)arg1 ;
-(id)_createPurchasedPage;
-(id)_newIPadViewController;
-(id)_newIPhoneViewController;
-(NSString *)performanceTestName;
-(NSDictionary *)performanceTestOptions;
-(void)dealloc;
-(void)loadView;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidLayoutSubviews;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)_reloadData;
-(char)performTestWithName:(id)arg1 options:(id)arg2 ;
-(void)_reloadView;
-(void)_accountStoreDidChange:(id)arg1 ;
-(void)_reloadViewControllerWithSize:(CGSize)arg1 ;
@end

