/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:23:44 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/AppStore.app/AppStore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <AppStore/AppStore-Structs.h>
#import <libobjc.A.dylib/SKUIArtworkRequestDelegate.h>
#import <AppStore/ASItemArtworkLoaderProtocol.h>

@protocol OS_dispatch_queue, ASItemArtworkLoaderProtocolDelegate;
@class UIImage, NSObject, NSMapTable, SKUIStyledImageDataConsumer, SKUIResourceLoader, NSString;

@interface ASItemArtworkLoader : NSObject <SKUIArtworkRequestDelegate, ASItemArtworkLoaderProtocol> {

	NSObject*<OS_dispatch_queue> _accessQueue;
	id<ASItemArtworkLoaderProtocolDelegate> _delegate;
	NSMapTable* _artworkRequestIDs;
	SKUIStyledImageDataConsumer* _dataConsumer;
	UIImage* _placeholderImage;
	SKUIResourceLoader* _resourceLoader;
	CGSize _artworkSize;

}

@property (nonatomic,readonly) CGSize artworkSize;                                                 //@synthesize artworkSize=_artworkSize - In the implementation block
@property (nonatomic,readonly) NSMapTable * artworkRequestIDs;                                     //@synthesize artworkRequestIDs=_artworkRequestIDs - In the implementation block
@property (nonatomic,readonly) SKUIResourceLoader * resourceLoader;                                //@synthesize resourceLoader=_resourceLoader - In the implementation block
@property (nonatomic,retain) SKUIStyledImageDataConsumer * dataConsumer;                           //@synthesize dataConsumer=_dataConsumer - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) UIImage * placeholderImage;                                         //@synthesize placeholderImage=_placeholderImage - In the implementation block
@property (assign,nonatomic,__weak) id<ASItemArtworkLoaderProtocolDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
+(CGSize)_artworkSize;
-(id)_imageForArtworkProvider:(id)arg1 reason:(int)arg2 ;
-(NSMapTable *)artworkRequestIDs;
-(CGSize)_artworkSizeScaledForDisplay;
-(id)imageForArtworkProvider:(id)arg1 ;
-(id)imageForArtworkProvider:(id)arg1 reason:(int)arg2 ;
-(id)styledImageForImage:(id)arg1 ;
-(id)init;
-(void)setDelegate:(id<ASItemArtworkLoaderProtocolDelegate>)arg1 ;
-(id<ASItemArtworkLoaderProtocolDelegate>)delegate;
-(UIImage *)placeholderImage;
-(SKUIResourceLoader *)resourceLoader;
-(void)setDataConsumer:(SKUIStyledImageDataConsumer *)arg1 ;
-(void)artworkRequest:(id)arg1 didLoadImage:(id)arg2 ;
-(SKUIStyledImageDataConsumer *)dataConsumer;
-(id)initWithResourceLoader:(id)arg1 ;
-(CGSize)artworkSize;
@end

