/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:23:44 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/AppStore.app/AppStore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SKUIItemGridDelegate <NSObject>
@optional
-(void)itemGrid:(id)arg1 didPerformEditActionForItem:(id)arg2 atIndex:(int)arg3;
-(void)itemGrid:(id)arg1 didSelectItem:(id)arg2 atIndex:(int)arg3;
-(void)itemGridWillBeginDragging:(id)arg1;

@end

