/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:17 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/FieldTest.app/FieldTest
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary;

@interface ClassIndex : NSObject {

	NSMutableDictionary* classDict;
	NSMutableDictionary* codeDictionary;

}
-(id)getClass:(id)arg1 ;
-(id)getSubscribers:(int)arg1 ;
-(id)getAllLogCodes;
-(id)init;
-(void)dealloc;
-(void)status;
@end

