/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:03 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/FieldTest.app/FieldTest
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface LogGenerator : NSObject
+(id)generatorFromTechnology:(id)arg1 ;
+(void)updateHistoryInState:(id)arg1 ;
-(id)getStartCommand;
-(id)generateLogUsingState:(id)arg1 ;
-(void)updateState:(id)arg1 withData:(id)arg2 ;
-(id)getSaveContentsFromState:(id)arg1 ;
-(id)init;
@end

