/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:17 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/FieldTest.app/FieldTest
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <FieldTest/ClassIndex.h>

@class RRC_State, UTRANServingCellInfo, UTRANNeighbhorMeasurements, GSMNeighbhorMeasurements, TRCHBLERMeasurement, CCTRCHSIRMeasurement, PDPContextList, SimInfo;

@interface UTRANClassIndex : ClassIndex {

	RRC_State* rrc_state;
	UTRANServingCellInfo* servingCellInfo;
	UTRANNeighbhorMeasurements* tdMeasurements;
	GSMNeighbhorMeasurements* gsmMeasurements;
	TRCHBLERMeasurement* trchMeasurements;
	CCTRCHSIRMeasurement* cctrchMeasurements;
	PDPContextList* pdpList;
	SimInfo* simInfo;

}
-(id)init;
-(void)dealloc;
@end

