/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:25:27 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Reminders.app/PlugIns/RemindersWidget.appex/RemindersWidget
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class UILabel;

@interface RemindersWidgetMoreContentCell : UITableViewCell {

	UILabel* _textLabel;

}
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
-(void)setText:(id)arg1 ;
@end

