/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:25:36 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/SoftwareUpdateUIService.app/SoftwareUpdateUIService
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SoftwareUpdateUIService/SoftwareUpdateUIService-Structs.h>
#import <SoftwareUpdateUIService/SUSUIPasscodeEntryView.h>

@class SUAutoInstallOperation;

@interface SUSUIInstallTonightPasscodeEntryView : SUSUIPasscodeEntryView {

	SUAutoInstallOperation* _installOperation;

}
-(void)setInstallTonightOperation:(id)arg1 ;
-(void)updateStatusText;
-(id)createPasscodeView;
-(id)_bodyTextToModelSpecificLocalizedKey:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
@end

