/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:25:16 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <UIKit/UIViewController.h>
#import <UIKit/UITableViewDataSource.h>
#import <UIKit/UITableViewDelegate.h>

@protocol MTSleepAlarmOnboardingDelegate;
@class MTSleepAlarm, UIImageView, UILabel, UITableView, NSLayoutConstraint, NSString;

@interface MTSleepAlarmReminderViewController : UIViewController <UITableViewDataSource, UITableViewDelegate> {

	id<MTSleepAlarmOnboardingDelegate> _onboardingDelegate;
	MTSleepAlarm* _sleepAlarm;
	UIImageView* _imageView;
	UILabel* _titleLabel;
	UITableView* _tableView;
	NSLayoutConstraint* _titleBaselineConstraint;
	NSLayoutConstraint* _iconTitleConstraint;

}

@property (nonatomic,retain) UIImageView * imageView;                                                   //@synthesize imageView=_imageView - In the implementation block
@property (nonatomic,retain) UILabel * titleLabel;                                                      //@synthesize titleLabel=_titleLabel - In the implementation block
@property (nonatomic,retain) UITableView * tableView;                                                   //@synthesize tableView=_tableView - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * titleBaselineConstraint;                              //@synthesize titleBaselineConstraint=_titleBaselineConstraint - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * iconTitleConstraint;                                  //@synthesize iconTitleConstraint=_iconTitleConstraint - In the implementation block
@property (assign,nonatomic,__weak) id<MTSleepAlarmOnboardingDelegate> onboardingDelegate;              //@synthesize onboardingDelegate=_onboardingDelegate - In the implementation block
@property (nonatomic,retain) MTSleepAlarm * sleepAlarm;                                                 //@synthesize sleepAlarm=_sleepAlarm - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(NSLayoutConstraint *)titleBaselineConstraint;
-(id<MTSleepAlarmOnboardingDelegate>)onboardingDelegate;
-(void)setOnboardingDelegate:(id<MTSleepAlarmOnboardingDelegate>)arg1 ;
-(void)setTitleBaselineConstraint:(NSLayoutConstraint *)arg1 ;
-(void)setSleepAlarm:(MTSleepAlarm *)arg1 ;
-(void)handleContentSizeChange:(id)arg1 ;
-(void)updateTitleBaselineConstraint;
-(void)setIconTitleConstraint:(NSLayoutConstraint *)arg1 ;
-(NSLayoutConstraint *)iconTitleConstraint;
-(id)reminderMinutesForCellAtIndexPath:(id)arg1 ;
-(id)titleForCellAtIndexPath:(id)arg1 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(void)loadView;
-(void)viewWillAppear:(char)arg1 ;
-(UILabel *)titleLabel;
-(void)setTableView:(UITableView *)arg1 ;
-(UITableView *)tableView;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)viewDidLoad;
-(UIImageView *)imageView;
-(void)setImageView:(UIImageView *)arg1 ;
-(void)setTitleLabel:(UILabel *)arg1 ;
-(void)setupConstraints;
-(MTSleepAlarm *)sleepAlarm;
-(void)next:(id)arg1 ;
@end

