/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:39:19 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <UIKit/UIViewController.h>
#import <MobileTimer/MTStopwatchPagingViewControllerDelegate.h>
#import <MobileTimer/StateManagement.h>
#import <MobileTimer/StopWatchControlsTarget.h>

@class CADisplayLink, NSDate, NSMutableArray, NSTimer, NSUserActivity, MTStopwatchController, MTStopwatchLapTableViewController, MTStopwatchLapTableHeaderView, UIImageView, MTStopwatchPagingViewController, UIPageControl, UIView, MTAnalogStopwatchView, MTTimeView, NSArray, NSString;

@interface StopWatchViewController : UIViewController <MTStopwatchPagingViewControllerDelegate, StateManagement, StopWatchControlsTarget> {

	CADisplayLink* _displayLink;
	NSDate* _startTime;
	double _offset;
	double _currentInterval;
	double _previousLapsTotalInterval;
	NSMutableArray* _laps;
	char _isTimerRunning;
	NSTimer* _restoreIdleTimerTimer;
	int _mode;
	NSUserActivity* _userActivity;
	MTStopwatchController* _stopwatchController;
	MTStopwatchLapTableViewController* _lapTableController;
	MTStopwatchLapTableHeaderView* _tableHeaderView;
	UIImageView* _lapButtonOccludingView;
	UIImageView* _startButtonOccludingView;
	MTStopwatchPagingViewController* _pagingViewController;
	UIPageControl* _pageControl;
	UIView* _analogStopwatchContainer;
	MTAnalogStopwatchView* _analogStopwatch;
	UIView* _digitalStopwatchContainer;
	MTTimeView* _timeView;
	NSArray* _constraints;
	CGSize _latestLayoutSize;

}

@property (nonatomic,retain) MTStopwatchController * stopwatchController;                         //@synthesize stopwatchController=_stopwatchController - In the implementation block
@property (nonatomic,retain) MTStopwatchLapTableViewController * lapTableController;              //@synthesize lapTableController=_lapTableController - In the implementation block
@property (nonatomic,retain) MTStopwatchLapTableHeaderView * tableHeaderView;                     //@synthesize tableHeaderView=_tableHeaderView - In the implementation block
@property (nonatomic,retain) UIImageView * lapButtonOccludingView;                                //@synthesize lapButtonOccludingView=_lapButtonOccludingView - In the implementation block
@property (nonatomic,retain) UIImageView * startButtonOccludingView;                              //@synthesize startButtonOccludingView=_startButtonOccludingView - In the implementation block
@property (nonatomic,retain) MTStopwatchPagingViewController * pagingViewController;              //@synthesize pagingViewController=_pagingViewController - In the implementation block
@property (nonatomic,retain) UIPageControl * pageControl;                                         //@synthesize pageControl=_pageControl - In the implementation block
@property (nonatomic,retain) UIView * analogStopwatchContainer;                                   //@synthesize analogStopwatchContainer=_analogStopwatchContainer - In the implementation block
@property (nonatomic,retain) MTAnalogStopwatchView * analogStopwatch;                             //@synthesize analogStopwatch=_analogStopwatch - In the implementation block
@property (nonatomic,retain) UIView * digitalStopwatchContainer;                                  //@synthesize digitalStopwatchContainer=_digitalStopwatchContainer - In the implementation block
@property (nonatomic,retain) MTTimeView * timeView;                                               //@synthesize timeView=_timeView - In the implementation block
@property (nonatomic,retain) NSArray * constraints;                                               //@synthesize constraints=_constraints - In the implementation block
@property (assign,nonatomic) CGSize latestLayoutSize;                                             //@synthesize latestLayoutSize=_latestLayoutSize - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)stopwatchPagingViewController:(id)arg1 didPage:(unsigned)arg2 ;
-(void)setLapTableController:(MTStopwatchLapTableViewController *)arg1 ;
-(MTStopwatchLapTableViewController *)lapTableController;
-(MTAnalogStopwatchView *)analogStopwatch;
-(MTStopwatchController *)stopwatchController;
-(void)updateShortcutItemForCurrentState;
-(void)updateTimeViewFont;
-(void)setStopwatchController:(MTStopwatchController *)arg1 ;
-(void)setLapButtonOccludingView:(UIImageView *)arg1 ;
-(UIImageView *)lapButtonOccludingView;
-(void)setStartButtonOccludingView:(UIImageView *)arg1 ;
-(UIImageView *)startButtonOccludingView;
-(void)setDigitalStopwatchContainer:(UIView *)arg1 ;
-(UIView *)digitalStopwatchContainer;
-(void)setAnalogStopwatch:(MTAnalogStopwatchView *)arg1 ;
-(void)setAnalogStopwatchContainer:(UIView *)arg1 ;
-(UIView *)analogStopwatchContainer;
-(CGSize)latestLayoutSize;
-(void)setLatestLayoutSize:(CGSize)arg1 ;
-(void)_restoreIdleTimer;
-(void)_clearAllLaps;
-(void)_addLap:(double)arg1 ;
-(id)shortcutItemForCurrentState;
-(id)shortcutItemForMode:(int)arg1 ;
-(id)startStopwatchShortcutItemForMode:(int)arg1 ;
-(id)stopStopwatchShortcutItem;
-(void)pauseLapTimer;
-(double)_timeAdjustedFor30fpsDisplay:(double)arg1 ;
-(void)startLapTimer;
-(void)resumeLapTimer;
-(void)lapLapTimer;
-(void)resetLapTimer;
-(id)defaultShortcutItem;
-(void)handleStartStopwatchShortcutAction;
-(void)handleStopStopwatchShortcutAction;
-(double)runningTotalForLap:(int)arg1 ;
-(id)init;
-(void)dealloc;
-(void)traitCollectionDidChange:(id)arg1 ;
-(char)prefersStatusBarHidden;
-(void)loadView;
-(NSArray *)constraints;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidAppear:(char)arg1 ;
-(void)viewWillDisappear:(char)arg1 ;
-(void)viewDidLayoutSubviews;
-(MTStopwatchLapTableHeaderView *)tableHeaderView;
-(void)setTableHeaderView:(MTStopwatchLapTableHeaderView *)arg1 ;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)viewDidLoad;
-(void)updateViewConstraints;
-(void)setConstraints:(NSArray *)arg1 ;
-(void)setMode:(int)arg1 ;
-(void)_startTimer;
-(void)_stopTimer;
-(UIPageControl *)pageControl;
-(void)updateTime;
-(void)_tick:(id)arg1 ;
-(Class)tableCellClass;
-(MTTimeView *)timeView;
-(void)saveState;
-(void)setPageControl:(UIPageControl *)arg1 ;
-(void)setPagingViewController:(MTStopwatchPagingViewController *)arg1 ;
-(MTStopwatchPagingViewController *)pagingViewController;
-(void)reloadState;
-(void)setTimeView:(MTTimeView *)arg1 ;
-(void)handleLocaleChange;
@end

