/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:39:17 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol CollectionViewDelegateBookmarkFavoritesGridLayout <UICollectionViewDelegateFlowLayout>
@optional
-(CGRect*)collectionView:(id)arg1 layout:(id)arg2 iconRectForItemAtIndexPath:(id)arg3;
-(id)collectionView:(id)arg1 deleteInsertPairsToTreatAsMovesForLayout:(id)arg2;

@end

