/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:25:13 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SafariServices/_SFBrowserSavedState.h>

@interface PPTTestBrowserSavedState : _SFBrowserSavedState
-(id)savedTabsStateForBrowserControllerWithUUID:(id)arg1 ;
-(char)activeDocumentIsValidForBrowserControllerWithUUID:(id)arg1 ;
@end

