/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:39:17 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <MobileSafari/MobileSafari-Structs.h>
@class CADisplayLink;

@interface ReorderingAutoscroller : NSObject {

	CADisplayLink* _displayLink;
	CGPoint _offsetError;
	/*^block*/id _scrollHandler;
	CGPoint _velocity;
	float _maximumSpeed;
	CGRect _scrollableRect;
	UIEdgeInsets _autoscrollInsets;

}

@property (assign,nonatomic) CGRect scrollableRect;                      //@synthesize scrollableRect=_scrollableRect - In the implementation block
@property (assign,nonatomic) UIEdgeInsets autoscrollInsets;              //@synthesize autoscrollInsets=_autoscrollInsets - In the implementation block
@property (assign,nonatomic) float maximumSpeed;                         //@synthesize maximumSpeed=_maximumSpeed - In the implementation block
-(void)endInteraction;
-(void)setScrollableRect:(CGRect)arg1 ;
-(void)updateInteractionAtPoint:(CGPoint)arg1 ;
-(void)beginInteractionWithScrollHandler:(/*^block*/id)arg1 ;
-(void)_autoscroll:(id)arg1 ;
-(CGRect)scrollableRect;
-(UIEdgeInsets)autoscrollInsets;
-(void)setAutoscrollInsets:(UIEdgeInsets)arg1 ;
-(id)init;
-(void)dealloc;
-(void)_setVelocity:(CGPoint)arg1 ;
-(float)maximumSpeed;
-(void)setMaximumSpeed:(float)arg1 ;
@end

