/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:25:11 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SidebarInteractionReporterDelegate;
@class NSDate;

@interface SidebarInteractionReporter : NSObject {

	NSDate* _lastSidebarSelectionDate;
	id<SidebarInteractionReporterDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<SidebarInteractionReporterDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)reportUserSelectedFromSidebarSection:(int)arg1 ;
-(void)reportUserClosedSidebar;
-(char)_shouldReportEventsForCurrentApplicationState;
-(void)setDelegate:(id<SidebarInteractionReporterDelegate>)arg1 ;
-(id<SidebarInteractionReporterDelegate>)delegate;
-(id)initWithDelegate:(id)arg1 ;
@end

