/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:49 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileCal/ApplicationTest.h>

@interface AnimationTest : ApplicationTest
+(id)_delaySubTestName;
+(id)_animationSubTestName;
-(void)runTest;
-(void)_animationCompleted;
-(void)kickOffAnimation;
-(void)dealloc;
-(void)setUp;
-(id)notificationName;
@end

