/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:49 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileCal/MobileCal-Structs.h>
#import <MobileCal/DayNavigationViewCell.h>

@class NSString, TappableDayNumber, UILabel, EKUITodayCirclePulseView, UIColor, UIView;

@interface CompactDayNavigationViewCell : DayNavigationViewCell {

	char _monthAnimationState;
	char _hasOverlay;
	NSString* _displayString;
	NSString* _overlayString;
	TappableDayNumber* _dateNumber;
	UILabel* _monthAnimationStateDayNumber;
	UILabel* _monthAnimationStateOverlay;
	float _circleDiameter;
	float _circleDiameterOverlay;
	float _circleDiameterOverlayLarge;
	EKUITodayCirclePulseView* _pulseView;
	UIColor* _weekendColor;
	char _verticallyCompressedState;
	float _baselineOffset;
	UIView* _eventCountsSubview;
	UILabel* _label;

}

@property (nonatomic,retain) UIColor * weekendColor; 
@property (assign,nonatomic) float baselineOffset;                        //@synthesize baselineOffset=_baselineOffset - In the implementation block
@property (nonatomic,readonly) CGRect circleFrame; 
@property (nonatomic,retain) UIView * eventCountsSubview;                 //@synthesize eventCountsSubview=_eventCountsSubview - In the implementation block
@property (assign,nonatomic) char monthAnimationState; 
@property (assign,nonatomic) char verticallyCompressedState;              //@synthesize verticallyCompressedState=_verticallyCompressedState - In the implementation block
@property (nonatomic,readonly) UILabel * label;                           //@synthesize label=_label - In the implementation block
+(float)standardCircleDiameter;
+(float)overlayCircleDiameter;
+(float)largeOverlayCircleDiameter;
+(id)_boldFont;
+(id)_overlayFont;
+(float)circleDiameter;
+(void)localeChanged;
-(CGRect)circleFrame;
-(id)initWithFrame:(CGRect)arg1 loadMonthAnimationState:(char)arg2 hasOverlay:(char)arg3 ;
-(void)_createMonthAnimationStateModeSubviews;
-(void)setCircled:(char)arg1 ;
-(void)setIsToday:(char)arg1 ;
-(void)setIsWeekend:(char)arg1 ;
-(void)touchDownOccurred:(id)arg1 ;
-(void)touchUpOccurred:(id)arg1 ;
-(void)_loadMonthAnimationStateOverlayIfNeeded;
-(void)setWeekendColor:(UIColor *)arg1 ;
-(UIColor *)weekendColor;
-(void)setCircled:(char)arg1 animated:(char)arg2 ;
-(UIView *)eventCountsSubview;
-(void)setDate:(id)arg1 forceStringUpdate:(char)arg2 ;
-(void)setDisplayedString:(id)arg1 ;
-(void)updateOverlay;
-(void)_updateDisplayedString;
-(void)setUnderlineThickness:(float)arg1 ;
-(float)_circleDiameter;
-(float)yCenterForDayNumbers;
-(char)verticallyCompressedState;
-(void)setMonthAnimationState:(char)arg1 ;
-(char)monthAnimationState;
-(void)setVerticallyCompressedState:(char)arg1 ;
-(void)setEventCountsSubview:(UIView *)arg1 ;
-(void)setCircleDiameter:(float)arg1 overlayDiameter:(float)arg2 largeOverlayDiameter:(float)arg3 ;
-(float)_circleXForDiameter:(float)arg1 ;
-(void)pulseToday;
-(void)stopPulsing;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)setNeedsDisplay;
-(void)setBackgroundColor:(id)arg1 ;
-(void)prepareForReuse;
-(UILabel *)label;
-(float)baselineOffset;
-(void)setBaselineOffset:(float)arg1 ;
-(void)setDate:(id)arg1 ;
-(void)touchCancelled:(id)arg1 ;
-(void)_createSubviews;
-(void)setOverlayString:(id)arg1 ;
-(void)_updateTextColor;
@end

