/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:55 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Fitness/MonthViewController.h>

@interface CompactMonthViewController : MonthViewController {

	char _applicationResuming;
	char _needsPaletteLayout;

}
+(float)scrubbingMinimumPressDuration;
-(char)shouldPushNextLevelViewControllerWhenTodayIsVisible;
-(void)updatePalette:(id)arg1 ;
-(void)setShouldRespondToApplicationDidBecomeActiveStateChange:(char)arg1 ;
-(void)weekNumbersPrefChanged;
-(void)_updateDayHeaderFrames;
-(float)palleteViewXOffset;
-(void)viewDidLayoutSubviews;
@end

