/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:54 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileCal/ApplicationTest.h>

@class DayViewController;

@interface PhoneDayViewHorizontalScrollTest : ApplicationTest {

	unsigned _daysToScroll;
	DayViewController* _dayViewController;

}
-(void)runTest;
-(void)_mainLoop;
-(void)dealloc;
@end

