/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:55 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileCal/ApplicationTest.h>

@class RootNavigationController, ListViewController;

@interface SearchViewLaunchTest : ApplicationTest {

	unsigned _iterations;
	char _inputInvalid;
	RootNavigationController* _rootNavController;
	ListViewController* _listViewController;

}
-(void)runTest;
-(id)initWithApplication:(id)arg1 model:(id)arg2 options:(id)arg3 ;
-(void)_searchViewDidAppear;
-(void)dealloc;
@end

