/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:56 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@protocol WeekViewAllDayContentsDelegate;
@interface WeekViewAllDayContents : UIView {

	id<WeekViewAllDayContentsDelegate> _delegate;

}

@property (__weak) id<WeekViewAllDayContentsDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)setDelegate:(id<WeekViewAllDayContentsDelegate>)arg1 ;
-(id<WeekViewAllDayContentsDelegate>)delegate;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
@end

