/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:39:19 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileSlideShow.app/PlugIns/PhotosNotificationsUpdates.appex/PhotosNotificationsUpdates
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <PhotosNotificationsUpdates/PhotosNotificationsUpdates-Structs.h>
#import <UIKit/UIViewController.h>
#import <libobjc.A.dylib/UNNotificationContentExtension.h>

@class UIColor, PUOneUpPresentationHelper, UIViewController, NSString;

@interface PhotosNotificationsUpdatesViewController : UIViewController <UNNotificationContentExtension> {

	PUOneUpPresentationHelper* _oneUpPresentationHelper;
	UIViewController* _previewViewController;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) unsigned mediaPlayPauseButtonType; 
@property (nonatomic,readonly) CGRect mediaPlayPauseButtonFrame; 
@property (nonatomic,copy,readonly) UIColor * mediaPlayPauseButtonTintColor; 
-(id)_photosDataSourceForAssetUUID:(id)arg1 ;
-(void)_updatePreferredContentSizeForPreferredPreviewSize:(CGSize)arg1 ;
-(void)_presentOneUpViewControllerForAssetUUID:(id)arg1 ;
-(void)_likeAssetWithCloudAssetUUID:(id)arg1 ;
-(void)_sendComment:(id)arg1 toAssetWithCloudAssetUUID:(id)arg2 ;
-(void)_dismissOneUpViewController;
-(void)loadView;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidAppear:(char)arg1 ;
-(void)viewWillDisappear:(char)arg1 ;
-(void)viewDidDisappear:(char)arg1 ;
-(void)didReceiveNotification:(id)arg1 ;
-(void)didReceiveNotificationResponse:(id)arg1 withCompletion:(/*^block*/id)arg2 ;
@end

