/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:25:25 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/PreBoard.app/PreBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class BKSHIDEventRouter, NSArray;

@interface PBAHIDEventController : NSObject {

	BKSHIDEventRouter* _eventRouter;
	NSArray* _savedEventRouters;

}

@property (nonatomic,retain) BKSHIDEventRouter * eventRouter;              //@synthesize eventRouter=_eventRouter - In the implementation block
@property (nonatomic,copy) NSArray * savedEventRouters;                    //@synthesize savedEventRouters=_savedEventRouters - In the implementation block
+(id)sharedController;
-(void)setSavedEventRouters:(NSArray *)arg1 ;
-(void)startReceivingEvents;
-(void)stopReceivingEvents;
-(BKSHIDEventRouter *)eventRouter;
-(void)setEventRouter:(BKSHIDEventRouter *)arg1 ;
-(NSArray *)savedEventRouters;
-(id)init;
@end

