/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:26 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/HashtagImages.app/PlugIns/HashtagImagesExtension.appex/HashtagImagesExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SGSuggestionsServiceSearchToShareProtocol;
@class NSObject, PARSession;

@interface STSFeedbackReporter : NSObject {

	NSObject*<SGSuggestionsServiceSearchToShareProtocol> _suggestionsService;
	PARSession* _parsecSession;

}

@property (nonatomic,retain) PARSession * parsecSession;              //@synthesize parsecSession=_parsecSession - In the implementation block
+(id)sharedInstance;
-(void)didLoadResults:(id)arg1 indexPaths:(id)arg2 ;
-(void)didShowQuerySuggestions:(id)arg1 ;
-(PARSession *)parsecSession;
-(void)setParsecSession:(PARSession *)arg1 ;
-(void)didSearchWithSuggestedQuery:(id)arg1 ;
-(void)didEngageProviderLogo;
-(void)searchBarDidCancel;
-(void)didSearchWithCustomQuery:(id)arg1 ;
-(void)searchViewDidDisappear;
-(void)searchViewDidAppearWithEvent:(unsigned)arg1 ;
-(void)didPreviewResult:(id)arg1 peek:(char)arg2 ;
-(void)didShowResults:(id)arg1 scrolling:(char)arg2 ;
-(id)didStartNetworkRequest:(id)arg1 query:(id)arg2 ;
-(void)didEndNetworkRequest:(id)arg1 infoDict:(id)arg2 ;
-(void)didShowProactiveSuggestions:(id)arg1 conversationId:(id)arg2 ;
-(void)resourceDidLoad:(id)arg1 ;
-(id)init;
-(void)didEngageResult:(id)arg1 ;
@end

