/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:24 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Fitness.app/PlugIns/activity-widget.appex/activity-widget
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class HKHealthStore, NSCalendar, HKActivitySummary;

@interface CHActivityWidgetDataProvider : NSObject {

	HKHealthStore* _healthStore;
	NSCalendar* _gregorianCalendar;
	HKActivitySummary* _lastActivitySummary;

}

@property (nonatomic,retain) HKActivitySummary * lastActivitySummary;              //@synthesize lastActivitySummary=_lastActivitySummary - In the implementation block
-(void)setLastActivitySummary:(HKActivitySummary *)arg1 ;
-(void)refreshTodayActivitySummaryWithCompletion:(/*^block*/id)arg1 ;
-(HKActivitySummary *)lastActivitySummary;
-(id)initWithHealthStore:(id)arg1 ;
@end

