/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:22 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Health.app/Health
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Health/WDDashboardCellPrimaryValueSource.h>

@protocol WDDashboardCellPrimaryValueSourceDelegate;
@class HKDataUnit, HKDataCategory, NSString, NSDate;

@interface WDCurrentValueTVCDemoFakePrimaryValueSource : NSObject <WDDashboardCellPrimaryValueSource> {

	id<WDDashboardCellPrimaryValueSourceDelegate> primaryValueSourceDelegate;
	NSDate* lastUpdated;
	HKDataUnit* _dataUnit;
	HKDataCategory* _dataCategory;
	NSString* _mostRecentValueText;
	NSString* _mostRecentUnitText;
	NSString* _primaryValueContextualText;
	unsigned _marginMode;

}

@property (nonatomic,retain) HKDataUnit * dataUnit;                                                                        //@synthesize dataUnit=_dataUnit - In the implementation block
@property (nonatomic,retain) HKDataCategory * dataCategory;                                                                //@synthesize dataCategory=_dataCategory - In the implementation block
@property (nonatomic,retain) NSString * mostRecentValueText;                                                               //@synthesize mostRecentValueText=_mostRecentValueText - In the implementation block
@property (nonatomic,retain) NSString * mostRecentUnitText;                                                                //@synthesize mostRecentUnitText=_mostRecentUnitText - In the implementation block
@property (nonatomic,retain) NSString * primaryValueContextualText;                                                        //@synthesize primaryValueContextualText=_primaryValueContextualText - In the implementation block
@property (assign,nonatomic) unsigned marginMode;                                                                          //@synthesize marginMode=_marginMode - In the implementation block
@property (assign,nonatomic,__weak) id<WDDashboardCellPrimaryValueSourceDelegate> primaryValueSourceDelegate; 
@property (nonatomic,readonly) NSDate * lastUpdated; 
-(void)setDataUnit:(HKDataUnit *)arg1 ;
-(void)setMarginMode:(unsigned)arg1 ;
-(unsigned)marginMode;
-(NSString *)mostRecentValueText;
-(NSString *)mostRecentUnitText;
-(id)mostRecentValueWithValueFont:(id)arg1 unitFont:(id)arg2 ;
-(id<WDDashboardCellPrimaryValueSourceDelegate>)primaryValueSourceDelegate;
-(void)setPrimaryValueSourceDelegate:(id<WDDashboardCellPrimaryValueSourceDelegate>)arg1 ;
-(NSString *)primaryValueContextualText;
-(void)setMostRecentValueText:(NSString *)arg1 ;
-(void)setMostRecentUnitText:(NSString *)arg1 ;
-(void)setPrimaryValueContextualText:(NSString *)arg1 ;
-(NSDate *)lastUpdated;
-(void)setDataCategory:(HKDataCategory *)arg1 ;
-(HKDataUnit *)dataUnit;
-(HKDataCategory *)dataCategory;
@end

