/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:27 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Health.app/Health
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Health/WDDashboardCellPrimaryValueSource.h>

@protocol WDDashboardCellPrimaryValueSourceDelegate, WDDataProviderValue;
@class HKDataUnit, HKDataCategory, NSDate, NSSet, WDControllerManager, NSString;

@interface WDDashboardSummaryItem : NSObject <WDDashboardCellPrimaryValueSource> {

	id<WDDashboardCellPrimaryValueSourceDelegate> _primaryValueSourceDelegate;
	HKDataUnit* _dataUnit;
	HKDataCategory* _dataCategory;
	NSDate* _lastUpdated;
	NSSet* _summaries;
	WDControllerManager* _controllerManager;
	id<WDDataProviderValue> _valueFormatter;

}

@property (nonatomic,retain) WDControllerManager * controllerManager;                                                      //@synthesize controllerManager=_controllerManager - In the implementation block
@property (nonatomic,retain) id<WDDataProviderValue> valueFormatter;                                                       //@synthesize valueFormatter=_valueFormatter - In the implementation block
@property (nonatomic,readonly) NSSet * summaries;                                                                          //@synthesize summaries=_summaries - In the implementation block
@property (assign,nonatomic,__weak) id<WDDashboardCellPrimaryValueSourceDelegate> primaryValueSourceDelegate;              //@synthesize primaryValueSourceDelegate=_primaryValueSourceDelegate - In the implementation block
@property (nonatomic,readonly) HKDataUnit * dataUnit;                                                                      //@synthesize dataUnit=_dataUnit - In the implementation block
@property (nonatomic,readonly) HKDataCategory * dataCategory;                                                              //@synthesize dataCategory=_dataCategory - In the implementation block
@property (nonatomic,readonly) NSString * primaryValueContextualText; 
@property (nonatomic,readonly) NSDate * lastUpdated;                                                                       //@synthesize lastUpdated=_lastUpdated - In the implementation block
-(NSSet *)summaries;
-(WDControllerManager *)controllerManager;
-(void)setControllerManager:(WDControllerManager *)arg1 ;
-(id)initWithSummary:(id)arg1 controllerManager:(id)arg2 ;
-(id)initWithSystolicSummary:(id)arg1 diastolicSummary:(id)arg2 controllerManager:(id)arg3 ;
-(char)containsActivitySummary;
-(id)mostRecentValueWithValueFont:(id)arg1 unitFont:(id)arg2 ;
-(id<WDDashboardCellPrimaryValueSourceDelegate>)primaryValueSourceDelegate;
-(void)setPrimaryValueSourceDelegate:(id<WDDashboardCellPrimaryValueSourceDelegate>)arg1 ;
-(NSString *)primaryValueContextualText;
-(NSDate *)lastUpdated;
-(void)setValueFormatter:(id<WDDataProviderValue>)arg1 ;
-(id<WDDataProviderValue>)valueFormatter;
-(HKDataUnit *)dataUnit;
-(HKDataCategory *)dataCategory;
@end

