/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:28 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Health.app/Health
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class UILabel, NSLayoutConstraint, NSString;

@interface WDHealthDataCategoryTitleTableViewCell : UITableViewCell {

	UILabel* _titleLabel;
	NSLayoutConstraint* _topLayoutConstraint;
	NSLayoutConstraint* _bottomLayoutConstraint;
	int _headerType;
	float _bottomLeading;
	NSString* _titleText;

}

@property (nonatomic,copy) NSString * titleText;              //@synthesize titleText=_titleText - In the implementation block
-(id)initWithHeaderType:(int)arg1 reuseIdentifier:(id)arg2 ;
-(void)setBottomLeading:(float)arg1 ;
-(float)_titleLabelTopToBaseline;
-(float)_titleLabelBaselineToBottom;
-(id)initWithCoder:(id)arg1 ;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
-(void)setTitleText:(NSString *)arg1 ;
-(NSString *)titleText;
-(void)_setupUI;
-(id)_titleLabelFont;
-(void)setHeaderType:(int)arg1 ;
@end

