/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:28 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Health.app/Health
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Health/Health-Structs.h>
#import <UIKit/UITableViewCell.h>
#import <UIKit/UICollectionViewDataSource.h>
#import <UIKit/UICollectionViewDelegate.h>

@protocol WDHealthDataTopLevelCategoryTableViewCellDelegate;
@class NSArray, NSMutableDictionary, UICollectionView, NSString;

@interface WDHealthDataTopLevelCategoryTableViewCell : UITableViewCell <UICollectionViewDataSource, UICollectionViewDelegate> {

	NSArray* _topLevelDataCategories;
	NSMutableDictionary* _topCategoryFrames;
	UICollectionView* _collectionView;
	id<WDHealthDataTopLevelCategoryTableViewCellDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<WDHealthDataTopLevelCategoryTableViewCellDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(float)_contentItemHeight;
+(float)_collectionViewMargin;
+(float)contentHeightWithCount:(unsigned)arg1 ;
+(float)_collectionViewWidth;
+(float)_contentItemWidth;
+(char)requiresConstraintBasedLayout;
+(id)reuseIdentifier;
-(void)_setupCollectionView;
-(CGSize)_contentItemSize;
-(CGRect)_collectionViewFrame;
-(float)_categoryNameWidth;
-(float)_categoryNameFittingScaleFactor;
-(float)categoryNameLabelFontSize;
-(id)initWithTopLevelDataCategories:(id)arg1 ;
-(id)topCategoryFrames;
-(id)initWithCoder:(id)arg1 ;
-(void)setDelegate:(id<WDHealthDataTopLevelCategoryTableViewCellDelegate>)arg1 ;
-(void)dealloc;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
-(id<WDHealthDataTopLevelCategoryTableViewCellDelegate>)delegate;
-(int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2 ;
-(id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2 ;
-(void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2 ;
-(void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3 ;
-(float)contentHeight;
@end

