/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:23 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Health.app/Health
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Health/WDSampleListDataProvider.h>

@class NSMutableDictionary, NSMutableArray, WDControllerManager;

@interface WDSleepListDataProvider : WDSampleListDataProvider {

	NSMutableDictionary* _sleepData;
	NSMutableArray* _orderedKeys;
	WDControllerManager* _controllerManager;

}
-(id)sampleTypes;
-(id)dataListViewController:(id)arg1 textForObject:(id)arg2 ;
-(unsigned)dataListViewController:(id)arg1 numberOfObjectsForSection:(unsigned)arg2 ;
-(id)dataListViewController:(id)arg1 objectAtIndex:(unsigned)arg2 forSection:(unsigned)arg3 ;
-(id)dataListViewController:(id)arg1 viewControllerForItemAtIndexPath:(id)arg2 ;
-(int)cellStyleForDataListViewController:(id)arg1 ;
-(unsigned)numberOfSectionsForDataListViewController:(id)arg1 ;
-(id)dataListViewController:(id)arg1 titleForSection:(unsigned)arg2 ;
-(id)dataListViewController:(id)arg1 secondaryTextForObject:(id)arg2 ;
-(void)dataListViewController:(id)arg1 didRemoveObjectAtIndex:(unsigned)arg2 forSection:(unsigned)arg3 sectionRemoved:(char*)arg4 ;
-(void)dataListViewControllerDidDeleteAllData:(id)arg1 ;
-(id)_sleepDataDictionaryFromSamples:(id)arg1 ;
-(id)_sleepSampleAtIndex:(unsigned)arg1 section:(unsigned)arg2 ;
-(void)_callUpdateHandler;
@end

