/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:24:22 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Health.app/Health
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Health/Health-Structs.h>
#import <UIKit/UIView.h>
#import <UIKit/UIScrollViewDelegate.h>

@protocol WDTimelineViewDelegate;
@class UIScrollView, NSDate, NSString;

@interface WDTimelineView : UIView <UIScrollViewDelegate> {

	UIScrollView* _scrollView;
	double _leftEdge;
	double _rightEdge;
	char _listenForScrollViewUpdates;
	id<WDTimelineViewDelegate> _delegate;
	NSDate* _minDate;
	NSDate* _maxDate;
	double _timeframe;
	double _anchorTime;

}

@property (assign,nonatomic) double anchorTime;                                       //@synthesize anchorTime=_anchorTime - In the implementation block
@property (assign,nonatomic,__weak) id<WDTimelineViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) NSDate * minDate;                                      //@synthesize minDate=_minDate - In the implementation block
@property (nonatomic,readonly) NSDate * maxDate;                                      //@synthesize maxDate=_maxDate - In the implementation block
@property (assign,nonatomic) double timeframe;                                        //@synthesize timeframe=_timeframe - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithFrame:(CGRect)arg1 minDate:(id)arg2 maxDate:(id)arg3 ;
-(double)_currentTimeFrame;
-(void)_adjustAnchorTime;
-(void)_resetScrollViewIfNecessary;
-(void)_alertDelegateDidChange;
-(void)_resetScrollView;
-(void)setAnchorTime:(double)arg1 ;
-(void)_alertDelegateDidReassessConstraints;
-(void)_contentOffsetDidChange;
-(void)setTimeframe:(double)arg1 ;
-(id)leftEdge;
-(id)rightEdge;
-(double)timeframe;
-(double)anchorTime;
-(id)init;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)setDelegate:(id<WDTimelineViewDelegate>)arg1 ;
-(void)scrollViewDidScroll:(id)arg1 ;
-(id<WDTimelineViewDelegate>)delegate;
-(id)startDate;
-(id)endDate;
-(void)setAnchorDate:(id)arg1 ;
-(NSDate *)minDate;
-(NSDate *)maxDate;
@end

