/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 30, 2017 at 11:25:03 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileNotes.app/PlugIns/com.apple.mobilenotes.SharingExtension.appex/com.apple.mobilenotes.SharingExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <com.apple.mobilenotes.SharingExtension/com.apple.mobilenotes.SharingExtension-Structs.h>
#import <MobileNotes/ICAudioPlayPauseView.h>

@protocol ICAttachmentBrickAudioPlayerViewDelegate;
@class ICArcLayer;

@interface ICAttachmentBrickAudioPlayerView : ICAudioPlayPauseView {

	id<ICAttachmentBrickAudioPlayerViewDelegate> _delegate;
	ICArcLayer* _progressCircleLayer;

}

@property (nonatomic,retain) ICArcLayer * progressCircleLayer;                                   //@synthesize progressCircleLayer=_progressCircleLayer - In the implementation block
@property (assign,nonatomic) id<ICAttachmentBrickAudioPlayerViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)sharedInit;
-(void)createBackgroundLayer;
-(void)createPlayPauseViews;
-(void)showStopped;
-(void)showPressed:(char)arg1 ;
-(void)updateTime:(double)arg1 duration:(double)arg2 ;
-(void)createProgressCircleLayer;
-(void)setProgressCircleLayer:(ICArcLayer *)arg1 ;
-(ICArcLayer *)progressCircleLayer;
-(void)showDisabled:(char)arg1 ;
-(void)setDelegate:(id<ICAttachmentBrickAudioPlayerViewDelegate>)arg1 ;
-(void)didMoveToWindow;
-(void)setBounds:(CGRect)arg1 ;
-(id<ICAttachmentBrickAudioPlayerViewDelegate>)delegate;
-(id)tintColor;
-(CGSize)intrinsicContentSize;
-(char)isAccessibilityElement;
@end

