/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:39:07 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/MobileNotes.app/PlugIns/com.apple.mobilenotes.SharingExtension.appex/com.apple.mobilenotes.SharingExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <com.apple.mobilenotes.SharingExtension/com.apple.mobilenotes.SharingExtension-Structs.h>
@class ICAttachment, NSString, NSURL, NSData, NSAttributedString, UIImage;

@interface ICSharingExtensionAttachmentInfo : NSObject {

	ICAttachment* _attachment;
	NSString* _title;
	NSURL* _mediaURL;
	NSString* _mediaUTI;
	NSData* _mediaData;
	NSString* _mediaFilenameExtension;
	UIImage* _image;
	NSAttributedString* _attributedContentText;

}

@property (nonatomic,retain) ICAttachment * attachment;                               //@synthesize attachment=_attachment - In the implementation block
@property (nonatomic,retain) NSString * title;                                        //@synthesize title=_title - In the implementation block
@property (nonatomic,retain) NSURL * mediaURL;                                        //@synthesize mediaURL=_mediaURL - In the implementation block
@property (nonatomic,retain) NSString * mediaUTI;                                     //@synthesize mediaUTI=_mediaUTI - In the implementation block
@property (nonatomic,retain) NSData * mediaData;                                      //@synthesize mediaData=_mediaData - In the implementation block
@property (nonatomic,retain) NSString * mediaFilenameExtension;                       //@synthesize mediaFilenameExtension=_mediaFilenameExtension - In the implementation block
@property (nonatomic,retain) UIImage * image;                                         //@synthesize image=_image - In the implementation block
@property (nonatomic,retain) NSAttributedString * attributedContentText;              //@synthesize attributedContentText=_attributedContentText - In the implementation block
-(NSString *)mediaUTI;
-(void)setMediaUTI:(NSString *)arg1 ;
-(NSString *)mediaFilenameExtension;
-(void)setMediaFilenameExtension:(NSString *)arg1 ;
-(NSAttributedString *)attributedContentText;
-(void)setImage:(UIImage *)arg1 ;
-(void)setTitle:(NSString *)arg1 ;
-(id)description;
-(NSString *)title;
-(UIImage *)image;
-(id)initWithFileURL:(id)arg1 ;
-(void)setAttachment:(ICAttachment *)arg1 ;
-(ICAttachment *)attachment;
-(void)setAttributedContentText:(NSAttributedString *)arg1 ;
-(void)setMediaURL:(NSURL *)arg1 ;
-(NSURL *)mediaURL;
-(NSData *)mediaData;
-(void)setMediaData:(NSData *)arg1 ;
@end

