/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 29, 2017 at 6:38:00 PM Japan Standard Time
* Operating System: Version 10.3.3 (Build 14G60)
* Image Source: /Applications/Bridge.app/Bridge
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Bridge/COSOptinViewController.h>

@protocol OS_dispatch_source;
@class NSObject;

@interface COSResetWatchNoticeViewController : COSOptinViewController {

	NSObject*<OS_dispatch_source> _discoveryTimer;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_source> discoveryTimer;              //@synthesize discoveryTimer=_discoveryTimer - In the implementation block
+(char)controllerNeedsToRun;
-(void)applyConfirmedOptin:(char)arg1 ;
-(id)detailString;
-(void)selectedOptinChoice:(id)arg1 ;
-(id)suggestedButtonString;
-(id)alternateButtonString;
-(id)aboutButtonString;
-(id)detailTitleString;
-(void)selectedAboutDetail:(id)arg1 ;
-(char)legacyButtonStyles;
-(id)moreOptionsButtonString;
-(void)selectedMoreOptions:(id)arg1 ;
-(void)discoveredAdvertisingWatch:(id)arg1 ;
-(void)cancelDiscoveryTimer;
-(void)beginDiscoveryTimer;
-(NSObject*<OS_dispatch_source>)discoveryTimer;
-(void)setDiscoveryTimer:(NSObject*<OS_dispatch_source>)arg1 ;
-(id)init;
-(void)dealloc;
-(void)viewDidAppear:(char)arg1 ;
-(void)viewDidDisappear:(char)arg1 ;
-(id)titleString;
-(id)imageResource;
@end

